truenas/documentation

content/en/hub/tasks/scheduled/rsync.md
I know at least one place that uses TrueNAS that has people who use screen readers due to poor eyesight, so we should probably get in the habit of including screen reader codes whenever we use a Font Awesome asset.  I am adding these to the TC docs and remembered seeing this one recently so I figured I might as well file the PR while it was on my mind. 
=> add screen reader text for icon for accessibility needs

config.toml
I found a way to leave the 11.3 entry in the list. But now it is more clear. Links are relative so you don't get that issue of not changing a page when switching between 11.3 and 12.0
=> DOCS-813 make version drop down more clear.

content/en/hub/sharing/iscsi/iscsi-share.md
=> escape '--' because it rendered as one dash.

assets/scss/_variables_project.scss, content/en/_index.html
- Remove obsolete css for links on grey backgrounds (site styling went a different direction)
- Review front page and remove references to obsolete lightlink rules
=> DOCS-834: Remove obsolete "lightlink" rules

content/en/hub/intro/COREHardwareGuide.md
The phrase "right of passage" does not exist. It should instead say "rite of passage".
=> Small grammatical change

content/en/hub/additional-topics/reference/ZFS-references.md
Erroneous left caret inside markdown for COW link.
=> Fix COW link typo

content/en/hub/tasks/advanced/virtual-machines.md
I added a small amount of text to the article that explains the behavior for the state toggle and Stop buttons when the VM has no Guest OS installed.
=> DOCS-1317: Update virtual-machines.md

content/en/hub/tasks/scheduled/replication/remote-ssh.md
Clarify that a dataset is used for the remote destination of  Replication task and that zvols are not to be used
=> DOCS-1451 - Clarify that the destination of a Replication task will be a dataset

content/en/hub/tasks/scheduled/snapshot-scheduling.md
See PR, try to make this a solid reference to the periodic snapshots.  For example, deletion process (and robustness if snapshot tasks named identically), naming, other strptime() variables linked in Python docs, using multiple periodic snapshot tasks (eg 1 hr for a week, then daily for 3 years), recursive setting, and so on.
=> More in-depth info on periodic snapshots

content/en/hub/sharing/smb/smb-share.md
Added breaks between two graphics at line 177 and 208
=> Line breaks after graphics in smb-share.md

content/en/hub/sharing/afp/afp-share.md
Updating the afp-share.md so that there is a space after the graphics
=> Updating the afp-share.md

content/TrueCommand/API/sys/_index.md
=> DOCS-1667: Add nolisttrue to TC API sys2 index

content/TrueCommand/API/license/_index.md
=> DOCS-1667: Add nolisttrue to TC API license index

content/en/hub/sharing/s3-object-store/_index.md
Allow image to be visible
Fixes [page](https://www.truenas.com/docs/hub/sharing/s3-object-store/) that looks like this:
=> Remove extra quote character in img tag

content/ReleaseNotes/SCALE/21.04-ALPHA.1.md
Update changelog version to show "21.04-ALPHA.1 Changelog". Currently it shows previous version "21.02-ALPHA.1 Changelog"
=> Update changelog version

content/Archive.md
Edited the EoL 11.3-U5 User Guide PDF and added the HA upgrade warning to the beginning of the doc and at the beginning of the System > Failover section. Uploaded the modified PDF to the web server and am modifying the archive link to point to this updated file.
=> DOCS-2133: Add HA Upgrade warning to archived doc

content/CORE/System/2FA.md
Small rework to note the 2FA field and possible need to refresh the browser (helpful for High Availability systems in a failover situation).
=> DOCS-2192: Small change to 2FA login procedure

content/ReleaseNotes/SCALE/21.02-ALPHA.1.md
Hey, I found that one link was not working for release notes. It was not redirecting to developer notes. I fixed that (tested with Hugo).
=> Fixing link to kubernetes integration

content/TrueCommand/API/alerts/_index.md, content/TrueCommand/API/cluster/_index.md, content/TrueCommand/API/email/_index.md, content/TrueCommand/API/freenas/_index.md, content/TrueCommand/API/license/_index.md, content/TrueCommand/API/notices/_index.md, content/TrueCommand/API/reports/_index.md, content/TrueCommand/API/servers/_index.md, content/TrueCommand/API/teams/_index.md, content/TrueCommand/API/users/_index.md, content/TrueCommand/Introduction/Support.md, content/TrueCommand/_index.md
edited line 24 to read: TrueCommand docker container can be deployed as a VM since vhdk and vmdk are no longer supported in version 2.0.
=> DOCS-2236: Edit Main Page

.github/workflows/build-external-contrib.yml, .github/workflows/build-internal-contrib.yml, config.toml, layouts/_default/baseof.html, static/includes/ServicesSNMPFields.md.part
Use a placeholder TN open storage logo for search results thumbnails.
Defined as a site parameter for easy adjustment or removal.
=> DOCS-2194: Define a feature image param for each page

content/SCALE/GettingStarted/InstallingSCALE.md, content/SCALE/Introduction/SCALEHardwareGuide.md, content/SCALE/Shares/NFS.md, content/SCALE/Storage/PermissionsSCALE.md, content/SCALE/SystemSettings/AdvancedSettings.md
Fixing a few more BSD refs:
- Removing a VMWare/FreeBSD specific bug
- Changing info on how to set up a VM to match Linux base
- Changing manpages to Debian 'Testing' URLs as Debian 11/Bulleseye is not released yet
=> Remove other BSD refs in the TrueNAS SCALE docs

content/ReleaseNotes/CORE/12.0U5.md
Add aliases so that the previous incorrect path still allows people to go to the new, correct location.
=> Update and rename 12.0-U5.md to 12.0U5.md

content/CORE/Sharing/WebDAV/WebDAVShare.md
The example was `https://10.2.1.1:8081/mnt/corepool1/newdataset` - this will show the 404 Not Found error page
When modified `https://10.2.1.1:8081/newdataset' this works ok.
=> Fixed Example

static/custom.css
- Also add a little padding to the bottom of the sticky header and round the edges of the box to be a little friendlier for dark mode.
- Add a small amount of padding to the bottom of base header.
=> DOCS-2603: Fix sticky header placement

content/References/Performance/InterconnectDataRates.md
Changes 1024^2 Column to MiB/s - Nick Wolff checked work and said it looks good.
=> DOCS-2198: Change 2nd Column to MiB/s

content/ReleaseNotes/CORE/12.0U6.1.md
Rebalance whitespace in Known Issues table.
Add new note about samba issues with custom widelink and vfs_full_audit parameters.
=> Add Known Issue about samba auxiliary parameters to 12.0-U6.1 Release Notes

content/Archive.md
The Archive has two entries for previous versions that are still HTML:
https://www.ixsystems.com/documentation/freenas/9.3/freenas.html 
https://www.ixsystems.com/documentation/freenas/9.10/freenas.html 
These html docs need to be downloaded, coverted to PDF, and reuploaded to the Docs Hub and Archive links updated.
=> DOCS-2551 Convert Legacy HTML docs to PDF and reupload to Docs Hub

layouts/partials/head.html
Local build test allows a single <span> inject to call the MDI icon and add as an SVG to inline content.
=> DOCS-2932: Add iconify for MDI icon support

content/ReleaseNotes/ReleaseSchedule.md
Fill in checkpoints for every software release scheduled during Q1 and Q2 2022
Add larger warning about tentative dates and separate internal iXsystems effort.
=> DOCS-3167: Update release schedule

content/SCALE/_index.md
I believe with the SCALE 22.02 release is this warning obsolete.
=> Removed warning about early development

content/Hardware/ExpansionShelves/ES60BSG.md
Update the Docs Hub publish location to ensure the ES60 BSG is viewable and downloadable: https://www.truenas.com/docs/hardware/expansionshelves/es60bsg/
=> DOCS-3345 ES60 BSG PDF is unavailable

content/SCALE/GettingStarted/MigratingFromCORE.md, content/TrueNASUpgrades/_index.md
=> DOCS-3527: Core HA to SCALE HA Upgrades are not possible

content/SCALE/GettingStarted/FirstTimeLogin.md
Added blurb about the ability to close an Error or Alert Dialog box and recover it in the Task Manager.
=> DOCS-3223: Error and Alert ABORT Buttons Changed to Close

content/CORE/CORETutorials/Services/ConfiguringFTP.md, content/CORE/CORETutorials/Services/ConfiguringSFTP.md, content/CORE/CORETutorials/Services/ConfiguringTFTP.md, content/CORE/CORETutorials/Services/FTPTFTP.md, content/CORE/UIReference/Services/FTPScreen.md, content/CORE/UIReference/Services/TFTPScreen.md, layouts/shortcodes/taglist.html
This adds a taglist shortcode that can be used to link similar content articles to each other and help guide readers. Thank you to https://kollitsch.dev/blog/2022/hugo-shortcode-taglist/ for the guide!
=> DOCS-3813: Add related content shortcode

content/CORE/COREReleaseNotes.md
Change the example on line 784 from
root@examplemini[~]# python3 replace_disk.py disk gptid/c7acbd9e-ca3d-11ec-8ec6-d05099c356a4 ada3
to
root@examplemini[~]# python3 replace_disk.py tank gptid/c7acbd9e-ca3d-11ec-8ec6-d05099c356a4 ada3
=> Example syntax correction on 13.0 Release Notes

static/includes/Reference/SystemAdvancedFields.md.part
Fix for Kernel options having been duplicated from the GUI section.
---
=> SystemAdvancedFields.md.part: fix Kernel options

content/CORE/UIReference/Sharing/SMB/SMBShareScreen.md
Remove text that was causing text for Access Based Share Enumeration to be hidden.
---
=> SMBShareScreen.md: fix checkbox description

content/SCALE/GettingStarted/Migrate/MigratingFromCORE.md, content/SCALE/GettingStarted/Migrate/_index.md
Minor typo fix in 2 articles re: migrating from CORE to SCALE.
=> Docs 4039 typo in the migrating instructions

content/CORE/COREPreviousVersion.md, content/CORE/COREReleaseNotes.md, content/_index.md, data/menu/more.yml
- Updated the site home page with links to the archived docs for the previous major CORE and TrueCommand versions. No change for SCALE yet - Angelfish is the first major version.
- Added menu item inside CORE area that redirects to the 12.0 Docs PDF. Added some text and direct link to the PDF if the redirect doesn't work for some reason.
- Fixed the more menu .yml file to use the pathway ref to the archive instead of direct linking. This should help when local build testing archive changes.
=> DOCS-4080: Add additional pointers to previous version docs

layouts/_default/baseof.html, static/custom.css
This adds an inobtrusive **back to top** button when scrolling past 10% of the page.
Thanks to https://css-tricks.com/how-to-make-an-unobtrusive-scroll-to-top-button/ for the assistance!
=> DOCS-4123: Add scroll to top button on pages

content/CORE/CORETutorials/Storage/Pools/ManagingPools.md
This ticket is a subtask of Docs 3753. This fixes the typo to read: "...pool is not in heavy use."
=> DOCS-4130 update typo in ManagingPools.md

content/CORE/CoreSecurityReports/SMB1Advisory.md
Found a tiny typo while reading TrueNAS CORE security doc:
'Do not use SBM1' -> 'Do not use SMB1'
=> Fix typo in SMB1Advisory.md

.github/workflows/build-external-contrib.yml, .github/workflows/build-internal-contrib.yml
This is no longer working for our use cases and needs to be removed. I'm setting up Netlify as a manual interim solution.
=> Remove surge.sh step

layouts/partials/head.html
adjusted to use a static Docs Hub string as part of the title
=> DOCS-4129: Update head title builder

content/SCALE/SCALEUIReference/Credentials/LocalUsersScreensSCALE.md
Somehow the article uploaded as the LocalUserScreensSCALE.md article ended up with duplicate content to what was in the tutorial articles.
This PR fixes that mistake and uploads the UI ref content.
=> Docs 4392 Fix the Local Users UI Ref Article in Angelfish

content/SCALE/SCALEUIReference/Credentials/LocalUsersScreensSCALE.md
This commit removes the conflict notice in the article that was deleted but stayed in the article when it built for the new release.
=> Docs-4399 Fixed Local Users Screens Article

content/SCALE/SCALETutorials/Credentials/ManageLocalUsersSCALE.md, content/SCALE/SCALEUIReference/Credentials/LocalUsersScreensSCALE.md
This commit updates the LocalUserScreensSCALE.md article Authentication settings, and the ManageLocaluser.md article to add including the root group when creating an Admin user.
=> Docs-4397 Update User Articles

config.toml
The link now takes you directly to the edit form for the article, no need to click the pencil icon before beginning to edit. local build test worked correctly
=> Adjust Path for Edit this Page link

content/CORE/CORETutorials/Storage/Pools/StorageEncryption.md, content/SCALE/SCALETutorials/Storage/Datasets/EncryptionSCALE.md
Added 512 as the length limit.
=> DOCS-4406: Add Passphrase length limit

content/SCALE/GettingStarted/Install/ConsoleSetupMenuScale.md, content/SCALE/SCALETutorials/Network/ConfigureStaticRoutes.md, content/SCALE/SCALETutorials/Network/Interfaces/ManagingInterfaces.md, content/SCALE/SCALETutorials/Network/Interfaces/SettingUpStaticIPs.md, content/_includes/AliasOrStaticIP.md
This commit adds a snippet to address the difference between an alias and static IP and when and where to configure them. It adds this snippet to the GettingStarted/Installation/ConsoleSetupMenu.md article and the Network tutorials for interfaces and static IPs.
=> Docs-4122 Update Articles with Alias or Static IP Address Content

content/SCALE/GettingStarted/Install/InstallingSCALE.md
Fix typo.
Remove negative statement about OSes to not try for a VM. The positive instruction for OS types to use is enough.
=> Internal suggestion to improve Generic VM install text

content/SCALE/SCALE22.12.md
Update with latest 22.12.1 dates
Add anticipated 22.12.2 dates
Clean up NFS config warning to reflect wheel group is available in SCALE now to help users work around the issue.
=> Update upcoming Bluefin release dates and known issue cleanup.

content/Hardware/LegacyHardware/MiniSeries/TrueNAS Minis (3rd Gen)/MiniBSG(Legacy).md
This was my error - this doc is supposed to show the initial 3rd gen Mini family, including some of the Mini E / E+ products that are end of life. I've uploaded the archival copy of this doc to the web server and adjusted the link to point to it.
=> Error fix - legacy 3rd gen mini doc

content/References/Performance/InterconnectDataRates.md
Gb/s columns were labeled as "Bytes" and the first data row in the last table was bolded
=> Minor corrections to interconnect data rates page

content/SCALE/GettingStarted/Migrate/MigratingFromCORE.md
This commit updates the MigratingFromCORE.md article content by adding a section on preparing for migration, adding Enterprise content, adds content on when the CORE update function works to use it to migrate to SCALE. And it makes other style/organizational improvements. When failover works properly, this article will include some information on migrating a non-Enterprise (HA) system from CORE to SCALE. This content is not included yet.
=> PD-116 Update Core to Scale Migration Article

content/_includes/TCReleaseNotes/2.0-Beta.md, content/_includes/TCReleaseNotes/2.0.md
- Add aliases for previous URLs of TC 2.0-BETA and TC 2.0, 2.01, 2.02 release notes.
- This is to fix the links to this content from the https://portal.ixsystems.com/ website.
=> PD-170: TC 2.0 relnotes alias update

content/_includes/TNHardwareGuide.md
This commit changes the TNHardwareGuide.md snippet used in both CORE and SCALE getting started section by: 
Changing the heading for Virtualized TrueNAS CORE to just Virtualized TrueNAS to make it generic for CORE and SCALE. 
Moves content around and adds a warning admonition box to emphasize deploying in a virtual environment is not a recommended or supported configuration for anything other than ad hoc proof-of-concept.
=> PD-192 Update TNHardwareGuide Snippet

content/SCALE/SCALETutorials/Shares/AFP/_index.md
This is an incidental catch. This index file is normally not selectable, but search links or URLs pointed right to it shows an empty article. I'm proposing a simple change to add some introductory text and the children shortcode to point to the related article.
=> Add introductory text to SCALE tutorials AFP index file.

content/SCALE/SCALEUIReference/Storage/Datasets/EncryptionUISCALE.md
Leaving this in place in the related tutorial, but not needed in pure reference material.
=> Remove keyfile warning from ref content

content/SCALE/GettingStarted/Install/InstallEnterpriseHASCALE.md, content/_includes/HAControllerInstallBestPracticeSCALE.md
This commit updates the HA install procedure to include the best practices for installing the controllers so controller 1 comes up as the primary controller. It adds a new snippet for a best practices statement used in a few places inside this article.
This commit merges into the SCALE 22.12.2_docs branch
=> PD-235 Update Install HA Article

content/References/BitsOrBytes.md, content/References/ControllerOrNode.md
This commit creates a simple reference article defining controller and node and explaining how TrueNAS uses the terms.
This PR can merge into Master as it does not contain 22.12.2 only content.
=> PD-176 Create Controller or Node Reference Article

content/TrueCommand/TCGettingStarted/InterfaceOverview.md
This commit updates the InterfaceOverview.md article, converting the bullet lists of icons and links to a table, and introduces the expand sections.
This pull request only addresses fixes in this article. A new ticket and PR to be submitted when we resolve the issue with the r30 not displaying system information and image correctly.
=> PD-222 Update TC Interface Overview Article

content/CORE/CORETutorials/Storage/Disks/DiskReplace.md, content/SCALE/SCALETutorials/Storage/Pools/Disks/ReplacingDisks.md, content/_includes/RestoreHotSpare.md
This commit creates a snippet to use in both CORE and SCALE Replacing a Disk articles that covers restoring a hot spare to operation.
=> PD-182 Add Restoring a Hot Spare to Replacing Disk Articles

content/SCALE/GettingStarted/Migrate/MigratingFromCORE.md, content/_includes/MigrateCOREtoSCALEWarning.md, words-to-ignore.txt
This commit adds instructions to upgrade CORE to the latest publicly-available release before attempting to migrate CORE to SCALE. This is added to the MigrateCOREToSCALEWarning.md snippet file, and added in an admonition box in the UI migration section of the MigratingFromCORE.md article.
=> PD-372 Update CORE to SCALE Migrate Content

content/SCALE/SCALETutorials/SystemSettings/Services/DDNSServiceSCALE.md, content/SCALE/SCALETutorials/SystemSettings/Services/S3ServiceSCALE.md, content/SCALE/SCALETutorials/SystemSettings/Services/TFTPServiceSCALE.md, content/SCALE/SCALETutorials/SystemSettings/Services/WebDAVServiceSCALE.md, content/SCALE/SCALEUIReference/SystemSettings/Services/DDNSServiceScreenSCALE.md, content/SCALE/SCALEUIReference/SystemSettings/Services/S3ServiceScreen.md, content/SCALE/SCALEUIReference/SystemSettings/Services/TFTPServiceScreen.md, content/SCALE/SCALEUIReference/SystemSettings/Services/WebDAVServiceScreen.md, content/_includes/SCALEServiceDeprecationNotice.md
This PR creates a snippet for the deprecated service notice and adds to to the service tutorial and UI reference articles for the services deprecated in 22.12.3.
=> PD-382 add deprecation notice to service articles

content/CORE/_index.md
The filename for the CORE logo in _index.md did not match the file in static\images and was displaying as broken. This PR corrects it.
=> CORE\_index.md logo filename correction

config.toml, layouts/partials/page-header.html
Switch parameter to allow edit page links at bottom to continue to work as well.
=> Fix up "Edit Page" links at top of pages.

content/Solutions/Optimizations/Security.md
This adds a general best practices section in front of the specific service hardening content and reweights headers for better navigation.
=> PD-487: Update TrueNAS Security Best Practices

content/SCALE/SCALETutorials/Storage/Datasets/EncryptionSCALE.md, content/SCALE/SCALEUIReference/Storage/Datasets/DatasetsScreensScale.md, content/SCALE/SCALEUIReference/Storage/Datasets/EncryptionUISCALE.md, content/Solutions/Optimizations/Security.md, content/_includes/EncryptionWarning.md, content/_includes/ReplicatedEncryptedUnlock.md
This PR updates the encryption content by removing information stating users can create an unencrypted dataset within an encrypted pool or dataset.
It fixes style issues, replaces the old image link with trueimage shortcodes. The icon image links embedded in the table of icons remain so they render correctly.
This PR merges into 22.12.3_docs branch.
=> PD-489 update dataset encryption content

content/SCALE/SCALECLIReference/Storage/CLIDataset.md, content/SCALE/SCALECLIReference/Storage/CLIDisk.md, content/SCALE/SCALECLIReference/Storage/CLIEnclosure.md, content/SCALE/SCALECLIReference/Storage/CLIFilesystem-Storage.md, content/SCALE/SCALECLIReference/Storage/CLIPool.md, content/SCALE/SCALECLIReference/Storage/CLIResilver.md, content/SCALE/SCALECLIReference/Storage/CLIScrub.md, content/SCALE/SCALECLIReference/Storage/CLISnapshot.md, content/SCALE/SCALECLIReference/Storage/CLIVmware.md, content/SCALE/SCALECLIReference/Storage/_index.md, content/SCALE/SCALEUIReference/SystemSettings/EnclosureScreensSCALE.md, content/_includes/SCALECLIIntroduction.md
This PR updates the SCALECLIReference/Storage/_index.md file content, moves the pool and dataset query content to the child namespace articles. It creates work-in-progress articles for the storage child namespaces.
=> PD-252 Create Storage CLI Namespace Articles

content/SCALE/SCALECLIReference/Sharing/CLINFS.md, content/SCALE/SCALECLIReference/Sharing/CLISMB.md, content/SCALE/SCALECLIReference/Sharing/CLIWebdav.md, content/SCALE/SCALECLIReference/Sharing/CLIiSCSI.md, content/SCALE/SCALECLIReference/Sharing/_index.md
This PR updates the SCALECLIReferences/Sharing/_index.md content with child namespace article information and makes it visible.
It creates the placeholder child namespace articles.
=> Pd 251 create cli sharing namespace articles

content/SCALE/SCALECLIReference/App/CLICatalog.md, content/SCALE/SCALECLIReference/App/CLIChartRelease.md, content/SCALE/SCALECLIReference/App/CLIContainer.md, content/SCALE/SCALECLIReference/App/CLIDocker.md, content/SCALE/SCALECLIReference/App/CLIKubernetes.md, content/SCALE/SCALECLIReference/App/_index.md, content/SCALE/SCALETutorials/Apps/UsingCatalogs.md
This PR updates the SCALECLIReference/App/_index.md article and makes it visible. Adds the placeholder child namespace articles.
=> PD-246 Create CLI App Namespace Articles

content/SCALE/SCALEUIReference/DataProtection/CloudSyncTasksScreensSCALE.md
I'm acknowledging that my changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.
=> Fix references to TNS Cloud Sync tutorial

content/SCALE/SCALECLIReference/Sharing/_index.md
This PR changes the child namespace section heading to Sharing Child Namespace Articles
=> PD-251 Update Sharing _index.md Heading

content/SCALE/SCALECLIReference/Storage/_index.md
This PR changes the child namespace section heading to Storage Child Namespace Articles.
=> PD-252 Change Storage Index file Heading

static/custom.css
This keeps the feedback button from covering any content.
=> PD-554: extra padding for feedback button

content/CORE/CORETutorials/Storage/Pools/SLOGOverprovision.md
Updating Link for Seagate SSD Over-Provisioning Benefits article as currently link is broken. This is the same change that was made to the corresponding SCALE document.
=> [CORE] Update SLOGOverprovision.md to Fix Broken Link

content/GettingStarted/Configure/FirstTimeLogin.md, content/GettingStarted/Configure/SetUpSharing.md, content/GettingStarted/Configure/UIConfigurationSCALE.md, content/GettingStarted/SCALEReleaseNotes.md, content/SCALECLIReference/Account/CLIgroup.md, content/SCALECLIReference/Account/CLIuser.md, content/SCALECLIReference/_index.md, content/SCALETutorials/Apps/CommunityApps/AddStorjNode.md, content/SCALETutorials/Apps/CommunityApps/Chia.md, content/SCALETutorials/Apps/CommunityApps/Collabora.md, content/SCALETutorials/Apps/CommunityApps/InstallNetdataApp.md, content/SCALETutorials/Apps/CommunityApps/InstallNextCloudMedia.md, content/SCALETutorials/Apps/CommunityApps/InstallPiHoleApp.md, content/SCALETutorials/Apps/CommunityApps/InstallWGEasyApp.md, content/SCALETutorials/Apps/CommunityApps/MinIOApp/MinIOClustering.md, content/SCALETutorials/Apps/CommunityApps/MinIOApp/MinioManualUpdate.md, content/SCALETutorials/Apps/CommunityApps/MinIOApp/_index.md, content/SCALETutorials/Apps/CommunityApps/Rsyncd.md, content/SCALETutorials/Apps/CommunityApps/TFTP-HPAApp.md, content/SCALETutorials/Apps/CommunityApps/WebDAV.md, content/SCALETutorials/Apps/CommunityApps/_index.md, content/SCALETutorials/Apps/CommunityApps/ddns-updater.md, content/SCALETutorials/SystemSettings/Advanced/_index.md, content/SCALEUIReference/Shares/iSCSISharesScreens.md, content/SCALEUIReference/Storage/_index.md, content/SCALEUIReference/SystemSettings/AlertsSettingsServiceScreen.md, content/SCALEUIReference/SystemSettings/Services/iSCSIServicesScreen.md, content/SCALEUIReference/TopToolbar/Alerts/AlertSettingsScreen.md
adds `/_includes/` to all `include file` shortcodes that did not have the path defined
=> Fix issue with _includes paths

content/References/ConceptsAndTerms.md
Updates dead link found for "ZIL" on this page: https://www.truenas.com/docs/references/conceptsandterms/
I checked all other links to `freenas.org` link references and they all properly redirect to `truenas.com`
=> Update outdated link

content/CORETutorials/Sharing/NFSShare.md, content/CORETutorials/Sharing/SMB/SMBShare.md, content/CORETutorials/Sharing/WebDAVShare.md, content/_includes/ShareDatasetsNotPools.md, content/_includes/SharingPrereqs.md
Ports admonitions from Cobia branch back to CORE. Makes some other incidental changes, mostly adding returns, proofreading, etc. 
=> Pd 646 create snippet for shares do not use a pool for share 13.0

content/SCALECLIReference/System/CLIInitShutdownScript.md, content/SCALETutorials/SystemSettings/Advanced/ManageInitShutdownSCALE.md, content/_includes/InitShutdownWarning.md
Documents the CLI `system init_shutdown_script` namespace. Also creates a init/shutdown specific warning snippet and adds that to the related Tutorial with a few other tweaks to that article.
=> Pd 455 cli guide document system init shutdown script namespace

content/GettingStarted/COREReleaseNotes.md, content/GettingStarted/Deprecations.md
This article is intended to track any feature deprecations in CORE 13.0.
- It should be ported to `master branch for use in future major version docs
- Some initial text about the S3 service deprecation in 13.0 is included.
- Some initial copy about SAS multipath deprecation in 13.0 is included.
- Incidental: did a quick update to 13.0 release notes to include the deprecations (with cross-references) and remove a few notices that were closed as not to be fixed.
=> (13.0) PD-696: Add Deprecations.md and some initial population

content/API/_index.md, content/CORETutorials/_index.md, content/CoreSecurityReports/_index.md, content/_index.md
Ahrefs report hit a couple cross-references in the API and home pages that were not pointed the right direction. The API article shortcode is removed (obsolete) and the home page reference to the hardware area updated to be a static link (cross-version compatibility)
=> PD-704: 13.0 branch cross references fixes

content/SCALE/SCALEUIReference/Shares/iSCSISharesScreens.md
This PR fixes missing references to the Wizard and Configure buttons on the iSCSI widget. It makes a few other related changes adding the name of screens opened. Makes the suggested changes in the settings tables.
=> PD-684 Updates and Corrections

content/SCALE/SCALEUIReference/SystemSettings/Services/NFSServiceScreen.md
This commit removes the hint box referencing the service not starting if the share is encrypted or locked.
=> PD-662 Remove Hint Box

content/SCALE/SCALECLIReference/Network/CLIStaticRoute.md, content/SCALE/SCALETutorials/Network/ConfigureStaticRoutes.md, content/SCALE/SCALEUIReference/Network/StaticRouteScreens.md
This PR updates the CLIStaticRoute.md article with standard CLI text and the static_route command content.
It updates the UI ref and tutorial articles on static routes with a new tag "scalestaticroute" and taglist shortcode.
=> Pd 346 update cli static route.md article content

content/_includes/COREMigratesList.md
Add migration note about account naming difference between CORE and SCALE.
=> PD-729 (Backport to 23.10)

content/GettingStarted/Migrate/MigratePrep.md, content/GettingStarted/Migrate/MigratePrepEnterprise.md, content/_includes/COREMigratesList.md, content/_includes/MigrateCOREtoSCALEWarning.md, content/_includes/MigrateCoreServicesToCobia.md, content/_includes/MigrateCoreServicesToCobiaEnterprise.md, words-to-ignore.txt
This PR ports change to `COREMigratesList.md` to 22.12. Also backports two other snippets on deprecated services. 
=> Pd 729 backport to 22.12

content/GettingStarted/SCALEReleaseNotes.md
In the release notes the mentioned Samba Version is 4.17.0, but on atlassian it is 4.17.10
=> Update SCALEReleaseNotes.md 22.12.4

content/GettingStarted/SCALEReleaseNotes.md
Fix a broken link on release note 22.12.4: (NAS-123123)
=> Update SCALEReleaseNotes.md - Fix broken Link on release note 22.12.4

content/SCALE/SCALECLIReference/System/CLIKeychainCredential.md
This PR adds the standard CLI article content and the keychain_credential command information to the CLIKeychainCredential.md article.
Many commands are still WIP and need updates when we are able to get the array object syntax correct to test these commands or engineering makes changes to make it easier to use these commands or removes them completely.
=> Pd 456 update cli keychain credential.md article

content/GettingStarted/SCALEReleaseNotes.md
Simplify the release schedule table and add a new Upgrade Note that warns users with an encrypted pool used for app storage to remain on bluefin until a later cobia maintenance release.
=> Update release schedule and add upgrade warning (23.10)

content/GettingStarted/23.10Upgrades.md, content/GettingStarted/Migrate/MigratingFromCORE.md, content/GettingStarted/SCALEReleaseNotes.md, content/_includes/23.10UpgradeMethods.md, words-to-ignore.txt
- Write a single source text snippet that clarifies the only recommended upgrade methods for Cobia releases and include in the 23.10 release notes and upgrade methods articles.
- Add an additional admonition against using the installer upgrade option to the 23.10 relnotes article.
- Review the other installation docs and purge any inclusion of the .iso upgrade option (not currently supported in Cobia).
=> 23.10 (Cobia): Clarify upgrade options

content/Hardware/ExpansionShelves.md, content/Hardware/MSeries.md, content/Hardware/Mini.md, content/Hardware/RSeries.md, content/Hardware/XSeries.md
Internal report that some X-Series docs cards links were in error.
Reviewed links for each of the reworked sections and fixed a number of issues.
I've commented out the Network Port IDs for each family and the M-Series NVDIMM replace card until we can finish investigating and do a clean resolution.
=> Hardware links fixes

layouts/_default/sitemap.xml
Properly begin with the base website url and subdirectory. Adjust the logic to remove some automation-only paths from the sitemap.
Example sitemap from building this branch locally:
=> MM2-3820: Update sitemap generation

content/SCALE/GettingStarted/SCALEReleaseNotes.md
This alias needs to be removed when scale 24.04 docs are branched.
=> Add temporary alias for dragonfish nightly release notes

content/_includes/CORETopMenu.md
Converted default commonmark syntax within the includes snippet to HTML to fix the style issue.
=> Fix issue with includes render inside expand for CORETopMenu.md

content/GettingStarted/COREReleaseNotes.md
This is a small PR for the 13.0-U6.1 hotpatch. It has a single draft note regarding the OpenZFS version update. Additional notes to be added as needed before the U6.1 release.
=> PD-890: 13.0-U6.1 release note

content/SCALE/SCALETutorials/Datasets/ManageSnapshotsSCALE.md
Had a DM noting there was what appeared to be duplicate text on this page.
Reviewed the article section and reworked to keep the alternate data restore method within the admonition and remove the duplicate text.
=> SCALE manage snapshot tutorial: update the snapshot revert text

content/Solutions/Integrations/SMBClustering.md, content/TrueCommand/TCGettingStarted/TCReleaseNotes.md, content/TrueCommand/UserGuide/Clusters.md, content/_includes/TC3.0ClusterCompatWarning.md, words-to-ignore.txt
Provide explanation of impact and clarify which versions of SCALE are compatible with which versions of TrueCommand clustering feature.
PR is in draft while I ask TC leadership for review.
=> PD-911: Add TC 3.0.0 clustering compatibility text and inject in 3 articles

content/GettingStarted/SCALEReleaseNotes.md
Simple notice is added with workaround and link to ticket that is being reworked with a more technical explanation of the issue.
Added one incidental change: elevated the service deprecation note to it's own subsection under the major features. This promotes it as a major change but distances it a little more from the general upgrade notes and paths in an attempt to prevent reader confusion.
=> (23.10) Add known issue for large custom app catalogs

content/CORE/GettingStarted/COREReleaseNotes.md, content/CORE/_index.md
Quick cleanup of the links on the CORE index page and add a Major Component Versions subsection to the development notes with FreeBSD and OpenZFS versions.
=> Nightly Dev home page polish and some early 13.1 development notes

content/CORE/CORETutorials/JailsPluginsVMs/Jails/AccessingJailsUsingSSH.md, content/CORE/CORETutorials/JailsPluginsVMs/Jails/InstallingJailSoftware.md, content/CORE/CORETutorials/JailsPluginsVMs/Jails/ManagingJails.md, content/CORE/CORETutorials/JailsPluginsVMs/Jails/SettingUpJailStorage.md, content/CORE/CORETutorials/JailsPluginsVMs/Jails/_index.md, content/CORE/CORETutorials/JailsPluginsVMs/Plugins/CreatingCustomPlugin.md, content/CORE/CORETutorials/JailsPluginsVMs/Plugins/PlexPlugin.md, content/CORE/CORETutorials/JailsPluginsVMs/Plugins/_index.md, content/CORE/CORETutorials/JailsPluginsVMs/UpdateJailsPlugins.md, content/CORE/GettingStarted/COREReleaseNotes.md, content/CORE/UIReference/JailsPluginsVMs/JailsScreens.md, content/CORE/UIReference/JailsPluginsVMs/PluginsScreens.md, content/CORE/UIReference/JailsPluginsVMs/VirtualMachines.md, content/CORE/UIReference/JailsPluginsVMs/_index.md
Add a few more items to the latest dev notes, in preparation for cutting over to 13.1-RC.1 release. Update the unsupported feature caution used in the beginning of the CORE plugins, jails, and vms content and apply to the parallel UI reference content.
=> CORE 13.1 - Release notes adds and virtualization support notice updates

layouts/shortcodes/cli.html
- shortcode now renders content as preformatted to avoid automatic rendering issue.
EXCEPT:
- Using asterisks as markdown formatting calls for bold and italics will still render the contained content. Example: {{< cli >}}**command** --name=test ***variable** italic*{{< /cli >}} renders the string with the asterisks properly translating to bold, italic, or even stacked bold and italic.
- The copy button continues to pull only the raw rendered text without formatting.
- Note that asterisks won't be usable as raw code text (i.e. part of a command) without proper escaping.
Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) …
=> Update the CLI shortcode

content/TrueCommand/TCGettingStarted/Install/InstallTCDocker.md
no tag exists in repository for 3.0.0, so command fails. tag is v3.0.0
https://github.com/orgs/iXsystems/packages/container/truecommand/versions?filters%5Bversion_type%5D=tagged
=> Documentation updated truecommand install for 3.0.0 to work.

layouts/partials/menu-nextprev.html, layouts/partials/page-header.html, layouts/partials/related-content.html, layouts/partials/toc-panel.html
Update this layout to better find the html header elements, including those injected by hugo shortcodes. Headers within HTML details elements are currently being ignored.
Apply some styling rules to the toc-panel entries to better denote h2, h3, or h4 headers.
Remove some h# elements applied to automatically generated elements to avoid overpopulating the toc-panel with less relevant entries.
Local build testing - no issues discovered so far and logic to remove the panel when the list has fewer than 2 entries is preserved.
=> ToC Panel polish

layouts/partials/page-header.html, static/custom.css
Break out the notice to it's own warning hint box and apply conditionally to the different software docs sections (CORE, SCALE, TrueCommand). Do some local build testing and css adjustments for polish.
=> Polish "where am I" notice at top of nightly version content pages

layouts/_default/baseof.html, layouts/partials/page-header.html, layouts/shortcodes/imagecard.html
1. Adjust toc-panel to ignore the TrueNASUpgrades section when generating.
2. Adjust imagecard shortcode (used in TrueNAS Systems) to not use h2 elements and cause extra toc panel entries.
3. Update the whereamI note to be consistent with gdoc hint warning styling and light/dark modes.
=> Some post-merges cleanups

content/_includes/SessionsSettingsWidget.md
Investigated and identified that the UI does not appear to show the number of days the raw seconds value translates to, only the remainder hours/minutes/seconds. Updated the text guidance to show the correct max value and will follow up as needed with Engineering regarding the days value not being displayed.
Note that this widget is renamed to Access in the latest nightly dev, so will need to review the master branch docs separately.
=> PD-974: Update sessions token lifetime max value (23.10)

content/SCALE/GettingStarted/SCALEReleaseNotes.md, static/api/scale_rest_api.html
Update static included websocket and rest API docs and validate gluster is no longer included.
Write early release notes about the gluster removal and upgrade guidance.
=> PD-987: 24.04-beta1 api docs

jenkins/update-dev1, jenkins/update-master, layouts/_default/baseof.html, layouts/_default/baseof.print.html, layouts/_default/taxonomy.html, layouts/_default/terms.html, layouts/partials/print/content.html, static/js/search.js
Refine the basic pagefind implementation:
- Ingest only content directories.
- Add ignore elements to printview and posts outputs
- Add ignore element on related content generator, to avoid keyword hits on article title links.
- Restyle the search results page with icons for CORE or SCALE content, or section names for the other nonspecific website sections.
Thank you to @DjP-iX for assisting with this effort!
=> Refine site search (master branch)

content/References/SMB.md, content/SCALE/GettingStarted/Configure/SetUpSharing.md, content/SCALE/SCALETutorials/Shares/SMB/AddSMBHomeShare.md, content/SCALE/SCALETutorials/Shares/SMB/_index.md, content/SCALE/SCALETutorials/SystemSettings/Services/SMBServiceSCALE.md, content/SCALE/SCALEUIReference/Shares/SMBSharesScreens.md, content/SCALE/SCALEUIReference/SystemSettings/Services/SMBServicesScreen.md, content/_includes/SMBShareMSDOSalert.md
- Condense the text
- Clarify TrueNAS (non) support for SMB client OS that are End of Life/End of Support
- Clarify that SMB1 protocol is not removed, but deprecated and subject to upstream Samba project changes. Link to original Samba release that makes this statement.
- Review locations where the single sourced text is called and refine placement.
Note that I'll backport these changes to Cobia & Bluefin branches once SME review is complete.
=> PD-1020: review and clarify SMB1 deprecation caution.

content/TrueNASUpgrades/_index.md, data/properties/core-releases.yaml, data/properties/scale-releases.yaml, data/properties/tc-releases.yaml
Add the latest anticipated dates for each software project.
Rename CORE next from 13.1 to 13.3.
Add a more obvious tentative card for TC next.
Do some small reworks to the Software Releases content to condense a bit.
=> Update SCALE, CORE, and TC anticipated release dates

static/js/search.js
Validated pagefind init is working as intended, but some front cleanup to do:
- fix path to .js file
- use 3.0 branch files for the search results icons.
=> PD-1013: More search cleanup

jenkins/update-3.0, static/js/search.js
With pagefind nonfunctional (so far), I'm resetting this to the basic lunr.js implementation used on the other branches. Local testing showed there was some unintended URLs pulled in, so adjusted to exclude those and keep the results url pointed to the branch docs on the Docs Hub.
=> PD-1013: Reset 3.0 branch to lunr.js search

content/SCALE/SCALEUIReference/SystemSettings/AdvancedSettingsScreen.md
=> PD-1038-further-clarify-allowed-ip-addresses-behavior

layouts/partials/head/custom.html
This is to fix the issue where our robots.txt file isn't properly applying as we're not a separate domain, but a subdirectory of truenas.com. Instead, we'll inject the noindex meta tag in <head> for the _includes, tags, volume, and book sections that we use for automatic relationships and single sourcing, but otherwise don't need Google crawling for content.
=> Update noindex entries for specific sections of master branch

content/GettingStarted/Configure/_index.md, content/GettingStarted/Install/_index.md, content/GettingStarted/Migrate/_index.md, content/GettingStarted/SCALEHardwareGuide.md
This PR rewords the front matter description in the Install, Configure, and Migrate _index.md files to fix the parallel construction of the bullet list in the Getting Started _index.md file. Standardize using Console Setup menu instead of Console setup menu or Console Setup Menu in paragraph text.
This makes changes to the 24.04 branch. Changes can be backported to Master.
=> Reword front matter descriptions

content/SCALE/SCALETutorials/SystemSettings/UpdateSCALE.md
This PR adds clarification and references to the release upgrade path information in the TruenasUpgrades.md article to reaffirm the process for users that try to skip a release.
=> Add Update Path Clarifications

content/UIReference/Sharing/SMBShareScreen.md
This PR updates the CORE 13.0 branch version of the SMB Share Screen article setting information on Export Recycle Bin, and fixes a typo.
=> PD-1040 Update SMB Share Screen Export Recycle Bin Setting Content

content/SCALETutorials/Shares/AddingNFSShares.md, content/SCALETutorials/SystemSettings/Services/NFSServiceSCALE.md, content/SCALEUIReference/Shares/NFSSharesScreens.md, content/SCALEUIReference/SystemSettings/Services/NFSServiceScreen.md, static/includes/NFSServiceUDPWarning.md
This PR backports the hint admonition and UDP protocol and NFS service snippet to 23.10
=> PD-1086 Backport UDP Protocl and NFS Snippet to 23.10

content/SCALETutorials/SystemSettings/General/ManageSysConfigSCALE.md
This PR backports the new section on backing up the system config file using TrueCommand to the 23.10 branch
=> PD-1081 Backport Config File Backup Content to 23.10

content/GettingStarted/Configure/SetUpSharing.md, content/SCALETutorials/Shares/AddingNFSShares.md, content/SCALETutorials/Shares/SMB/_index.md, content/SCALEUIReference/Shares/NFSSharesScreens.md, content/SCALEUIReference/Shares/SMBSharesScreens.md
This PR updates the shares tutorials and UI ref articles, and the SetUpSharing.md article with the FileExplorerFolderIcon.md snippet in the 24.04 branch.
These changes will be backported to Master in a separate PR
=> Add FileExplorerFolerIcon.md Snippet to Shares 24.04

content/SCALE/GettingStarted/Configure/SetUpSharing.md, content/SCALE/SCALETutorials/Shares/AddingNFSShares.md, content/SCALE/SCALETutorials/Shares/SMB/_index.md, content/SCALE/SCALEUIReference/Shares/NFSSharesScreens.md, content/SCALE/SCALEUIReference/Shares/SMBSharesScreens.md
This PR adds the FileExplorerFolderIcon.md snippet to the SMB and NFS shares UI ref, tutorials, and SetUpSharing.md article in the Master branch.
=> Update Shares Articles - Master

content/GettingStarted/Configure/SetUpSharing.md, content/SCALETutorials/Shares/SMB/AddSMBHomeShare.md, content/SCALETutorials/Shares/SMB/_index.md, static/includes/LocalSMBUser.md
Dragonfish now requires users to set up a user with Samba authentication or join AD before creating an SMB share.
Add an admonition box to the 24.04 Add SMB Home Share and SMB Share _index tutorials reminding users that they must have an SMB authentication user to access their shares.
=> Pd 1097 add note about creating smb user in 24.04

content/SCALE/SCALEUIReference/Storage/DevicesScreensSCALE.md, content/SCALE/SCALEUIReference/Storage/DisksScreen.md, content/SCALE/SCALEUIReference/Storage/PoolCreateWizardScreens.md, content/SCALE/SCALEUIReference/Storage/_index.md
This PR updates the Storage UI reference article content in the Master branch for these articles: /Storage/_index.md which covers the Storage Dashboard content DisksScreen.md
DevicesScreens.md
PoolCreateWizardScreens.md
This PR backports changes made in the 24.04 branch to Master
=> Update Storage UI Articles - Master

content/SCALETutorials/Credentials/ManageLocalUsersSCALE.md, content/SCALEUIReference/Credentials/LocalUsersScreensSCALE.md
Fix build errors from relref links.
=> Update manage local users scale.md   24.04

content/SCALE/GettingStarted/Migrate/MigratePrep.md, content/SCALE/SCALECLIReference/Storage/CLIScrub.md, content/SCALE/SCALECLIReference/System/CLIBoot.md, content/SCALE/SCALECLIReference/System/CLIBootenv.md, content/SCALE/SCALECLIReference/System/CLITrueCommand.md, content/SCALE/SCALETutorials/Apps/CommunityApps/Immich.md, content/SCALE/SCALETutorials/Apps/CommunityApps/InstallPiHoleApp.md, content/SCALE/SCALETutorials/Apps/CommunityApps/jellyfin.md, content/SCALE/SCALETutorials/Apps/UsingCustomApp.md, content/SCALE/SCALETutorials/ConfigReportsScale.md, content/SCALE/SCALETutorials/Shares/MixedModeShares.md, content/SCALE/SCALETutorials/Storage/Disks/SLOGOverprovisionSCALE.md, content/SCALE/SCALETutorials/SystemSettings/Advanced/ManageGPUSCALE.md, content/SCALE/SCALEUIReference/Apps/InstallCustomAppScreens.md, content/SCALE/SCALEUIReference/ReportingScreensSCALE.md, content/Solutions/Integrations/VMware/DeployTNinVMWare.md, content/Solutions/Optimizations/Security.md, content/TrueCommand/TCGettingStarted/UserAccounts.md, static/includes/BrowsingSnapshotCollections1.md, static/includes/ClusterSetup.md, static/includes/MinIODatasetRequirements.md
=> Pd 1093 building documenation locally from main branch fails

layouts/shortcodes/section-cards.html
The legacy TrueNAS CORE box was accidentally pointed to the release that won't be named, so I've adjusted to reflect the accurate upgrade path, which is 11.3 > 13.0 > 13.3 (eventual).
This is the Docs Hub landing page, so no version backports necessary.
=> Minor bugfix for historical core release on home page

content/GettingStarted/SCALEReleaseNotes.md, content/SCALETutorials/Credentials/ManageLocalUsersSCALE.md, content/SCALETutorials/Shares/SMB/AddSMBHomeShare.md, static/includes/24.04HomeDirectory.md, words-to-ignore.txt
=> Pd 1136 update 24 04 release notes guidance on user home directory change

layouts/shortcodes/enterprise-error.html
This is a standardized admonition box to be used when a Known Issue is TrueNAS Enterprise specific and not generic content that uses the light blue styling
Example:
{{< enterprise-error >}}
This is an example of an Enterprise specific issue where we need danger coloration and the TrueNAS Enterprise logo.
{{< /enterprise-error >}}
I'll backport this to 24.04 and 13.3 branch so we can use this moving forward.
=> Add Enterprise-specific issue box

content/GettingStarted/COREReleaseNotes.md, layouts/shortcodes/enterprise-error.html
Include a change to the 13.3-BETA.1 release notes to use the new shortcode for the Enterprise-specific issue.
=> Add enterprise-error shortcode (13.3 backport)

static/includes/TNHardwareGuide.md
This PR updates the TNHardwareGuilde.md snippet used in both the CORE and SCALE Hardware Guides with minor style fixes, and adds the Linux command equivalent to the FreeBSD `diskinfo` command, and adds clarifications about what applies to CORE v/s SCALE. i.e., plugins/jails being CORE and apps being SCALE. Removes extra end-of-line spaces and carriage returns. 
Changes can be backported to other release branches, 13.0, 13.3, 23.10, 24.04 or just 13.3 and 24.04.
=> PD-1124 Update Hardware Guide Snippet

data/properties/scale-releases.yaml, static/includes/SCALEUpgradePaths.md
Adjust the pathways to show 24.04.1.1
=> (24.04) Update SCALEUpgradePaths.md

content/SCALE/SCALETutorials/Apps/EnterpriseApps/MinIO/ConfigMinioEnterpriseMNMD.md, content/SCALE/SCALETutorials/Apps/EnterpriseApps/MinIO/ConfigMinioEnterpriseSNMD.md, content/SCALE/SCALETutorials/Apps/EnterpriseApps/MinIO/_index.md, content/SCALE/SCALETutorials/Apps/EnterpriseApps/Syncthing.md, content/SCALE/SCALETutorials/Apps/EnterpriseApps/_index.md, static/includes/SCALEEnterpriseApps.md
Reviewed the messaging on each article in the Enterprise Applications section.
Single sourced the specific messaging around Enterprise systems needing a specific license and recommendation to only install apps from the Enterprise apps train.
Applied single-sourced snippet across all SCALE Enterprise Apps articles
=> Single-source and clarify Enterprise app messaging (backporting needed)

static/includes/CreateDebugSCALE.md
Add SCALE CLI instruction for debug generation when UI access is not possible. Included a rudimentary sftp example.
=> Expand debug generate with SCALE CLI (midcli) instruction

content/SCALE/SCALETutorials/Apps/AppSecurity/CloudflareTunnel.md
Added note about clearing Host field when setting OVERWRITEHOST environment variable. Otherwise you will get this error "Environment Variable [OVERWRITEHOST] in [envList] tried to override the Environment Variable that is already defined in [Secret - nextcloud-creds]"
Please see this post where I asked how to fix the error I was getting: https://forums.truenas.com/t/unable-set-set-overwritehost-variable-for-nextcloud-cloudflare-reverse-proxy/5659
=> Update CloudflareTunnel.md with info to prevent error when setting OVERWRITEHOST

content/CORE/GettingStarted/COREReleaseNotes.md
Needs:
- make sure the nightlytestwarning snippet actually builds and deploys.
- Update the download link to point to the Storj / a different location for any post-13.3 builds. (see software releases page for examples)
- 
=> Rework CORErelease notes for generic nightlies

layouts/partials/docs-nav.html
=> Pd 1190 publish new version switcher

content/SCALETutorials/Credentials/Certificates/AddACMESCALE.md
I was struggling to find where to create the OVH credentials required for the ACME DNS authenticator. I found the site to create the credentials, but had trouble finding which routes to allowlist while creating the credential. So I dug into the code for the authenticator and found that TrueNAS is using the certbot-dns-ovh package. Its documentation contained the necessary information, so I though this PR would help others find the information.
Is this fine or would you like me to structure this differently or reproduce the information on this page instead of referencing the other docs?
> Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons …
=> Add hint on where to get credentials for ACME DNS authenticator via OVH

static/includes/FusionPools.md
Removed all instances that the ability to configure 'hot spares' for metadata/special VDEVs was found. Conversed with Grace on Tim's 06/11/124 comment, and she advised me that the docs already adequately discussed improved pool performance.
=> PD-1219-remove-references-to-special-vdev-hot-spare-support

content/SCALETutorials/Credentials/Certificates/SettingUpLetsEncryptCertificates.md
When setting up Route53 I wasn't sure which permissions were needed so it took some trial and error to get it to work. Looking at [the code](https://github.com/truenas/middleware/blob/master/src/middlewared/middlewared/plugins/acme_protocol_/authenticators/route53.py) I believe these are the three that are actually used.
It looks like the docs on `master` have been reorganized and no longer include this page; let me know if I should submit a PR for those in addition (or instead).
=> Add Route53 action names to SettingUpLetsEncryptCertificates.md

content/SCALE/SCALETutorials/SystemSettings/Services/FTPServiceSCALE.md
Added "Note, however, that you cannot create multiple accounts utilizing the same dataset as your home directory," to ensure that future readers understand that they can't create multiple accounts using the same dataset as their home directory. 
=> PD-1264-fix-ambiguity-with-ftp-documentation

content/_index.md, layouts/partials/docs-nav.html, layouts/partials/page-header.html
A few minor updates to the archived documentation to make it consistent with the archiving procedure that will be used starting with TC 2.3 and SCALE 23.10. 
=> Pd 1326 docs lifecycle standardize 22.12 archival changes

content/CORETutorials/Getting Support.md, content/CORETutorials/Network/Interfaces/SettingStaticIP.md, content/CORETutorials/Sharing/iSCSI/SettingUpFibreChannel.md, content/CORETutorials/Storage/Pools/StorageEncryption.md, content/CORETutorials/SystemConfiguration/ConfiguringFailover.md, content/CORETutorials/SystemConfiguration/ConfiguringKMIP.md, content/CORETutorials/UpdatingTrueNAS/UpdatingENTERPRISE.md, content/CORETutorials/UpdatingTrueNAS/_index.md, content/GettingStarted/COREReleaseNotes.md, content/UIReference/Sharing/iSCSI/FibreChannel.md, content/UIReference/System/Failover.md, content/UIReference/System/KMIP.md, content/UIReference/System/Support.md, content/UIReference/System/ViewEnclosure.md, data/properties/core-releases.yaml, layouts/partials/page-header.html, static/includes/13.3Overview.md, static/includes/COREUpgradePaths.md, static/includes/S3Deprecation.md, static/includes/iSCSIRef.md, words-to-ignore.txt
- Write the Community release messaging based from the official announcement.
- Disable Enterprise-specific content
- Write 13.3-RELEASE changelog
- Update release dates, upgrade path chart, and other content pulled into the release notes article
Note - Enterprise-specific content is moved to draft or otherwise commented out while 13.3 is a Community-only release. We can go back and restore this when ready to make a recommendation about Enterprise updates.
=> PD-1357: 13.3-RELEASE docs updates and changelog (13.3 branch)

content/SCALE/SCALETutorials/Apps/CommunityApps/Rsyncd.md
There was a small formating issue that made it hard to understand where the secrets file should be located because it was displaying as "/data//rsynd.secrets" instead of `/data/<module name>/rsynd.secrets`
=> Fix instructions for rsyncd authentication

content/SCALETutorials/SystemSettings/UpdateSCALE.md
Remove cli instruction for upgrading pools - this is covered in https://www.truenas.com/docs/scale/24.04/scaletutorials/storage/managepoolsscale/#upgrading-a-pool by the correct UI-centric method.
=> Update UpdateSCALE.md (24.04)

content/SCALE/GettingStarted/Migrate/MigratePrep.md
Used version numbers in a few spots (other than the main area) to further attempt to reinforce 13.0 to 24.04 is fine.
Check if a backport is needed for 24.04 branch
=> Upgrade migrate prep to clarify using either 13.0 or 13.3 (master)

content/SCALE/SCALEUIReference/DataProtection/PeriodicSnapshotTasksScreensSCALE.md
Added info to PeriodicSnapshotTasksScreensSCALE.md, including link to General Settings Screen. Did a quick scan of other data protection articles and didn't find any content relating to timezones that needs to be updated.
=> PD-1361-update-content-for-timezone-display

content/UserGuide/Alerts/AlertManage.md
Remove misleading statement about TLS and emphasize the lack of support for external relays on Cloud.
=> Clarify TrueCommand Cloud alert-settings

static/includes/iSCSIRef.md
Include a link to RFC-3722
(backport to 24.10)
=> Add IQN allowed character convention to iSCSI ref snippet

content/GettingStarted/Install/ConsoleSetupMenuScale.md
Updated singular instance of alias/static IP address referral as instructed by Tim.
=> PD-1405 / 24.10 / PD-1405-the-static-ip-settings-from-console-are-inaccurate

content/SCALE/GettingStarted/Install/ConsoleSetupMenuScale.md
Updated singular instance of alias/static IP address referral as instructed by Tim.
Original PR: https://github.com/truenas/documentation/pull/3049
Jira URL: https://ixsystems.atlassian.net/browse/PD-1405
=> PD-1405 / 25.04 / PD-1405-the-static-ip-settings-from-console-are-inaccurate (by linzi-ix)

content/SCALETutorials/Storage/ManagePoolsScale.md, content/SCALEUIReference/Storage/_index.md
There was an erroneous sentence about pool autoexpand when the disks are replaced with larger capacities. Discussed with Caleb and Mav and determined autoexpand is not present in this situation, so rewrote the procedure to add an extra step to manually expand the pool after disks are replaced.
Final version of the PR needs to be ported to `master` branch.
=> PD-1466: (NAS-130436) pool expand on disk replace procedure

data/properties/scale-releases.yaml
Old RC.1 date wasn't correct, needs to be updated to the latest estimated release day.
Backport to other affected branches as needed
=> Update scale-releases.yaml (master)

content/SCALETutorials/Datasets/EncryptionSCALE.md
Ran tests on my system to confirm these results.
=> PD-1378 / 24.10 / PD-1378-clarify-auto-unlock-behaviors-for-dataset-encryption-with-key-vs-password

content/CORETutorials/JailsPluginsVMs/VirtualMachines/SettingUpNPIV.md, content/CORETutorials/Sharing/iSCSI/SettingUpFibreChannel.md, static/includes/NPIV.md
This PR moves the content in the SettingUpNPIV.md article into a new snippet NPIV.md, and adds that snippet to both the SettingUpNPIVmd and SettingUpFibreChannel.md articles. It build out the content in the NPIV.md snippet to include more information on NPIV and a general overview procedure for setting up non-TrueNAS Fibre Channel systems for NPIV.
=> PD-1444 / 13.0 / PD-1444 Adding NPIV content to the Fibre Channel Article

content/CORETutorials/Services/ConfiguringOpenVPN.md, content/CORETutorials/Sharing/SMB/ManagingSMBShares.md, content/CORETutorials/Storage/Pools/Permissions.md, content/CORETutorials/Tasks/CreatingReplicationTasks/AdvancedReplication.md, content/GettingStarted/Applications.md, content/UIReference/System/Advanced.md, words-to-ignore.txt
This PR adds aliases for CORE articles in Master not present in the 13.0 branch.
=> PD-1500 / 13.0 / PD-1500 Add Aliases for Articles in Master not in 13.0

static/includes/RESTAPIDeprecationNotice.md
Feedback from Engineering:
- Note that REST API removal is targeted for later to avoid the impression that it is going away immediately.
- remove mentions of experimental golang client in favor of focusing on the recommended initial client.
- small cleanup of text
=> Update RESTAPIDeprecationNotice.md (24.10)

content/GettingStarted/Migrate/ComponentNaming.md, content/GettingStarted/Migrate/MigrateCOREHAtoSCALEHA.md, content/GettingStarted/Migrate/MigratePrep.md, content/GettingStarted/Migrate/MigratingFromCORE.md, content/GettingStarted/Migrate/SCALEZFSFlagRemoval.md, content/GettingStarted/Migrate/_index.md, static/includes/MigrateCOREtoSCALEWarning.md
This PR updates the migration articles in 24.04 with the approved migration path and aliases from articles in both Master and 24.10 branches. It updates the MigrateCOREtoSCALEWarning.md snippet with the migration path information.
=> PD-1430 / 24.04 / PD-1430 Update 24.04 Migration Articles with Approved Migration Path

content/SCALETutorials/Storage/ManagePoolsScale.md, static/includes/ExpandedVdevReporting.md, words-to-ignore.txt
git cherry-pick -x ed7458b9b28dd454df05255048456b2802a63099
git cherry-pick -x 1ae7cf411cac2803b4571b4e1106b9a62ebac322
git cherry-pick -x 696c900050604c32222392e61390b59ef8c16811
git cherry-pick -x 5b1fce32cfc59f7d31b985a170a973ce97372e02
git cherry-pick -x e062451633d0ae04d9a78d38edfdaabddb2063e8
git cherry-pick -x bddd2d899b29a0b664d25f55cf55ef9ed829f104
git cherry-pick -x a7535016dab95df6a465ee0c1996d861a18a11f0
git cherry-pick -x 59af38c9e0290ed2c215877a582dcd5d72ab815d
git cherry-pick -x 0486df0df252cc2ef7e8ce9cfbe328f787afad5c
Quick update to set expectations for post-expansion …
=> PD-1527 / 24.10 / Pd 1527 review raid z expansion (by DjP-iX)

content/GettingStarted/SCALEReleaseNotes.md, data/properties/scale-downloads.yaml, data/properties/scale-releases.yaml, static/includes/SCALEUpgradePaths.md
Add release notes and other schedule & upgrade path updates for 24.0.4.2.5 and 24.10.0.2 releases
=> 24.04.2.5 Release updates

content/SCALE/SCALEUIReference/SystemSettings/Services/SMBServicesScreen.md
This PR updates the File Mask (create mask) default to 0664 and the Directory Mask default to 0775.
Backport to 24.10
=> PD-1519 / 25.04 / PD-1519 Update File and Directory Mask Descriptions

content/UIReference/Services/SMBScreen.md
This PR corrects the File Mask (create mask) and Directory Mask default values to 0644 and 0755 respectively.
Backport to 13.3
=> PD-1519 / 13.0 / PD-1519 Update File and Directory Mask Descriptions

content/SCALEUIReference/SystemSettings/Services/SMBServicesScreen.md
This PR updates the File Mask (create mask) default to 0664 and the Directory Mask default to 0775.
Backport to 24.10
Original PR: https://github.com/truenas/documentation/pull/3202
Jira URL: https://ixsystems.atlassian.net/browse/PD-1519
=> PD-1519 / 24.10 / PD-1519 Update File and Directory Mask Descriptions (by micjohnson777)

content/UIReference/Services/SMBScreen.md
This PR corrects the File Mask (create mask) and Directory Mask default values to 0644 and 0755 respectively.
Backport to 13.3
Original PR: https://github.com/truenas/documentation/pull/3203
Jira URL: https://ixsystems.atlassian.net/browse/PD-1519
=> PD-1519 / 13.3 / PD-1519 Update File and Directory Mask Descriptions (by micjohnson777)

content/SCALE/GettingStarted/Configure/SetUpSharing.md, content/SCALE/SCALETutorials/Shares/AFPMigration.md, content/SCALE/SCALETutorials/Shares/AddingNFSShares.md, content/SCALE/SCALETutorials/Shares/MixedModeShares.md, content/SCALE/SCALETutorials/Shares/SMB/AddSMBHomeShare.md, content/SCALE/SCALETutorials/Shares/SMB/AddSMBShadowCopies.md, content/SCALE/SCALETutorials/Shares/SMB/ManageSMBShares.md, content/SCALE/SCALETutorials/Shares/SMB/SMBMultichannel.md, content/SCALE/SCALETutorials/Shares/SMB/SetUpBasicTimeMachineSMBShare.md, content/SCALE/SCALETutorials/Shares/SMB/_index.md, content/SCALE/SCALETutorials/Shares/_index.md, static/includes/RootLevelDatasetShareWarning.md
This PR creates a snippet with a warning admonition about not sharing the root/pool-level dataset, and adds it to all getting started/SMB/NFS sharing articles.
This can be backported to 24.10 and 24.04.
=> PD-1499 / 25.04 / Pd 1499 create do not create root dataset share warning

static/custom.css
Had a request come in to brighten the off-white text a little more in dark mode so there would be a starker contrast. Made the adjustment for the variable --body-font-color only in dark mode and automatic dark mode selectors. Please review and send feedback. If this change is good to merge, then we'll backport to the other active branches too.
=> Brighten dark mode text a little to improve readability (master branch; backports needed)

content/SCALETutorials/Apps/_index.md
The aliases were added as "/scale/scaletutorials/..." but the way the 23.10 branch is build and deployed means the aliases were covering incorrect locations (truenas.com/docs/scale/23.10/scale/scaletutorials/...) instead of the desired locations (truenas.com/docs/scale/23.10/scaletutorials/...)
=> Fix up aliases on 23.10 apps index

content/SCALEUIReference/Apps/_index.md, content/SCALEUIReference/SystemSettings/AdvancedSettingsScreen.md
=> Add cautions to debug kernel option. (24.10)

content/SCALEUIReference/Apps/_index.md
Reviewed the Apps/Installed Apps screen drop down menus in 24.10.2 and found some updates to do:
- Replaced one semi-obsolete image call and reworked terminology for the "Settings" option within the Configuration menu 
- Updated the Settings dropdown to match the current naming "Configuration"
-  Adjust internal headers and cross references accordingly.
=> Update 24.10 ui ref screen and notes for updated "settings" option in 24.10.2

content/GettingStarted/Configure/SetUpSharing.md, content/SCALETutorials/Credentials/ManageLocalGroups.md, content/SCALETutorials/Shares/SMB/_index.md, content/SCALEUIReference/Credentials/LocalGroupsScreens.md
After reviewing a 24.10 environment, I confirmed that the field was renamed to SMB User for User Credentials and SMB Group for Group Credentials. Did a bulk search for the obsolete term and updated each instance that I found.
Local build testing found no issues.
=> PD-1805 / 24.10 / Update credentials > Samba Authentication field name (24.10 branch)

content/SCALETutorials/SystemSettings/Advanced/ManageGlobal2FASCALE.md, static/includes/BasicReplicationProcess.md
Update to reflect where this option now exists in the Credentials > Users add/edit form.
Will review 25.04 and master branches too.
=> PD-1792 / 24.10 / find and fix outdated references to password login toggles in the SSH Service screen (24.10)

static/includes/iSCSIAddEditExtentSettings.md
Enable TCP -> Enable TPC
Additionally, the description of the Enable TPC feature links to the Windows "xcopy" command. 
AFAIK, this feature is related to SCSI XCOPY, not the Windows XCOPY command.
https://www.t10.org/ftp/t10/document.99/99-143r1.pdf
=> fix "Enable TPC" typo

static/includes/IncusExperimental.md, static/includes/InstanceWarning.md
Reorganizes the warning about UI-only Incus support so it appears in the release notes
=> Add cli warning

layouts/partials/docs-nav.html, static/custom.css
* PD-1825: add small groupings to TrueNAS version selector (backports needed)
* additional styling
* adjust line height and add archive div
---------
=> Add small groupings to TrueNAS version selector (13.3 cleanup)

layouts/partials/docs-nav.html, static/custom.css
…ckports n… (#3610)
* PD-1825: add small groupings to TrueNAS version selector (backports needed)
* additional styling
* adjust line height and add archive div
---------
=> PD-1825 / 3.0 / add small groupings to TrueNAS version selector (final polish)

layouts/partials/docs-nav.html, static/custom.css
…ckports n… (#3610)
* PD-1825: add small groupings to TrueNAS version selector (backports needed)
* additional styling
* adjust line height and add archive div
---------
=> PD-1825 / 24.04 / add small groupings to TrueNAS version selector (final polish)

content/GettingStarted/Migrate/MigratePrep.md
This commit and PR adds only the iSCSI cautions and information to the 25.04 branch article, and the strong encouragement that Enterprise customers contact support for assistance.
This is the backport of the 25.10 content with what applies in 25.04
=> PD-1802 / 25.04 / PD-1802 Add iSCSI info to MigratePrep.md

static/includes/NPIV.md
The command in line 23 does not set up the virtual port. Removing the word "input" from the command fixes this command. Change tested and verified.
Backport this change to 13.3
=> PD-1853 / 13.0 / PD-1853 Fix Command in line 23 of NPIV.md Snippet

content/CORETutorials/Tasks/CreatingRsyncTasks.md
This PR updates the content in the current rsync task article in general, and updates the SSH mode instructions to what is tested and verified to work.
This content can backport to 13.3
=> PD-1266 / 13.0 / PD-1266 Update Rsync Task Content

content/GettingStarted/SCALEReleaseNotes.md
Ticket investigation found that the issue was caused by developer-mode level modifications being done, not an issue with the default codebase.
=> Remove known issue escalation about importing instance pool

content/CORETutorials/Tasks/CreatingRsyncTasks.md
git cherry-pick -x f1ee8051d3404d71287e83db6d007f2fc3ccb15a
git cherry-pick -x 1d64d1ccecd87fa751aabf49e3c07da9417a1d9e
git cherry-pick -x 48e662a0c9b644f1164b9adf9b8f19b4aa7af9ee
git cherry-pick -x ddf8b27008a655bafc5287a78972a64dff04b26d
git cherry-pick -x f2fbe5b068422676fd3bb8ba2b24215d729d4bd8
git cherry-pick -x f62a00ac896d4dc0ab89462f8eee022502f3a823
git cherry-pick -x f4523a63a9a9054e00d1e435154a6e7958b1cdf6
This PR updates the content in the current rsync task article in general, and updates the SSH mode instructions to what is tested and verified to work.
This content can …
=> PD-1266 / 13.3 / PD-1266 Update Rsync Task Content (by micjohnson777)

layouts/shortcodes/capacity_calculator.html, static/custom.css
Quick styling changes to make calculator work better with the docs hub light/dark mode selector and some small improvements
=> PD-1859 / 25.10 / Pd 1859 zfscapacitycalculator doesnt show with dark mode

content/SCALE/SCALETutorials/SystemSettings/Advanced/_index.md
Discussed with Andrew W and found two additional auth methods to consider before enabling STIG/FIPS.
=> Add two additional auth methods that are disabled in STIG mode

content/SCALE/SCALEUIReference/SystemSettings/AdvancedSettingsScreen.md
This commit corrects the time conversion for the maximum number of seconds. Added clarification to what the max seconds converts to if hours/minutes/seconds and if days/hours/minutes/seconds.
This can backport to 25.04. Manually backporting to 24.10 because not all the information in the /SCALEUIReference/SystemSettings/Advanced/_index.md is the same as in 25.10 and 25.40 branches
=> PD-1914 / 25.10 / PD-1914 Correct Time Conversion in Session Settings

content/SCALEUIReference/SystemSettings/AdvancedSettingsScreen.md
This PR is a manual backport of the correction to the session timeout  maximum seconds, showing it converted to hours/minutes/seconds and days/hours/minutes/seconds.
=> PD-1914 / 24.10 / PD-1914 Manual Backport of Session Timeout Correction

content/SCALEUIReference/SystemSettings/AdvancedSettingsScreen.md
This commit corrects the time conversion for the maximum number of seconds. Added clarification to what the max seconds converts to if hours/minutes/seconds and if days/hours/minutes/seconds.
This can backport to 25.04. Manually backporting to 24.10 because not all the information in the /SCALEUIReference/SystemSettings/Advanced/_index.md is the same as in 25.10 and 25.40 branches
Original PR: https://github.com/truenas/documentation/pull/3789
Jira URL: https://ixsystems.atlassian.net/browse/PD-1914
=> PD-1914 / 25.04 / PD-1914 Correct Time Conversion in Session Settings (by micjohnson777)

content/SCALETutorials/SystemSettings/AuditingSCALE.md
This PR updates the AudtingSCALE.md article content by adding new audit logging events including STIG-compliant security related events and HA event logs and capabilities. A grammar and spelling check was run on the content with changes made where identified.
Backport to 25.04.
Original PR: https://github.com/truenas/documentation/pull/3799
Jira URL: https://ixsystems.atlassian.net/browse/PD-1703
=> PD-1703 / 25.04 / Pd 1703 update auditing content (by micjohnson777)

static/includes/AppsHostIP.md
git cherry-pick -x c8f30614980143d8b9e9e283a06014ef26e7de55
git cherry-pick -x 0dbda2a7d248086d8521d7d79dce8757b0820709
git cherry-pick -x 3230ea330cbc848f0e5398481fe90308b7da85cb
git cherry-pick -x 642d1a3e7031e737f3be4782139f5dd244e330a3
git cherry-pick -x 851fb26628e9227dbb88986313d1f74cc5d44ecf
Started this as a release notes update, but this update isn't release specific and I think better to release sooner than waiting for 25.04.1
Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the …
=> PD-1994 / 25.10 / PD-1994-Update-App-IP-Support-Lists (by DjP-iX)

content/SCALE/API/_index.md, content/SCALE/SCALETutorials/TopToolbar/ManagingAPIKeys.md
api/_index.md:
- Reorder content to place the includes snippet that the beginning of the API Documentation section. This is informational/introductory content that explains the relevance of the API docs and is better served at the beginning of the section.
- Make the API access options a subheader and bullet list to better differentiate between the individual access methods
- Add a link to the api.truenas.com online location
ManagingAPIKeys.md
- Add one link to the api.truenas.com location and clarify the remaining instructions are for accessing embedded documentation.
Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) …
=> PD-1421: Add references to api.truenas.com and clarify access methods a bit

content/SCALETutorials/SystemSettings/Services/SSHServiceSCALE.md, content/SCALETutorials/SystemSettings/Services/UPSServicesSCALE.md, content/SCALEUIReference/Credentials/DirectoryServices/LDAP.md, content/SCALEUIReference/DataProtection/ReplicationScreensSCALE.md, content/SCALEUIReference/DataProtection/RsyncTasksScreensSCALE.md, content/SCALEUIReference/Shares/SMBSharesScreens.md, content/SCALEUIReference/SystemSettings/Services/FTPServiceScreenSCALE.md, content/SCALEUIReference/SystemSettings/Services/SNMPServiceScreenSCALE.md, content/SCALEUIReference/SystemSettings/Services/SSHServiceScreenSCALE.md, content/SCALEUIReference/SystemSettings/Services/UPSServicesScreenSCALE.md, static/includes/auxiliary-parameters-caution.md
This is a general note that is applied to these user custom input fields:
- SSH (service)
- UPS (service)
- LDAP (creds)
- rsync (task)
- ftp (service)
- snmp (service)
- SMB (share)
Port to 25.10 docs is needed
=> PD-2052 / 25.04 / add notice about auxiliary params to various areas

layouts/partials/docs-nav.html
Fix version switcher generating 404s in analytics
Problem:
The version switcher was using fetch() HEAD requests to validate URLs before redirecting users. These validation
requests were being logged as legitimate 404 errors in analytics when checking non-existent article paths,
creating noise in error reporting.
Solution:
Replace HTTP-based URL validation with sitemap-based validation.
- Sitemap caching: Pre-load and cache XML sitemaps for each product/version
- Client-side validation: Check URLs against cached sitemap data instead of making HTTP requests
- Enhanced product detection: Distinguish TrueNAS CORE vs SCALE as separate product lines (versions <20 = CORE,
≥20 = SCALE)-- NOTE: this is for internal logic only, UX still presents TrueNAS for all versions. 
- Improved path …
=> PD-2098 / 25.10 / Update docs-nav.html

layouts/partials/docs-nav.html
Fix version switcher generating 404s in analytics
Problem:
The version switcher was using fetch() HEAD requests to validate URLs before redirecting users. These validation
requests were being logged as legitimate 404 errors in analytics when checking non-existent article paths,
creating noise in error reporting.
Solution:
Replace HTTP-based URL validation with sitemap-based validation.
- Sitemap caching: Pre-load and cache XML sitemaps for each product/version
- Client-side validation: Check URLs against cached sitemap data instead of making HTTP requests
- Enhanced product detection: Distinguish TrueNAS CORE vs SCALE as separate product lines (versions <20 = CORE,
≥20 = SCALE)-- NOTE: this is for internal logic only, UX still presents TrueNAS for all versions. 
- Improved path …
=> PD-2098 / 13.3 / Update docs-nav.html (by DjP-iX)

content/CORETutorials/Services/ConfiguringFTP.md
git cherry-pick -x 6f744be75558166975b7afff9f8f4105a2bde479
git cherry-pick -x 4db5f6b8322f6210f3f42cd1d0d5bd74ca876357
git cherry-pick -x fbcd5a797888c980f990f21ea32bb05d6b173fc0
Original PR: https://github.com/truenas/documentation/pull/4013
Jira URL: https://ixsystems.atlassian.net/browse/PD-2131
=> PD-2131 / 13.3 / Pd 2131 no indication to add user to ftp group (by DjP-iX)

content/SCALETutorials/DataProtection/CloudSyncTasks/AddGooglePhotosCloudSyncTask.md
git cherry-pick -x 94b3c8541822848d60ad487b1f966c1b5a780857
git cherry-pick -x 6d5deb0f272d99d3ebd1d31ae0fee7b8db92b5f9
git cherry-pick -x 6629c80b6bf822dc59119e8f5aa6ae5b27c2b188
git cherry-pick -x 3f1931db15d4e31a800835f20073ca14045f3d78
git cherry-pick -x f50ae97d9bf526644569baaf2be1336e1cc2e0ce
git cherry-pick -x 6ae00236977b1c06621f662a704f14c8f7b84747
git cherry-pick -x 06dc0f14c6b9968412aa941b8bbbfb514b6611e8
git cherry-pick -x 815dfda78e018b99e53b8ab9347f39b0e3b62149
Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed …
=> PD-2206 / 25.04 / Pd 2206 update content around google photos use (by DjP-iX)

content/GettingStarted/SCALEReleaseNotes.md
This is behavior in 25.10 that is downstream from the reporting system backend (netdata) and is anticipated to be the way 25.10 (at minimum) generally behaves).
=> (25.10) Add blurb to upgrade notes about metric system startup time
