truenas/documentation

layouts/partials/page-header.html
=> whereami notice port to tc 2.3 branch

content/CORE/GettingStarted/COREReleaseNotes.md, content/SCALE/GettingStarted/SCALEReleaseNotes.md, content/TrueCommand/TCGettingStarted/TCReleaseNotes.md, content/TrueNASUpgrades/_index.md, data/properties/core-releases.yaml, data/properties/scale-releases.yaml, data/properties/tc-releases.yaml, layouts/shortcodes/releaselist.html, layouts/shortcodes/section-cards.html, layouts/shortcodes/timeline.html, words-to-ignore.txt
Refines schedule cards and adds new timeline cards to the Release Schedules page. Related improvements.
=> Pd 909 refine the single sourced release schedules presentation

layouts/partials/page-header.html
=> Make whereami note consistent with gdoc hint styling (13.0)

layouts/partials/page-header.html
=> Make whereami note style consistent (22.12)

layouts/partials/page-header.html
=> Make whereami note style consistent (3.0)

layouts/partials/page-header.html
=> Make whereami note styling consistent (2.3)

content/SCALE/SCALETutorials/DataProtection/Replication/RemoteReplicationSCALE.md, content/SCALE/SCALETutorials/DataProtection/Replication/_index.md, content/_includes/BasicReplicationProcess.md, content/_includes/ReplicationCreateDatasetAndAdminHomeDirSteps.md
=> Pd 969 ssh netcat replication and sudo

content/GettingStarted/Install/InstallPrepEnterprise.md, content/GettingStarted/SCALEReleaseNotes.md, content/_includes/SCALEHADisableSTP.md, words-to-ignore.txt
=> PD-989: 23.10.1.3 Hotpatch

content/SCALE/SCALETutorials/Datasets/DatasetsSCALE.md
line 65: Fix minor spelling mistake
=> DOC: Update DatasetsSCALE.md

content/SCALE/GettingStarted/SCALEReleaseNotes.md
=> PD-866: Add note about ZFS ARC allocations

content/SCALEUIReference/Apps/InstallCustomAppScreens.md
=> PD-971: backport typo fix (23.10)

content/SCALE/SCALETutorials/Apps/UsingCatalogs.md
This PR fixes a typo on the [Using Catalogs](https://arc.net/l/quote/iqktbunr) page.
=> Fix typo on Using Catalogs

data/properties/core-downloads.yaml, data/properties/scale-downloads.yaml, layouts/shortcodes/tabbox.html
- Clean up some unused elements from the data/properties files.
- Attempt one fix to help the active tab selector find the right element. This works in local build testing, but not on the live site, so testing is tricky.
=> Small cleanup to tabbox to attempt to fix active tab select

content/SCALETutorials/Credentials/Certificates/SettingUpLetsEncryptCertificates.md
page https://www.truenas.com/docs/scale/scaletutorials/credentials/certificates/settingupletsencryptcertificates/
=> Copy info about CloudFlare API Keys from the main Tutorials

content/SCALETutorials/Credentials/Certificates/SettingUpLetsEncryptCertificates.md
Copied from https://www.truenas.com/docs/scale/scaletutorials/credentials/certificates/settingupletsencryptcertificates/
=> Add info on Cloudflare API Key creation

layouts/shortcodes/releaselist.html, layouts/shortcodes/tabbox.html
Javascript updates to fix active tab display in Software Releases cards
=> Active Tab Fix

static/js/search.js
testing with /includes, /printview, and /tags getting excluded from results.
=> (Dev1) Experiment to filter out search results

jenkins/update-dev1, layouts/_default/baseof.html, layouts/search/list.html, static/custom.css, static/js/search.js
=> Pagefind improvements

jenkins/update-dev1
=> Update update-dev1 (try 2)

jenkins/update-dev1
=> Update update-dev1 - glob test

content/SCALE/GettingStarted/SCALEReleaseNotes.md, content/_includes/24.04FeatureList.md
Clarify audit feature text to better reflect the specific elements that are being audited.
=> Small adjust to 24.04 relnotes text

content/SCALE/SCALETutorials/Shares/MixedModeShares.md
Update to use existing image that meets the doc need.
=> Fix broken image call in MixedModeShares.md

content/CORE/UIReference/Network/InterfacesScreen.md
=> PD-983: fix typo on InterfacesScreen.md

layouts/search/list.html, static/js/search.js
- fix icon calls
- additional change ported from dev branch for removing unnecessary text from results page.
=> Search results additional polish

static/custom.css
=> Add highlight styling to go with pagefind improvements

content/GettingStarted/Configure/SetUpSharing.md, content/SCALETutorials/Shares/SMB/AddSMBHomeShare.md, content/SCALETutorials/Shares/SMB/AddSMBShares.md, content/SCALETutorials/SystemSettings/Services/SMBServiceSCALE.md, content/SCALEUIReference/Shares/SMBSharesScreens.md, content/SCALEUIReference/SystemSettings/Services/SMBServicesScreen.md, content/_includes/SMBShareMSDOSalert.md
=> PD-1020: Backport SMB1 warning clarification (23.10 branch)

content/GettingStarted/Configure/SetUpSharing.md, content/SCALETutorials/Shares/SMB/AddSMBHomeShare.md, content/SCALETutorials/Shares/SMB/AddSMBShares.md, content/SCALETutorials/SystemSettings/Services/SMBServiceSCALE.md, content/SCALEUIReference/Shares/SMBSharesScreens.md, content/SCALEUIReference/SystemSettings/Services/SMBServicesScreen.md, content/_includes/SMBShareMSDOSalert.md
=> PD-1020: Backport SMB1 warning clarification (22.12 branch)

jenkins/update-3.0, static/js/search.js
Update pagefind to generate an index for the 3.0 branch build.
Resync the search.js results functionality with master.
Adjust the search.js functionality to pull from the new 3.0 pagefind index.
=> PD-1013: backport style improvements and update 3.0 branch pagefind implementation

jenkins/update-3.0, layouts/_default/baseof.html, layouts/_default/baseof.print.html, layouts/search/list.html, static/custom.css, static/js/search.js
With Jenkins question solved, retry implementing the pagefind solution and refinements on the TC 3.0 branch.
=> PD-1013: Retry pagefind on TC 3.0 branch

static/js/anchorpad.js
=> Fix anchor scroll padding issue with _includes

content/GettingStarted/SCALEReleaseNotes.md, static/api/scale_rest_api.html
=> Pd 1009 scale 23.10.2 release notes

content/SCALE/SCALETutorials/DataProtection/Replication/AdvancedReplication/_index.md, content/_includes/BasicReplicationProcess.md, content/_includes/ReplicationCreateDatasetAndAdminHomeDirSteps.md, content/_includes/ReplicationIndexContentSCALE.md, content/_includes/ReplicationIntroSCALE.md, words-to-ignore.txt
Combine redundant text.
Rework conflicting/confusing statements about Snapshot Tasks to simplify the requirement.
Rework some admonition boxes.
=> PD-1010: PR review

content/SCALE/GettingStarted/Migrate/MigrateCOREHAtoSCALEHA.md, content/SCALE/GettingStarted/Migrate/MigratingFromCORE.md, content/SCALE/SCALETutorials/Credentials/ManageLocalUsersSCALE.md, content/_includes/AddAdminUserAccount.md
Fix a build issue from include shortcode syntax error.
Simplify the HA article down to a simple bullet of process requirements and encouragement to consult iX support.
=> Update PR #2499 with Enterprise-specific changes

content/SCALETutorials/SystemSettings/Services/SNMPServiceSCALE.md
=> PD-1054: (Cobia Docs) Update SNMP tutorial to include MIB

content/References/Performance/InterconnectDataRates.md, content/References/Performance/SMBFileTimes.md, content/SCALE/GettingStarted/SCALEHardwareGuide.md
draft = true until regular content is added.
=> PD-1072: placeholder article for new perf data

content/References/Performance/SMBFileTimes.md, content/SCALE/GettingStarted/SCALEReleaseNotes.md, content/_includes/24.04FeatureList.md, words-to-ignore.txt
=> Publish SMB file list Perf numbers

content/TCGettingStarted/TCReleaseNotes.md, content/_includes/LifecycleTable.md, content/_includes/ReleaseScheduleWarning.md, data/properties/tc-releases.yaml, layouts/shortcodes/releaselist.html, words-to-ignore.txt
=> Pd 1031 TC 3.0.1 documentation

content/SCALE/SCALEUIReference/ReportingScreensSCALE.md, content/_includes/24.04FeatureList.md
=> Add NetData blurb to 24.04 features

content/SCALE/GettingStarted/Install/InstallEnterpriseHASCALE.md
This PR fixes the subtask list in the Installing ISO Steps section, step 3 subtasks to appear as a list and not in a paragraph.
=> PD-1087 Update Subtask List Formatting (master branch)

content/SCALE/GettingStarted/SCALEReleaseNotes.md
=> Remove 24.04 relnotes alias (prep for the 24.04 branch to go live)

content/GettingStarted/Install/InstallEnterpriseHASCALE.md
=> PD-1087: port small format fix to 24.04 branch

content/GettingStarted/SCALEReleaseNotes.md
=> Update SCALEReleaseNotes.md to remove direct path from BlueFin

content/GettingStarted/Configure/SetUpBackupScale.md
=> Update SetUpBackupScale.md (23.10 Branch)

content/GettingStarted/Configure/SetUpBackupScale.md
=> Update SetUpBackupScale.md (22.12)

content/GettingStarted/Migrate/MigratePrep.md
Polish updates to this article to improve readability.
Edits can be backported to Master.
=> Improved MigratePrep.md Content

content/SCALETutorials/SystemSettings/UpdateSCALE.md
=> Port update scale.md content updates

content/SCALETutorials/Storage/Pools/ManagePoolsScale.md
The process is identical to 24.04, so I copied it over and made some small changes.
=> PD-1090   23.10 storage tutorial using outdated screenshots

layouts/_default/_markup/render-heading.html
=> PD-1095-anchors-not-copying-the-full-link

layouts/_default/_markup/render-heading.html, layouts/shortcodes/expand.html
Ports changes from main branch
=> Pd 1095 anchors not copying the full link (24.04)

content/GettingStarted/Install/InstallingSCALE.md, static/includes/SCALEInstallerProcedure.md
This PR updates the content in the InstallingSCALE.md article and SCALEInstallerProcedure.md snippet in the 24.04 branch.
These changes can be backported to Master.
=> Updates to installation articles 24.04 Branch

content/SCALETutorials/Shares/AddingNFSShares.md, content/SCALETutorials/SystemSettings/Services/NFSServiceSCALE.md, content/SCALEUIReference/Shares/NFSSharesScreens.md, content/SCALEUIReference/SystemSettings/Services/NFSServiceScreen.md, static/includes/NFSServiceUDPWarning.md
This PR backports the hint admonition and UDP Protocol and NFS snippet to 24.04
=> PD-1086 Backport UDP Protocol and NFS Snippet to 24.04

data/properties/core-downloads.yaml
=> Update core-downloads.yaml for updated 13.3 iso location

content/SCALE/SCALETutorials/Apps/CommunityApps/Immich.md
This PR adds information about backing up and restoring the Immich database on TrueNAS.
=> Docs: Update Immich.md

static/includes/COREFeatureSupport.md, static/includes/S3Deprecation.md
=> Pd 1099 deprecation warnings on core 13 3

README.md, content/GettingStarted/Getting Support/GetSupportSCALE.md, content/GettingStarted/Migrate/SCALEZFSFlagRemoval.md, content/SCALEUIReference/SCALEDashboard.md, content/SCALEUIReference/SystemSettings/GeneralSettingsScreens.md, layouts/partials/menu-nextprev.html, layouts/partials/site-header.html, static/includes/CommunityForums.md, static/includes/iXsystemsSupportContact.md
=> Pd 1110 update forum links 23.10

README.md, content/GettingStarted/Getting Support/GetSupportSCALE.md, content/GettingStarted/Migrate/SCALEZFSFlagRemoval.md, content/SCALEUIReference/SCALEDashboard.md, content/SCALEUIReference/SystemSettings/GeneralSettingsScreens.md, layouts/partials/menu-nextprev.html, layouts/partials/site-header.html, static/includes/iXsystemsSupportContact.md
=> Pd 1110 update forum links 22.12

README.md, content/CORETutorials/Getting Support.md, content/CORETutorials/Tasks/CreatingInitShutdownScripts.md, layouts/partials/menu-nextprev.html, layouts/partials/site-header.html, static/includes/COREFeatureSupport.md, static/includes/iXsystemsSupportContact.md
=> Pd 1110 update forum links 13.0

README.md, content/Introduction/Support.md, layouts/partials/menu-nextprev.html, layouts/partials/site-header.html, static/includes/iXsystemsSupportContact.md
=> Pd 1110 update forum links 2.3

README.md, content/TCGettingStarted/Support.md, layouts/partials/menu-nextprev.html, layouts/partials/site-header.html, static/includes/iXsystemsSupportContact.md
=> Pd 1110 update forum links 3.0

layouts/partials/head/favicons.html, static/favicon/TN-favicon.svg
=> Pd 1108 fix browser tab titling

content/SCALETutorials/SystemSettings/Advanced/ManageGlobal2FASCALE.md, content/SCALEUIReference/SystemSettings/AdvancedSettingsScreen.md
This PR backports the two key changes from Master to the 23.10 branch in the Advanced Settings UI article and the Managing Global 2FA tutorial.
=> Backport Advanced Settings Article Changes to 23.10

content/SCALETutorials/DataProtection/ScrubTasksSCALE.md, content/SCALEUIReference/DataProtection/ScrubTasksScreensSCALE.md, static/includes/ResilverPriority.md, static/includes/ResilverPrioritySetWhen.md, static/includes/ResliverPrioritySetWhen.md
This PR backports the changes to the SCALE UI ref and scrub task tutorials, and adds the two new snippets.
=> Backport Resilvering Updates to 24.04

content/SCALETutorials/DataProtection/ScrubTasksSCALE.md, content/SCALEUIReference/DataProtection/ScrubTasksScreensSCALE.md, static/includes/ResilverPriority.md, static/includes/ResilverPrioritySetWhen.md, static/includes/ResliverPrioritySetWhen.md
This PR backports the changes to the SCALE UI ref and tutorials for resilvering/scrub tasks and adds the two new snippets.
=> Backport Resilvering Updates to 23.10

content/TrueNASUpgrades/_index.md
=> Update Software Releases Upgrade Paths

layouts/_default/baseof.print.html
Removed conditional that isn't needed for non-master branches and locally built and validated the getting started guide printview is now properly generating.
This needs a check and backport to other version branches and a note in the branching checklist.
=> PD-1123: Fix printview generation for 24.04 Getting Started Guide

content/SCALE/GettingStarted/Configure/SetUpSharing.md
changed Fileshsystem to Filesystem
=> Fix typo in  SetUpSharing.md

content/GettingStarted/Migrate/MigratePrep.md, content/GettingStarted/SCALEReleaseNotes.md, content/SCALECLIReference/Storage/CLIScrub.md, content/SCALETutorials/Apps/CommunityApps/InstallPiHoleApp.md, content/SCALETutorials/Apps/UsingCustomApp.md, content/SCALETutorials/ConfigReportsScale.md, content/SCALETutorials/Shares/MixedModeShares.md, content/SCALETutorials/Storage/Pools/SLOGOverprovisionSCALE.md, content/SCALETutorials/Virtualization/AccessingNASFromVM.md, content/SCALEUIReference/Credentials/BackupCredentials/CloudCredentialScreens.md, content/SCALEUIReference/ReportingScreensSCALE.md, static/includes/BrowsingSnapshotCollections1.md, static/includes/MinIODatasetRequirements.md
=> PD-1093-building-documenation-locally-from-main-branch-fails-23.10

content/TCGettingStarted/UserAccounts.md
=> PD-1093-building-documenation-locally-from-main-branch-fails-3.0

data/properties/core-releases.yaml
=> Update core-releases.yaml (13.3 branch backport)

content/_index.md, i18n/en.yaml, layouts/partials/docs-nav.html, layouts/partials/page-header.html
=> Pd 1046 archive 22 12 documentation 22.12

content/Archive.md, layouts/partials/docs-nav.html
=> Pd 1046 archive 22 12 documentation

layouts/partials/docs-nav.html
=> Pd 1046 archive 22 12 documentation 24.04

layouts/partials/docs-nav.html
=> Pd 1046 archive 22 12 documentation 23.10

layouts/partials/docs-nav.html
=> Pd 1046 archive 22 12 documentation 13.3

layouts/partials/docs-nav.html
=> Pd 1046 archive 22 12 documentation 3.0

static/includes/24.10FeatureList.md
=> Add anticipated feature

layouts/partials/docs-nav.html
=> Pd 1046 archive 22 12 documentation 2.3

content/GettingStarted/SCALEReleaseNotes.md, layouts/shortcodes/UpgradePaths.html, static/includes/SCALEUpgradePaths.md, words-to-ignore.txt
=> Pd 1106 follow up 24.04

content/GettingStarted/COREReleaseNotes.md, data/properties/core-releases.yaml
Update release name to 13.3-BETA1
=> 13.3-BETA1 Port updates to 13.3

content/CORETutorials/Services/ConfiguringSSH.md
=> PD-1138-remove-ssh-service-tuning-recommendations-13.3

layouts/shortcodes/enterprise-error.html
=> Create enterprise-error.html (24.04 backport)

content/GettingStarted/SCALEReleaseNotes.md
=> PD-1162-add-known-issue-to-24-04-0-release-notes-about-swap-and-performance-issues

static/includes/TNHardwareGuide.md
This PR backports the changes made to the TNHardwareGuide.md changes to the 24.04 branch
=> PD-1124 Backport TNHardwareGuide.md Changes to 24.04

content/SCALETutorials/Shares/AddingNFSShares.md, content/SCALETutorials/SystemSettings/AuditingSCALE.md, content/SCALEUIReference/SystemSettings/AdvancedSettingsScreen.md, content/SCALEUIReference/SystemSettings/Services/SMBServicesScreen.md, static/includes/ConfigureSystemAuditSCALE.md
=> Backport of Update the audit reference and tutorial documentation

content/CORE/GettingStarted/COREReleaseNotes.md
=> PD-1147-remove-alias

content/CORE/GettingStarted/COREReleaseNotes.md, layouts/partials/docs-nav.html, layouts/shortcodes/section-cards.html
=> Pd 1147 publish 13 3 branch to live website

layouts/partials/docs-nav.html
=> Pd-1147-Backport-13.3

layouts/partials/docs-nav.html
=> Pd 1147 backport 13.0

layouts/partials/docs-nav.html
=> Pd 1147 backport 3.0

layouts/partials/docs-nav.html
=> Pd 1147 backport 2.3

layouts/partials/docs-nav.html
=> Pd-1147-backport-22.12

layouts/partials/docs-nav.html
=> Pd 1147 backport 23.10

content/CORE/CORETutorials/JailsPluginsVMs/Jails/SettingUpJailStorage.md
=> Fix html syntax in CORE jail storage tutorial

content/Hardware/ExpansionShelves.md, content/Hardware/FSeries.md, content/Hardware/HSeries.md, content/Hardware/MSeries.md, content/Hardware/MiniFamily.md, content/Hardware/RSeries.md, layouts/shortcodes/prodintro.html, words-to-ignore.txt
This PR adds the description and keyword front matter parameters to the hardware platform _index.md articles and adds SEO terms in both the description and the keywords. It adds a link to the sales pages through the product image and a text-based link to the content.
It updates the layouts/shortcodes/prodintro.html file to allow the links from the image to work. Do not backport these changes.
=> PD-1179 Update Hardware _index.md Articles With SEO

data/properties/core-releases.yaml, static/includes/COREUpgradePaths.md
=> Pd 1158 port re add core 12 0 to upgrade paths and release lists 13.3

static/includes/iXsystemsSupportContact.md
=> PD-1178-replace-gold-support-number-on-support-contact-snippets-24.04

static/includes/iXsystemsSupportContact.md
=> PD-1178-replace-gold-support-number-on-support-contact-snippets-23.10

static/includes/iXsystemsSupportContact.md
=> PD-1178-replace-gold-support-number-on-support-contact-snippets-22.12

static/includes/iXsystemsSupportContact.md
=> PD-1178-replace-gold-support-number-on-support-contact-snippets-3.0

static/includes/iXsystemsSupportContact.md
=> PD-1178-replace-gold-support-number-on-support-contact-snippets-2.3

static/includes/iXsystemsSupportContact.md
=> PD-1178-replace-gold-support-number-on-support-contact-snippets-13.3

static/includes/iXsystemsSupportContact.md
=> PD-1178-replace-gold-support-number-on-support-contact-snippets-13.0

layouts/partials/docs-nav.html
=> docs-dev1 testing

content/GettingStarted/SCALEReleaseNotes.md
=> 24.04.1 Known Issue with Apps Service start

data/properties/scale-downloads.yaml, data/properties/scale-releases.yaml, static/includes/SCALEUpgradePaths.md
=> (master branch) 24.04.1.1 links updates

data/properties/scale-releases.yaml
=> Update release dates for 24.04.2 and 24.10 anticipated releases.

content/SCALETutorials/Apps/EnterpriseApps/MinIO/ConfigMinioEnterpriseMNMD.md, content/SCALETutorials/Apps/EnterpriseApps/MinIO/ConfigMinioEnterpriseSNMD.md, content/SCALETutorials/Apps/EnterpriseApps/MinIO/_index.md, content/SCALETutorials/Apps/EnterpriseApps/Syncthing.md, content/SCALETutorials/Apps/EnterpriseApps/_index.md, static/includes/SCALEEnterpriseApps.md
=> (24.04 docs) Update Enterprise apps messaging with single-source snippet

content/SCALETutorials/Apps/EnterpriseApps/MinIO/ConfigMinioEnterpriseMNMD.md, content/SCALETutorials/Apps/EnterpriseApps/MinIO/ConfigMinioEnterpriseSNMD.md, content/SCALETutorials/Apps/EnterpriseApps/MinIO/_index.md, content/SCALETutorials/Apps/EnterpriseApps/Syncthing.md, content/SCALETutorials/Apps/EnterpriseApps/_index.md, static/includes/SCALEEnterpriseApps.md
backported changes from master
=> (23.10 docs) Update Enterprise apps messaging with single-source snippet

content/SCALE/GettingStarted/UserAgreements/DataCollectionStatement.md, content/SCALE/SCALETutorials/SystemSettings/General/GeneralSettings.md, content/SCALE/SCALEUIReference/SystemSettings/GeneralSettingsScreens.md, static/includes/SystemGeneralFields.md, static/includes/TNDataCollection.md
=> Pd 1161 expand usage collection documentation

data/properties/core-releases.yaml
=> Update core-releases.yaml for BETA2 release

content/CORE/GettingStarted/COREReleaseNotes.md
=> Follow up: Rework CORErelease notes for generic nightlies

content/SCALE/SCALETutorials/Apps/UsingCatalogs.md, content/SCALE/SCALEUIReference/Apps/_index.md, static/includes/ThirdPartyCatalogs.md
=> Pd 1128 expand cautions on custom catalog content

content/GettingStarted/SCALEReleaseNotes.md, words-to-ignore.txt
=> Add known issue with apps connectivity to 24.04.1.1 notes

content/CORE/CORETutorials/JailsPluginsVMs/VirtualMachines/_index.md, content/CORE/_index.md, content/SCALE/_index.md, content/TrueCommand/_index.md, content/_index.md, data/menu/more.yml, layouts/_default/baseof.html, layouts/partials/menu-filetree.html, layouts/partials/menu.html
=> Pd 1191 testing

content/SCALE/GettingStarted/SCALEReleaseNotes.md, static/includes/24.10FeatureList.md
=> Update 24.10 nightly notes with Kubernetes > Docker update

README.md
Newer versions haven't been tested or deployed in automation yet, so document which version is recommended to use for now.
=> Update README.md with specific Hugo version

content/SCALE/SCALETutorials/Apps/AppSecurity/CloudflareTunnel.md, content/SCALE/SCALETutorials/Apps/CommunityApps/AddStorjNode.md, content/SCALE/SCALETutorials/Apps/CommunityApps/Chia.md, content/SCALE/SCALETutorials/Apps/CommunityApps/Collabora.md, content/SCALE/SCALETutorials/Apps/CommunityApps/Immich.md, content/SCALE/SCALETutorials/Apps/CommunityApps/InstallNetdataApp.md, content/SCALE/SCALETutorials/Apps/CommunityApps/InstallNextCloudMedia.md, content/SCALE/SCALETutorials/Apps/CommunityApps/InstallPiHoleApp.md, content/SCALE/SCALETutorials/Apps/CommunityApps/InstallWGEasyApp.md, content/SCALE/SCALETutorials/Apps/CommunityApps/MinIOApp/MinIOClustering.md, content/SCALE/SCALETutorials/Apps/CommunityApps/MinIOApp/MinioManualUpdate.md, content/SCALE/SCALETutorials/Apps/CommunityApps/MinIOApp/_index.md, content/SCALE/SCALETutorials/Apps/CommunityApps/PrometheusApp.md, content/SCALE/SCALETutorials/Apps/CommunityApps/Rsyncd.md, content/SCALE/SCALETutorials/Apps/CommunityApps/SyncthingCharts.md, content/SCALE/SCALETutorials/Apps/CommunityApps/TFTP-HPAApp.md, content/SCALE/SCALETutorials/Apps/CommunityApps/WebDAV.md, content/SCALE/SCALETutorials/Apps/CommunityApps/_index.md, content/SCALE/SCALETutorials/Apps/CommunityApps/ddns-updater.md, content/SCALE/SCALETutorials/Apps/CommunityApps/jellyfin.md, content/SCALE/SCALETutorials/Apps/_index.md, static/includes/AppsUnversioned.md, static/includes/CommunityAppsContribute.md
=> Pd 1167 master 24 04 and 23 10 docs add content to apps about unversioned updating

content/SCALETutorials/Apps/CommunityApps/AddStorjNode.md, content/SCALETutorials/Apps/CommunityApps/Chia.md, content/SCALETutorials/Apps/CommunityApps/Collabora.md, content/SCALETutorials/Apps/CommunityApps/InstallNetdataApp.md, content/SCALETutorials/Apps/CommunityApps/InstallNextCloudMedia.md, content/SCALETutorials/Apps/CommunityApps/InstallPiHoleApp.md, content/SCALETutorials/Apps/CommunityApps/InstallWGEasyApp.md, content/SCALETutorials/Apps/CommunityApps/MinIOApp/MinIOClustering.md, content/SCALETutorials/Apps/CommunityApps/MinIOApp/MinioManualUpdate.md, content/SCALETutorials/Apps/CommunityApps/MinIOApp/_index.md, content/SCALETutorials/Apps/CommunityApps/PrometheusApp.md, content/SCALETutorials/Apps/CommunityApps/Rsyncd.md, content/SCALETutorials/Apps/CommunityApps/SyncthingCharts.md, content/SCALETutorials/Apps/CommunityApps/TFTP-HPAApp.md, content/SCALETutorials/Apps/CommunityApps/WebDAV.md, content/SCALETutorials/Apps/CommunityApps/_index.md, content/SCALETutorials/Apps/CommunityApps/ddns-updater.md, content/SCALETutorials/Apps/_index.md, static/includes/AppsUnversioned.md, static/includes/CommunityAppsContribute.md
=> Pd 1167 master 24 04 and 23 10 docs add content to apps about unversioned updating (port to 23.10)

content/SCALETutorials/Apps/AppSecurity/CloudflareTunnel.md, content/SCALETutorials/Apps/CommunityApps/AddStorjNode.md, content/SCALETutorials/Apps/CommunityApps/Chia.md, content/SCALETutorials/Apps/CommunityApps/Collabora.md, content/SCALETutorials/Apps/CommunityApps/Immich.md, content/SCALETutorials/Apps/CommunityApps/InstallNetdataApp.md, content/SCALETutorials/Apps/CommunityApps/InstallNextCloudMedia.md, content/SCALETutorials/Apps/CommunityApps/InstallPiHoleApp.md, content/SCALETutorials/Apps/CommunityApps/InstallWGEasyApp.md, content/SCALETutorials/Apps/CommunityApps/MinIOApp/MinIOClustering.md, content/SCALETutorials/Apps/CommunityApps/MinIOApp/MinioManualUpdate.md, content/SCALETutorials/Apps/CommunityApps/MinIOApp/_index.md, content/SCALETutorials/Apps/CommunityApps/PrometheusApp.md, content/SCALETutorials/Apps/CommunityApps/Rsyncd.md, content/SCALETutorials/Apps/CommunityApps/SyncthingCharts.md, content/SCALETutorials/Apps/CommunityApps/TFTP-HPAApp.md, content/SCALETutorials/Apps/CommunityApps/WebDAV.md, content/SCALETutorials/Apps/CommunityApps/_index.md, content/SCALETutorials/Apps/CommunityApps/ddns-updater.md, content/SCALETutorials/Apps/CommunityApps/jellyfin.md, content/SCALETutorials/Apps/_index.md, static/includes/AppsUnversioned.md, static/includes/CommunityAppsContribute.md
=> Pd 1167 master 24 04 and 23 10 docs add content to apps about unversioned updating (port to 24.04)

content/CORE/CORETutorials/JailsPluginsVMs/VirtualMachines/_index.md, content/CORE/_index.md, content/SCALE/_index.md, content/TrueCommand/_index.md, content/_index.md, data/menu/more.yml, layouts/_default/baseof.html, layouts/partials/menu-filetree.html, layouts/partials/menu.html, layouts/shortcodes/section-cards.html
=> Pd 1191 create custom nav for docs hub landing page

layouts/partials/docs-nav.html
=> PD-1190-publish-new-version-switcher

layouts/partials/docs-nav.html
=> PD-1190-publish-new-version-switcher-(2.3)

layouts/partials/docs-nav.html
This reverts commit bf4145562038408a017a42263014d105b416eb8b.
=> Revert "Update docs-nav.html"

layouts/partials/docs-nav.html
Reverts truenas/documentation#2834
=> Revert "Pd 1190 publish new version switcher"

layouts/partials/docs-nav.html
=> Pd 1190 publish new version switcher (experiment)

layouts/partials/docs-nav.html
=> PD-1190-publish-new-version-switcher (fix redirect)

content/SCALE/SCALETutorials/DataProtection/Replication/RemoteReplicationSCALE.md
=> PD-1235: quick copy-edit of intro text

content/_index.md, layouts/partials/docs-nav.html
=> PD-1190-publish-new-version-switcher-follow-up

layouts/partials/docs-nav.html
=> PD-1190-publish-new-version-switcher-(3.0)

layouts/partials/docs-nav.html
=> Pd 1190 publish new version switcher (13.0)

layouts/partials/docs-nav.html
=> Pd 1190 publish new version switcher (13.3)

layouts/partials/docs-nav.html
=> Pd 1190 publish new version switcher (23.10)

layouts/partials/docs-nav.html
=> Update docs-nav.html 13.3

layouts/partials/docs-nav.html
=> 13.0 fix docs nav

layouts/partials/docs-nav.html
=> 23.10 fix docs nav

content/_index.md
=> Reposition/edit _index intro text

content/SCALE/SCALETutorials/Apps/Sandboxes.md
Alias command updated to reflect upstream change, see: https://forums.truenas.com/t/changing-default-editor-update-alternatives-not-working/6984/7
=> PD-1202-follow-up

content/SCALE/SCALETutorials/Network/SettingUpIPMI.md, content/SCALE/SCALEUIReference/SystemSettings/AlertsSettingsServiceScreen.md, static/includes/AlertsCategories.md, static/includes/IPMISELAlert.md
=> Pd 1183 add additional info about how to clear the log from ipmi to get rid of the alert

content/SCALE/SCALETutorials/Credentials/BackupCredentials/AddSSHConnectionKeyPair.md
Fix typo
Remove obsolete references to FreeNAS
No backport necessary
=> PD-1240: Small cleanup for SSHConnectionKeyPairs

content/SCALE/SCALETutorials/Apps/CommunityApps/InstallNextCloudMedia.md
Adding clarification for 999 user and group to address confusion reported in the forums. 
=> PD-1245-unclear-dataset-under-troubleshooting-follow-up

static/includes/TNHardwareGuide.md
Master branch already has this change, no cherry-pick needed.
=> (24.04) PD-1259: Duplicated text in SCALE hardware guide

content/GettingStarted/COREReleaseNotes.md
=> Add 13.0 Known issue and workaround

content/GettingStarted/COREReleaseNotes.md, words-to-ignore.txt
=> PD-1262: 13.0-U6.2 release notes

content/SCALE/SCALETutorials/DataProtection/RsyncTasksSCALE.md, content/SCALE/SCALEUIReference/DataProtection/RsyncTasksScreensSCALE.md
=> Pd 1208 review in detail the rsync task creation via ssh mode

content/GettingStarted/SCALEReleaseNotes.md, data/properties/scale-releases.yaml, static/api/scale_rest_api.html, words-to-ignore.txt
=> Pd 1247 24 04 2 release notes

content/SCALETutorials/Shares/SMB/AddSMBHomeShare.md
=> Clarify AddSMBHomeShare.md

content/SCALE/SCALETutorials/Shares/SMB/AddSMBHomeShare.md
=> Port AddSMBHomeShare.md updates from 24.04

content/SCALE/SCALETutorials/SystemSettings/AuditingSCALE.md
port update from 24.04 to master branch.
=> AuditingSCALE.md - Update Unlink Events description (master)

content/SCALETutorials/SystemSettings/AuditingSCALE.md
Update erroneous description to note this logs deletion requests.
=> AuditingSCALE.md - fix Unlink Events text (24.04)

content/_index.md
=> PD-1292: fix a broken link on TC 3.0 docs home page

content/GettingStarted/Migrate/MigratingFromCORE.md
=> PD-1292: fix broken link in 23.10 docs

.github/workflows/build-external-contrib.yml
=> (24.04) Update pnpm action to v4 for external contrib workflow

.github/workflows/build-external-contrib.yml
=> (13.3) Update pnpm action to v4 for external contrib workflow

.github/workflows/build-external-contrib.yml
=> (master) Update pnpm action to v4 for external contrib workflow

.github/workflows/build-external-contrib.yml
=> (3.0) Update pnpm action to v4 for external contrib workflow

content/GettingStarted/SCALEReleaseNotes.md
=> (24.04) Add known issue about NUT service behavior and upstream update

content/References/SLOG.md
Chris Peredun said that the above sentences were technically correct, but that they should be augmented to insinuate that these are only "best practices" recommendations and not the sole solutions. Edited as such.
=> PD-977-sme-review-of-slog-reference-articles

content/SCALE/SCALEUIReference/SCALEDashboard.md
update image call to correct image name
only for master branch
=> Update SCALEDashboard.md (image fix)

static/includes/iSCSIRef.md
=> (13.0) Quick url fix

data/properties/core-downloads.yaml
=> Add 13.3-BETA2 to core-downloads.yaml

content/CORE/GettingStarted/COREReleaseNotes.md
=> Pd 1287 link to true nas core 13 0 release train release notes from https www truenas com docs core gettingstarted corereleasenotes

content/GettingStarted/SCALEReleaseNotes.md
small update with engineering suggested change
=> PD-1360: update NUT known issue (24.04)

content/Archive.md, content/TrueNASUpgrades/_index.md, content/_index.md
Clarifies documentation lifecycle with reference to the Software Status page
=> Pd 1327 update docs hub content

content/_index.md, i18n/en.yaml, layouts/partials/docs-nav.html, layouts/partials/page-header.html
=> Pd 1329 archive tc 2 3 docs version branch

layouts/partials/docs-nav.html
=> Pd 1329 archive tc 2 3 docs 24.04

layouts/partials/docs-nav.html
=> Pd-1329-archive-tc-2-3-docs-3.0

layouts/partials/docs-nav.html
=> Pd 1329 archive tc 2 3 docs 13.3

layouts/partials/docs-nav.html
=> Pd-1329-archive-tc-2-3-docs-13.0

content/SCALE/SCALEUIReference/Shares/SMBSharesScreens.md
Added more description to each row of the affected table. 
=> PD-1263-clarify-smb-share-purpose-descriptions-in-both-ui-ref-and-tutorial-and-review-the-settings-preset-to-each-purpose

content/References/ExtensionCalculator.md
=> Correct frontmatter for extensioncalculator 

content/SCALE/GettingStarted/SCALEReleaseNotes.md
=> Update EE Component versions

content/SCALETutorials/Apps/UsingCustomApp.md, content/SCALEUIReference/Apps/InstallCustomAppScreens.md
=> Pd 1127 24.04 expand tutorials for deploying custom apps directly from docker hub or other primary pull points

static/includes/SCALEUpgradePaths.md
Found some cruft in the SCALE path and added another entry for the 13.3-RELEASE (with current recommended upgrade path)
=> Update the upgrade paths a little more (master)

static/includes/SCALEUpgradePaths.md
=> (24.04) upgrade path update

layouts/partials/reading-time.html
=> PD-1298 port to 13.3

layouts/partials/reading-time.html
=> PD-1298 port to 13.0

layouts/partials/reading-time.html
=> PD-1298 Port to 3.0

content/GettingStarted/SCALEReleaseNotes.md
=> Add 24.04.2 known issue with CORE migration

layouts/partials/docs-nav.html
Cherry-pick from https://github.com/truenas/documentation/pull/3010
=> (24.04 branch) Replace SCALE Nightly version text to 24.10 (temporary)

layouts/partials/docs-nav.html
Cherry-pick from https://github.com/truenas/documentation/pull/3010
=> (13.3 branch) Replace SCALE Nightly version text to 24.10 (temporary)

layouts/partials/docs-nav.html
Cherry-pick from https://github.com/truenas/documentation/pull/3010
=> (13.0 branch) Replace SCALE Nightly version text to 24.10 (temporary)

content/SCALE/GettingStarted/SCALEReleaseNotes.md
=> Update SCALEReleaseNotes.md - typo fixes

layouts/partials/docs-nav.html
Cherry-pick from https://github.com/truenas/documentation/pull/3010
=> (23.10 branch) Replace SCALE Nightly version text to 24.10 (temporary)

layouts/partials/docs-nav.html
Cherry-pick from https://github.com/truenas/documentation/pull/3010 
=> (3.0 branch) Replace SCALE Nightly version text to 24.10 (temporary)

content/GettingStarted/SCALEReleaseNotes.md, data/properties/scale-downloads.yaml, data/properties/scale-releases.yaml, static/includes/SCALEUpgradePaths.md
=> 24.04.2.2 Release Notes

data/properties/scale-downloads.yaml, data/properties/scale-releases.yaml, static/includes/SCALEUpgradePaths.md
=> 24.04.2.2 release followup (24.10 branch)

content/GettingStarted/SCALEReleaseNotes.md, data/properties/scale-downloads.yaml, data/properties/scale-releases.yaml, static/includes/SCALEUpgradePaths.md
Reverts truenas/documentation#3037
=> Revert "24.04.2.2 Release Notes"

data/properties/scale-downloads.yaml, data/properties/scale-releases.yaml, static/includes/SCALEUpgradePaths.md
Reverts truenas/documentation#3039
=> Revert "24.04.2.2 release followup (24.10 branch)"

data/properties/scale-downloads.yaml, data/properties/scale-releases.yaml, static/includes/SCALEUpgradePaths.md
Reverts truenas/documentation#3038
=> Revert "Port 24.04.2.2 schedule updates to master"

content/GettingStarted/SCALEReleaseNotes.md, data/properties/scale-downloads.yaml, data/properties/scale-releases.yaml, static/includes/SCALEUpgradePaths.md
Reverts truenas/documentation#3042
=> Republish "24.04.2.2 Release Notes""

data/properties/scale-downloads.yaml, data/properties/scale-releases.yaml, static/includes/SCALEUpgradePaths.md
Reverts truenas/documentation#3044
=> Republish "24.04.2.2 release followup (24.10 branch)"

data/properties/scale-downloads.yaml, data/properties/scale-releases.yaml, static/includes/SCALEUpgradePaths.md
Reverts truenas/documentation#3043
=> Republish "Port 24.04.2.2 schedule updates to master"

static/includes/iSCSIRef.md
Include a link to RFC-3722
(backport to 24.10)
=> Add IQN allowed character convention to iSCSI ref snippet (24.10)

content/CORE/CORETutorials/DirectoryServices/ActiveDirectory.md, content/CORE/CORETutorials/Storage/SED.md, content/CORE/CORETutorials/Storage/Snapshots.md, content/CORE/CORETutorials/Tasks/RunningSMARTTests.md, content/CORE/GettingStarted/Install.md, content/References/SMB.md, content/References/ZFSDeduplication.md, content/SCALE/SCALETutorials/DataProtection/CloudSyncTasks/_index.md, content/SCALE/SCALETutorials/DataProtection/CreatingVMwareSnapshots.md, content/SCALE/SCALETutorials/Storage/Disks/SEDScale.md, content/Solutions/Integrations/Containers.md, content/Solutions/Optimizations/Networking.md, content/TruenasApps/Sandboxes.md, static/includes/BrowsingSnapshotCollections1.md, static/includes/TNDataCollection.md
Removed all midclt and CLI references in the linked document (some had already been removed prior)
=> PD-1420 / 25.04 / Pd1420 remove all remaining cli related documentation from the scale tutorials

content/CORETutorials/JailsPluginsVMs/Jails/AccessingJailsUsingSSH.md, content/CORETutorials/JailsPluginsVMs/Jails/CreatingJails.md, content/CORETutorials/JailsPluginsVMs/Jails/InstallingJailSoftware.md, content/CORETutorials/JailsPluginsVMs/Jails/ManagingJails.md, content/CORETutorials/JailsPluginsVMs/Jails/SettingUpJailStorage.md, content/CORETutorials/JailsPluginsVMs/Jails/_index.md, content/CORETutorials/JailsPluginsVMs/Plugins/CreatingCustomPlugin.md, content/CORETutorials/JailsPluginsVMs/Plugins/ManagingPlugins.md, content/CORETutorials/JailsPluginsVMs/Plugins/MinIOPlugin.md, content/CORETutorials/JailsPluginsVMs/Plugins/_index.md, content/CORETutorials/JailsPluginsVMs/UpdateJailsPlugins.md, content/CORETutorials/JailsPluginsVMs/_index.md, content/UIReference/JailsPluginsVMs/Jails/JailsScreens.md, content/UIReference/JailsPluginsVMs/Jails/_index.md, content/UIReference/JailsPluginsVMs/Plugins/PluginsScreens.md, content/UIReference/JailsPluginsVMs/Plugins/_index.md, content/UIReference/JailsPluginsVMs/_index.md, static/includes/COREFeatureSupport.md
=> PD-1426 / 13.0 / Pd 1426 plugins are broken clarify 13 0 13 3 docs for free bsd eo l feature status

static/includes/COREFeatureSupport.md
=> PD-1426 / 13.3 / Pd 1426 plugins are broken clarify 13 0 13 3 docs for free bsd eo l feature

content/SCALE/SCALETutorials/Credentials/AdminRoles.md, content/SCALE/SCALETutorials/Credentials/ManageLocalGroups.md, content/SCALE/SCALETutorials/Credentials/ManageLocalUsersSCALE.md, static/includes/AddAdminGroup.md, static/includes/AddAdminUserAccount.md, static/includes/AdminAccountSecurity.md, static/includes/AdminSudo.md
=> PD-1415 / 25.04 / Pd 1415 address sudo permissions with rootless login

layouts/partials/site-header.html
=> PD-1117: Add AI-Powered Search widget to Docs Hub (Master - Backport to active branches)

data/properties/scale-releases.yaml
=> Update scale-releases.yaml (#3063) (24.10 backport)

layouts/partials/site-header.html
=> Update aisearch id for widget change

layouts/partials/site-header.html
* Update id on bot widget
---------
=> Update aisearch id for widget change (#3072)

layouts/partials/site-header.html
…to active branches) (#3059)
---------
Original PR: https://github.com/truenas/documentation/pull/3065 …
=> PD-1117 / 13.3 / Add AI-Powered Search widget to Docs Hub (Master - Backport … (by DjP-iX)

layouts/partials/site-header.html
…to active branches) (#3059)
---------
Original PR: https://github.com/truenas/documentation/pull/3065 …
=> PD-1117 / 23.10 / Add AI-Powered Search widget to Docs Hub (Master - Backport … (by DjP-iX)

layouts/partials/site-header.html
…to active branches) (#3059)
---------
Original PR: https://github.com/truenas/documentation/pull/3065 …
=> PD-1117 / 24.10 / Add AI-Powered Search widget to Docs Hub (Master - Backport … (by DjP-iX)

layouts/partials/site-header.html
…to active branches) (#3059)
---------
Original PR: https://github.com/truenas/documentation/pull/3065 …
=> PD-1117 / 3.0 / Add AI-Powered Search widget to Docs Hub (Master - Backport … (by DjP-iX)

layouts/partials/docs-nav.html
=> PD-1474 / 24.04 / PD-1474-make-version-switcher-consistent-across-branches

layouts/partials/docs-nav.html
Original PR: https://github.com/truenas/documentation/pull/3078
Jira URL: https://ixsystems.atlassian.net/browse/PD-1474
=> PD-1474 / 13.0 / PD-1474-make-version-switcher-consistent-across-branches (by DjP-iX)

layouts/partials/docs-nav.html
Original PR: https://github.com/truenas/documentation/pull/3078
Jira URL: https://ixsystems.atlassian.net/browse/PD-1474
=> PD-1474 / 13.3 / PD-1474-make-version-switcher-consistent-across-branches (by DjP-iX)

layouts/partials/docs-nav.html
Original PR: https://github.com/truenas/documentation/pull/3078
Jira URL: https://ixsystems.atlassian.net/browse/PD-1474
=> PD-1474 / 23.10 / PD-1474-make-version-switcher-consistent-across-branches (by DjP-iX)

layouts/partials/docs-nav.html
Original PR: https://github.com/truenas/documentation/pull/3078
Jira URL: https://ixsystems.atlassian.net/browse/PD-1474
=> PD-1474 / 3.0 / PD-1474-make-version-switcher-consistent-across-branches (by DjP-iX)

content/SCALE/SCALETutorials/Credentials/AdminRoles.md, content/SCALE/SCALETutorials/Credentials/ManageLocalGroups.md, content/SCALE/SCALETutorials/Credentials/ManageLocalUsersSCALE.md, static/includes/AddAdminGroup.md, static/includes/AddAdminUserAccount.md, static/includes/AdminAccountSecurity.md, static/includes/AdminSudo.md
git cherry-pick -x e685529cf2abd6cf01eb96ce3ea89dd4c34b9660
git cherry-pick -x 90c337667d1b1c661956204d33ff9ed2cba4b014
git cherry-pick -x 5b6087f6d3d854cf52aa69f7a52c91741cd5e2b7
git cherry-pick -x aabd2a3f253a89c061a25b9080eed660c5370ed7
git cherry-pick -x 8621e19c0aa5a9f36828145d0a0254f4bdb347f8
git cherry-pick -x 4a83a92b10b33fc6fbf15d257a93b06439a09535
git cherry-pick -x 00c88a1a978f80d5061a52d2aeb8f22a594db176
git cherry-pick -x 908fbbcfc09ee9cd0feb53cf5dc58275b6f1fa09
git cherry-pick -x d0d73ab6fda912b8483ef4dd03d6e206792b9dd4
git cherry-pick -x a0be3f5e4fd0ef909962100a7ce6cf38c2dd624f
git cherry-pick -x 6f1da436a919ab9b8ee846524edc81eed14a2587
git cherry-pick -x …
=> PD-1415 / 25.04 / Pd 1415 address sudo permissions with rootless login (by DjP-iX) (by bugclerk)

content/CORE/CORETutorials/JailsPluginsVMs/Plugins/MinIOPlugin.md, content/SCALE/GettingStarted/Migrate/MigratePrep.md, content/Solutions/MinioCOREtoSCALE.md, static/includes/S3Deprecation.md, words-to-ignore.txt
=> PD-1487 / 25.04 / replace minio plugin and migration content with EoL statement (master)

layouts/partials/menu-filetree.html, layouts/partials/menu.html, layouts/partials/search-form.html, layouts/partials/site-header.html
=> PD-1475 / 25.04 / Pd 1475 additional css styling for the docs bot

content/Hardware/FSeries.md
Racking process is already in User Manual
=> Remove F-Series Racking Guide

i18n/en.yaml, layouts/partials/menu.html, layouts/partials/search-form.html, layouts/partials/site-header.html
git cherry-pick -x 2d94fb234f74cd68fcc86e83146fa992b3790d76
git cherry-pick -x 976fe6288941cc9079206df61dcea77c4ddb53c4
git cherry-pick -x c65514b753bb66a16e04e5965743398bcf596b5d
git cherry-pick -x d1dc430e3ab015e19a19a0f8ae8cf84a2a483d90
git cherry-pick -x 6656ec5c26022e893959aa471ad75aa49d3fdd00
git cherry-pick -x d4f89c6802c577568a491f7db616d56dfee41341 …
=> PD-1475 / 3.0 / Pd 1475 additional css styling for the docs bot (by DjP-iX)

i18n/en.yaml, layouts/partials/menu.html, layouts/partials/search-form.html, layouts/partials/site-header.html
git cherry-pick -x 2d94fb234f74cd68fcc86e83146fa992b3790d76
git cherry-pick -x 976fe6288941cc9079206df61dcea77c4ddb53c4
git cherry-pick -x c65514b753bb66a16e04e5965743398bcf596b5d
git cherry-pick -x d1dc430e3ab015e19a19a0f8ae8cf84a2a483d90
git cherry-pick -x 6656ec5c26022e893959aa471ad75aa49d3fdd00
git cherry-pick -x d4f89c6802c577568a491f7db616d56dfee41341 …
=> PD-1475 / 24.04 / Pd 1475 additional css styling for the docs bot (by DjP-iX)

i18n/en.yaml, layouts/partials/menu.html, layouts/partials/site-header.html
git cherry-pick -x 2d94fb234f74cd68fcc86e83146fa992b3790d76
git cherry-pick -x 976fe6288941cc9079206df61dcea77c4ddb53c4
git cherry-pick -x c65514b753bb66a16e04e5965743398bcf596b5d
git cherry-pick -x d1dc430e3ab015e19a19a0f8ae8cf84a2a483d90
git cherry-pick -x 6656ec5c26022e893959aa471ad75aa49d3fdd00
git cherry-pick -x d4f89c6802c577568a491f7db616d56dfee41341 …
=> PD-1475 / 23.10 / Pd 1475 additional css styling for the docs bot (by DjP-iX)

i18n/en.yaml, layouts/partials/menu.html, layouts/partials/search-form.html, layouts/partials/site-header.html
git cherry-pick -x 2d94fb234f74cd68fcc86e83146fa992b3790d76
git cherry-pick -x 976fe6288941cc9079206df61dcea77c4ddb53c4
git cherry-pick -x c65514b753bb66a16e04e5965743398bcf596b5d
git cherry-pick -x d1dc430e3ab015e19a19a0f8ae8cf84a2a483d90
git cherry-pick -x 6656ec5c26022e893959aa471ad75aa49d3fdd00
git cherry-pick -x d4f89c6802c577568a491f7db616d56dfee41341 …
=> PD-1475 / 13.3 / Pd 1475 additional css styling for the docs bot (by DjP-iX)

content/GettingStarted/SCALEReleaseNotes.md, data/properties/scale-releases.yaml
=> Update Release notes RC.1

content/Hardware/MiniFamily.md
=> URGENT Update MiniFamily.md

layouts/partials/menu-filetree.html, layouts/partials/site-header.html
Add optional "showsearch" URI check to start the page with docs bot opened
=> Add option to show docs bot open at launch

content/GettingStarted/SCALEReleaseNotes.md, words-to-ignore.txt
=> Update SCALEReleaseNotes.md (nvidia known issue)

data/properties/scale-downloads.yaml, data/properties/scale-releases.yaml
=> PD-1506 / 25.04 / Pd 1506 follow up

content/GettingStarted/SCALEReleaseNotes.md, data/properties/scale-releases.yaml
=> Update SCALEReleaseNotes.md (date typo)

content/SCALE/GettingStarted/Migrate/SCALEZFSFlagRemoval.md
obsolete content and point to relnotes (for now).
=> Update SCALEZFSFlagRemoval.md (master)

content/GettingStarted/Migrate/SCALEZFSFlagRemoval.md
Obsolete and remove content with note to refer to release notes.
=> Update SCALEZFSFlagRemoval.md (24.04)

content/GettingStarted/Migrate/SCALEZFSFlagRemoval.md
Obsolete content and point to release notes for ZFS feature flag notes.
=> Update SCALEZFSFlagRemoval.md (24.10)

content/SCALEUIReference/TopToolbar/TasksScreens.md, static/includes/TerminateActiveRunningJob.md
Snippet created and added to TasksScreen.md
=> PD-1399 / 24.10 / PD-1399 Terminating an Active Running Job Snippet

static/includes/RootToAdminUserAccount.md
=> PD-1374 / 24.04 / updated snippet

static/includes/RESTAPIDeprecationNotice.md
Cherry-picking some Engineering feedback to master branch from 24.10.
=> Update REST API deprecations notice (master)

content/AdminGuide/Systems.md
=> Add TrueCommand note for reconnecting to system after failover

content/GettingStarted/SCALEReleaseNotes.md
=> PD-1449 / 24.04 / PD-1449-add-24.04.2.3-known-issue

content/GettingStarted/SCALEReleaseNotes.md
=> 24.10 known issue with ES24 shelves

content/SCALE/SCALETutorials/Shares/SMB/_index.md, content/SCALE/SCALEUIReference/Shares/SMBSharesScreens.md, static/includes/SMBPurposePresets.md
=> PD-1502 / None / Pd 1502 update smb share purpose presets descriptions

content/SCALEUIReference/SystemSettings/AdvancedSettingsScreen.md, static/includes/AccessSettingsWidget.md
=> PD-1509 / 24.10 / Replaced All Instances of "Token Lifetime"

content/SCALETutorials/Credentials/Certificates/CertificatesSCALE.md
=> PD-1515 / 24.10 / PD-1515 Add more depth/note requirements when making new certificates in TrueNAS

content/SCALE/SCALETutorials/Credentials/Certificates/CertificatesSCALE.md
Original PR: https://github.com/truenas/documentation/pull/3179
Jira URL: https://ixsystems.atlassian.net/browse/PD-1515
=> PD-1515 / 25.04 / PD-1515 Add more depth/note requirements when making new certificates in TrueNAS (by linzi-ix)

content/TruenasApps/StableApps/_index.md
This PR fixes the path for the snippet so the content shows in the rendered article.
=> Fix Stable Apps index.md File Snippet

content/CORETutorials/Sharing/AFPShare.md, content/UIReference/Services/AFPScreen.md
Opted for two links as there isn't much official documentation on this from Apple apart from numerous community inquiries
=> PD-1571 / 13.0 /  PD-1571-misleading-link-on-core-afs-page

content/CORETutorials/Sharing/AFPShare.md, content/UIReference/Services/AFPScreen.md
Opted for two links as there isn't much official documentation on this from Apple apart from numerous community inquiries
Original PR: https://github.com/truenas/documentation/pull/3205
Jira URL: https://ixsystems.atlassian.net/browse/PD-1571
=> PD-1571 / 13.3 /  PD-1571-misleading-link-on-core-afs-page (by linzi-ix)

layouts/partials/menu.html, layouts/partials/search-form.html
git cherry-pick -x 2fdd0bf7ae4393ef48ac84e4fe58569525da7238
git cherry-pick -x 4dc05b3b827cca3b1016184959fae34558036691
git cherry-pick -x feb28a00296652c34393d5ea39cb6c4fb12861db
git cherry-pick -x 6da312f755580ba39f3ae56bf9ab985d2bc294a1
UX improvements for the docs bot. 
-- Better sizing for mobile view
-- Adds on-window close button
Also adds a clickable button to the classic static search.
Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons …
=> PD-1594 / 13.0 / Pd 1594 polish docs bot UI for mobile friendliness (by DjP-iX)

layouts/partials/menu.html, layouts/partials/search-form.html
git cherry-pick -x 2fdd0bf7ae4393ef48ac84e4fe58569525da7238
git cherry-pick -x 4dc05b3b827cca3b1016184959fae34558036691
git cherry-pick -x feb28a00296652c34393d5ea39cb6c4fb12861db
git cherry-pick -x 6da312f755580ba39f3ae56bf9ab985d2bc294a1
UX improvements for the docs bot. 
-- Better sizing for mobile view
-- Adds on-window close button
Also adds a clickable button to the classic static search.
Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons …
=> PD-1594 / 3.0 / Pd 1594 polish docs bot UI for mobile friendliness (by DjP-iX)

layouts/partials/docs-nav.html
=> PD-1403 / 13.3 / backport version switcher change (13.3)

layouts/partials/docs-nav.html
Original PR: https://github.com/truenas/documentation/pull/3223
Jira URL: https://ixsystems.atlassian.net/browse/PD-1403
=> PD-1403 / 13.0 / backport version switcher change (by Mrt134)

layouts/partials/docs-nav.html
Original PR: https://github.com/truenas/documentation/pull/3223
Jira URL: https://ixsystems.atlassian.net/browse/PD-1403
=> PD-1403 / 23.10 / backport version switcher change (by Mrt134)

layouts/partials/docs-nav.html
Original PR: https://github.com/truenas/documentation/pull/3223
Jira URL: https://ixsystems.atlassian.net/browse/PD-1403
=> PD-1403 / 24.04 / backport version switcher change (by Mrt134)

layouts/partials/docs-nav.html
Original PR: https://github.com/truenas/documentation/pull/3223
Jira URL: https://ixsystems.atlassian.net/browse/PD-1403
=> PD-1403 / 3.0 / backport version switcher change (by Mrt134)

content/SCALETutorials/Storage/ManagePoolsScale.md
=> PD-1591 / 24.10 / PD-1591-wrong-link-on-raidz-extension-calculator

layouts/partials/menu-filetree.html
=> Fix landing page nav menu

layouts/partials/docs-nav.html
Testing apps redirection logic.
=> PD-1541 / 24.04 / PD-1541-test

layouts/partials/docs-nav.html, words-to-ignore.txt
=> PD-1541 / 24.10 / Pd 1541 update product version switcher for apps backports

layouts/partials/docs-nav.html, words-to-ignore.txt
git cherry-pick -x c580823295e8058b08dd2a4d90ae4821c538bf48
git reset --hard HEAD~3
git cherry-pick -x 32f33cbc0a93597d3b7bd51cb1fc772f1d58e1df
Original PR: https://github.com/truenas/documentation/pull/3235
=> PD-1541 / 13.0 / Pd 1541 update product version switcher for apps backports (by DjP-iX)

layouts/partials/docs-nav.html, words-to-ignore.txt
git cherry-pick -x c580823295e8058b08dd2a4d90ae4821c538bf48
git reset --hard HEAD~3
git cherry-pick -x 32f33cbc0a93597d3b7bd51cb1fc772f1d58e1df
Original PR: https://github.com/truenas/documentation/pull/3235
=> PD-1541 / 23.10 / Pd 1541 update product version switcher for apps backports (by DjP-iX)

layouts/partials/docs-nav.html, words-to-ignore.txt
git cherry-pick -x c580823295e8058b08dd2a4d90ae4821c538bf48
git reset --hard HEAD~3
git cherry-pick -x 32f33cbc0a93597d3b7bd51cb1fc772f1d58e1df
Original PR: https://github.com/truenas/documentation/pull/3235
=> PD-1541 / 3.0 / Pd 1541 update product version switcher for apps backports (by DjP-iX)

layouts/partials/docs-nav.html
=> PD-1541 / 24.04 / Pd 1541 test

content/GettingStarted/Configure/SetUpSharing.md, content/SCALETutorials/Shares/AFPMigration.md, content/SCALETutorials/Shares/AddingNFSShares.md, content/SCALETutorials/Shares/MixedModeShares.md, content/SCALETutorials/Shares/SMB/AddSMBHomeShare.md, content/SCALETutorials/Shares/SMB/AddSMBShadowCopies.md, content/SCALETutorials/Shares/SMB/ManageSMBShares.md, content/SCALETutorials/Shares/SMB/SMBMultichannel.md, content/SCALETutorials/Shares/SMB/SetUpBasicTimeMachineSMBShare.md, content/SCALETutorials/Shares/SMB/_index.md, content/SCALETutorials/Shares/_index.md, layouts/partials/docs-nav.html, static/includes/RootLevelDatasetShareWarning.md
git cherry-pick -x 491d30410a7b4838954839a853fda9edc66ac427
git cherry-pick -x 3dd1329bc36db8b1bbeb298b4c5d0882a98f37fb
git cherry-pick -x d5cded3395da3fd4f902f61f9d013a6e40c3416f
git cherry-pick -x 41b43f7698f4a35b9d35aab03e3da6e1c727e860
git cherry-pick -x 1290dfce9859127af9a01bcfaa9851fc6d71842a
git cherry-pick -x 39f0e27caa8878c89201dcc4d38970db8a6fdf29
git cherry-pick -x b0f03575544bc1492da42143ab81c22f48d6ea23
git cherry-pick -x fe6c275c35c7a47972f972ea6722bc1a96424ee4
This PR creates a snippet with a warning admonition about not sharing the root/pool-level dataset, and adds it to …
=> PD-1499 / 24.04 / Pd 1499 create do not create root dataset share warning (by micjohnson777)

layouts/partials/docs-nav.html
Fixes an issue with migrating from CORE to SCALE versions within the new combined TrueNAS selections
Original PR: https://github.com/truenas/documentation/pull/3247
=> PD-1541 / 13.0 / PD-1541-Update-Product/Version-Switcher-for-apps (by DjP-iX)

layouts/partials/docs-nav.html
Fixes an issue with migrating from CORE to SCALE versions within the new combined TrueNAS selections
Original PR: https://github.com/truenas/documentation/pull/3247
=> PD-1541 / 13.3 / PD-1541-Update-Product/Version-Switcher-for-apps (by DjP-iX)

layouts/partials/docs-nav.html
Fixes an issue with migrating from CORE to SCALE versions within the new combined TrueNAS selections
Original PR: https://github.com/truenas/documentation/pull/3247
=> PD-1541 / 23.10 / PD-1541-Update-Product/Version-Switcher-for-apps (by DjP-iX)

layouts/partials/docs-nav.html
Fixes an issue with migrating from CORE to SCALE versions within the new combined TrueNAS selections
Original PR: https://github.com/truenas/documentation/pull/3247
=> PD-1541 / 3.0 / PD-1541-Update-Product/Version-Switcher-for-apps (by DjP-iX)

content/404Error.md, layouts/partials/head/custom.html
=> PD-1543 / 25.04 / Pd 1543 docs hub 404 page is returning a 200 code

content/References/SMB.md, words-to-ignore.txt
=> Add max file size for SMB write to SMB Reference article

layouts/partials/head/custom.html
git cherry-pick -x 1715a86e961f34925394fd76f784dbc71b971f7b
=> PD-1543 / 13.0 / Pd 1543 docs hub 404 page is returning a 200 code (by DjP-iX)

layouts/partials/head/custom.html
=> PD-1543 / 13.3 / Pd 1543 docs hub 404 page is returning a 200 code (by DjP-iX)

content/404Error.md, layouts/partials/head/custom.html
git cherry-pick -x 1715a86e961f34925394fd76f784dbc71b971f7b
=> PD-1543 / 23.10 / Pd 1543 docs hub 404 page is returning a 200 code (by DjP-iX)

layouts/partials/head/custom.html
git cherry-pick -x 1715a86e961f34925394fd76f784dbc71b971f7b
=> PD-1543 / 24.04 / Pd 1543 docs hub 404 page is returning a 200 code (by DjP-iX)

layouts/partials/head/custom.html
git cherry-pick -x 1715a86e961f34925394fd76f784dbc71b971f7b
=> PD-1543 / 3.0 / Pd 1543 docs hub 404 page is returning a 200 code (by DjP-iX)

content/GettingStarted/COREReleaseNotes.md
=> Update 13.3 ReleaseNotes - quick resync with general announcement

content/GettingStarted/COREReleaseNotes.md
=> Update 13.0-U6.3 ReleaseNotes.md - Quick resync with general announcement

content/UIReference/System/Certificates.md
Created binding certificate snippet 
=> PD-1521 / 13.0 / Update Certificates.md

content/GettingStarted/SCALEReleaseNotes.md
=> SED known issue for 24.10

layouts/partials/menu-filetree.html
verified showsearch is still functional
=> (docsbot) Remove obsolete URI check

content/SCALE/SCALETutorials/Shares/SMB/_index.md
Feel free to wordsmith further.
=> Update SMB mount on Apple expand with link to Apple tuning doc

content/SCALETutorials/Network/SettingUpIPMI.md, content/SCALEUIReference/Network/IPMIScreens.md, static/includes/IPMICompatibility.md
Original PR: https://github.com/truenas/documentation/pull/3253
Jira URL: https://ixsystems.atlassian.net/browse/PD-1572
=> PD-1572 / 24.10 / Pd 1572 review ipmi configuration tutorial (by DjP-iX)

content/UIReference/System/Certificates.md
git cherry-pick -x 0ffc1d2d6e326c1991e717a16a4698c9852041a3
git cherry-pick -x bfdc5244a65388e0cc71dfe30dc608ffa4c8a1f0
git cherry-pick -x 0074c0cfe3f37f36fcb06ab99ac80854b72df05a
git cherry-pick -x cf7df10517a817882416750388de3da787ac1e44
Created binding certificate snippet 
Original PR: https://github.com/truenas/documentation/pull/3284
Jira URL: …
=> PD-1521 / 13.3 / Update Certificates.md (by linzi-ix)

layouts/partials/menu.html, layouts/partials/search-form.html
=> Clean up pagefind call and obsolete docsbot script (13.0)

layouts/partials/docs-nav.html
=> PD-1455 / 24.10 / PD-1455-backport-typo-fix

layouts/partials/menu.html, layouts/partials/search-form.html
=> Clean up pagefind call and obsolete docsbot script (13.3)

layouts/partials/menu-filetree.html, layouts/partials/search-form.html
=> Pagefind docsbot code cleanup 24.10

layouts/partials/menu.html, layouts/partials/search-form.html
=> Clean up pagefind and docs bot code a bit (3.0)

layouts/partials/docs-nav.html
=> PD-1455 / 13.0 / PD-1455-backport-typo-fix (by DjP-iX)

layouts/partials/docs-nav.html
=> PD-1455 / 23.10 / PD-1455-backport-typo-fix (by DjP-iX)

layouts/partials/docs-nav.html
=> PD-1455 / 13.3 / PD-1455-backport-typo-fix (by DjP-iX)

layouts/partials/docs-nav.html
=> PD-1455 / 24.04 / PD-1455-backport-typo-fix (by DjP-iX)

layouts/partials/docs-nav.html
=> PD-1455 / 3.0 / PD-1455-backport-typo-fix (by DjP-iX)

static/api/core_rest_api.html, static/api/scale_rest_api.html, static/api/tc_rest_api.html
=> Add missing titles to api html files

static/api/scale_rest_api.html
=> Update scale_rest_api.html (23.10)

static/api/core_rest_api.html, static/api/scale_rest_api.html, static/api/tc2api.html
=> Add missing titles to api html files (13.0)

layouts/_default/baseof.print.html
=> Update baseof.print.html (13.0)

content/GettingStarted/SCALEReleaseNotes.md
=> Update SCALEReleaseNotes.md (24.04)

content/References/SMB.md
=> PD-1635 / 25.04 / PD-1635-update-master-branch-reference-smb-max-file-size-note-for-24-10-1-change

content/GettingStarted/SCALEReleaseNotes.md, data/properties/scale-releases.yaml, static/api/scale_rest_api.html, static/includes/SCALEUpgradePaths.md, words-to-ignore.txt
Original PR: https://github.com/truenas/documentation/pull/3333
Jira URL: https://ixsystems.atlassian.net/browse/PD-1634
=> PD-1634 / dev1 / Pd 1634 24 10 1 docs (by DjP-iX)

content/SCALE/GettingStarted/SCALEReleaseNotes.md, content/SCALE/SCALEUIReference/Credentials/LocalUsersScreensSCALE.md, content/SCALE/SCALEUIReference/DataProtection/CloudSyncTasksScreensSCALE.md, content/TruenasApps/StableApps/InstallNextCloudMedia.md, content/TruenasApps/StableApps/MinIOApp/MinIOClustering.md
=> Address some errors found in site audit (master branch)

static/custom.css
=> PD-1656 / 13.3 / update dark mode text color (by Mrt134)

static/custom.css
=> PD-1656 / 24.04 / update dark mode text color (by Mrt134)

static/custom.css
=> PD-1656 / 3.0 / update dark mode text color (by Mrt134)

static/custom.css
git cherry-pick -x 906b15160a95832fbdf6e2616c99eb6526610245
git cherry-pick -x ffe3350c9472fb7c77cd618fac122a996237ec69
=> PD-1656 / 23.10 / update dark mode text color (by Mrt134)

static/custom.css
git cherry-pick -x 906b15160a95832fbdf6e2616c99eb6526610245
git cherry-pick -x ffe3350c9472fb7c77cd618fac122a996237ec69
=> PD-1656 / 13.0 / update dark mode text color (by Mrt134)

content/GettingStarted/COREReleaseNotes.md
=> 13.0-U6.4 relnotes

data/properties/core-downloads.yaml, data/properties/core-releases.yaml, static/includes/COREUpgradePaths.md, static/includes/SCALEUpgradePaths.md
=> 13.0-U6.4 release notes followup (master)

content/GettingStarted/SCALEReleaseNotes.md
=> Add additional 24.10.1 note about change to CPU widgets

content/References/dRAIDprimer.md
=> Update dRAIDprimer.md - typo

content/SCALE/GettingStarted/Migrate/_index.md
=> Update _index.md (test alias removal)

content/GettingStarted/SCALEReleaseNotes.md, words-to-ignore.txt
- fix restricted zfs properties on boot pool
- sendmail removal (security)
=> Elevate two changelog items to 24.10.1 release notes

content/CORETutorials/SystemConfiguration/SettingtheSystemDataset.md
=> PD-1624 / 13.0 / changes made

content/CORETutorials/SystemConfiguration/SettingtheSystemDataset.md
=> PD-1624 / 25.04 / Pd 1624 change system dataset needs additional info

content/GettingStarted/SCALEReleaseNotes.md
=> Update SCALEReleaseNotes.md - CPU widget known issue

content/SCALE/GettingStarted/Migrate/MigrateCOREHAtoSCALEHA.md, content/TruenasApps/Sandboxes.md, content/TruenasApps/StableApps/InstallNetdataApp.md
=> (master) Additional site audit cleanups

static/includes/COREFeatureSupport.md
=> Update COREFeatureSupport.md snippet

content/GettingStarted/Install/InstallEnterpriseHASCALE.md
Last site test caught this - trivial fix
=> Fix image call typo

content/SCALETutorials/Datasets/DatasetsSCALE.md, content/SCALETutorials/Datasets/EncryptionSCALE.md, content/SCALETutorials/Storage/CreatePoolWizard.md, content/SCALETutorials/SystemSettings/Advanced/_index.md, content/SCALEUIReference/Datasets/EncryptionUISCALE.md, content/SCALEUIReference/Datasets/ZvolsScreensScale.md, content/SCALEUIReference/Datasets/_index.md, content/SCALEUIReference/Storage/PoolCreateWizardScreens.md, static/includes/CreatePool.md, static/includes/EncryptionRootLevel.md, static/includes/EncryptionWarning.md
git cherry-pick -x 8b7d37ed836a8cdadcac07e584ea43368cf8d4c9
git cherry-pick -x d3055a2a108ae5f4971fbec325acbd7a907986fe
git cherry-pick -x 305f6040676f0d3f45d1e85b19574db4248da943
git cherry-pick -x 63e83cfc78cb925de4ecd2c69d30951adde4ed11
git cherry-pick -x 8ff8229c22e9045d7381abd1ad865ebc5f699962
git cherry-pick -x 5d6b75f5ff2ae8ed12a5db0dae1f95f297b9fe0e
git cherry-pick -x 154f1bb4fbb231164bc53e94ad9de5cfd5cda9df
git cherry-pick -x 52b3dd9151bd7fab96264b56545d5b406b67cdc2
git cherry-pick -x 739ed1279c3324855d51ffcb0d56eaf33227dbee
git cherry-pick -x 1c676dd69d0192a16a619dd55b546b9aae39fe44
git cherry-pick -x 6c36e8e6c2b12974dad5f80fb606086a5ab79c98
git cherry-pick -x 5745a8cac32fade59f46647dacbda75f40d540c7
git …
=> PD-1648 / 24.10 / Pd 1648 update encryption documentation (by DjP-iX)

content/GettingStarted/SCALEReleaseNotes.md, words-to-ignore.txt
=> Add nvidia plex passthru known issue (24.10.1)

static/includes/COREMigratesList.md
git cherry-pick -x 75a8eeab57eb294eaa22b9f97923728fdadd745c
git cherry-pick -x de9b630b179ba267624b0d064b9004b3d42d9c60
git cherry-pick -x aac9c0c0715ddf4ea84f2b03a27341db03397192
git cherry-pick -x 78ef5f1102decccf90f76855f0f7591a3ecc308f
git cherry-pick -x ee3a8dbfbeca6ddb8fa2fed41b66a3a19530f526
Original PR: https://github.com/truenas/documentation/pull/3427 …
=> PD-1651 / 23.10 / PD-1651-update-vm-migration (by linzi-ix)

static/includes/COREMigratesList.md
git cherry-pick -x 75a8eeab57eb294eaa22b9f97923728fdadd745c
git cherry-pick -x de9b630b179ba267624b0d064b9004b3d42d9c60
git cherry-pick -x aac9c0c0715ddf4ea84f2b03a27341db03397192
git cherry-pick -x 78ef5f1102decccf90f76855f0f7591a3ecc308f
git cherry-pick -x ee3a8dbfbeca6ddb8fa2fed41b66a3a19530f526
Original PR: https://github.com/truenas/documentation/pull/3427 …
=> PD-1651 / 22.12 / PD-1651-update-vm-migration (by linzi-ix)

content/TruenasApps/CommunityApps/nginx-proxy-manager.md
Found a couple of other trivial changes to do.
=> Quick followup on nginx-proxy-manager.md

content/SCALE/GettingStarted/Configure/VMandAppConfigSCALE.md, content/SCALE/GettingStarted/SCALEReleaseNotes.md, content/SCALE/SCALETutorials/Virtualization/AddManageVMDevicesSCALE.md, content/SCALE/SCALETutorials/Virtualization/_index.md, content/SCALE/SCALEUIReference/VirtualizationScreens.md, static/includes/25.04FeatureList.md, static/includes/25.04Virtualization.md, static/includes/Incus.md, static/includes/MigratingVMs.md
=> PD-1602 / 25.04 / Pd 1602 community container vm experimental feature documentation

content/SCALETutorials/Network/ConfigureIPv6.md
=> PD-1745-implementing-i-pv-6-link-in-first-paragraph-is-broken-404

content/GettingStarted/COREReleaseNotes.md
These are draft release notes and other small doc updates for the impending 13.0-U6.6 release.
=> 13.0-U6.6 release notes

content/_index.md
=> PD-1749-nighly-nightly

content/SCALE/SCALETutorials/DataProtection/TrueCloudTasks.md
=> PD-1747-true-cloud-25-04-typo

static/includes/SoftwareStatusPage.md, static/includes/TNHardwareGuide.md
git cherry-pick -x c49e6197bc7518b2b0ca5a418dc60e83f3bc24d2
git cherry-pick -x 1abf2800c113eff36978bd0234b6d5e87b3a5c29
git cherry-pick -x 89a2b01c5481f7fd6ce448dc03f276dfcb41e9fd
git cherry-pick -x c05e8c64b55104a855aa06611d79c1309741df9d
Original PR: https://github.com/truenas/documentation/pull/3460
Jira URL: https://ixsystems.atlassian.net/browse/PD-1684
=> PD-1684 / 13.0 / PD-1684-hardware-guide-should-warn-about-smr-drives (by DjP-iX)

static/includes/TNHardwareGuide.md
git cherry-pick -x 1abf2800c113eff36978bd0234b6d5e87b3a5c29
git cherry-pick -x 89a2b01c5481f7fd6ce448dc03f276dfcb41e9fd
git cherry-pick -x c05e8c64b55104a855aa06611d79c1309741df9d
Original PR: https://github.com/truenas/documentation/pull/3460
Jira URL: https://ixsystems.atlassian.net/browse/PD-1684
=> PD-1684 / 13.3 / PD-1684-hardware-guide-should-warn-about-smr-drives (by DjP-iX)

static/includes/TNHardwareGuide.md
Original PR: https://github.com/truenas/documentation/pull/3460
Jira URL: https://ixsystems.atlassian.net/browse/PD-1684
=> PD-1684 / 24.10 / PD-1684-hardware-guide-should-warn-about-smr-drives (by DjP-iX)

content/GettingStarted/COREReleaseNotes.md
Quick turnaround release to grab another change to upstream rsync.
=> 13.0-U6.7 release notes

content/SCALE/SCALETutorials/Datasets/PermissionsSCALE.md
Removed a sentence that has been repeated in just a slightly different way.
=> Remove duplicate text

data/properties/core-downloads.yaml, data/properties/core-releases.yaml, static/includes/COREUpgradePaths.md
=> Add 13.0-U6.6 and 13.0-U6.7 to 13.3 branch data files

data/properties/core-downloads.yaml, data/properties/core-releases.yaml, static/includes/COREUpgradePaths.md
=> Update releases info for 13.3-U1.1

content/SCALE/SCALETutorials/SystemSettings/Advanced/ManageCronJobsSCALE.md, content/SCALE/SCALEUIReference/SystemSettings/AdvancedSettingsScreen.md, content/Solutions/Optimizations/Security.md, static/includes/CustomScriptWarning.md
=> PD-1771 / 25.04 / PD-1771-document-security-concern-for-users-with-custom-scripts

content/GettingStarted/SCALEReleaseNotes.md
=> NAS-133983: update 24.10 relnotes terminology

content/GettingStarted/SCALEReleaseNotes.md
=> NAS-133983: relnotes headers rework (23.10)

data/menu/more.yml
backporting improvements from 25.04 branch
=> 24.10 - Update more.yml

content/GettingStarted/SCALEReleaseNotes.md, data/properties/component_versions.yaml, layouts/shortcodes/component-versions.html, static/custom.css
=> Component versions redesign

content/SCALE/_index.md
=> PD-1606 / 25.10 / Update _index.md

layouts/partials/docs-nav.html
=> PD-1606 / 24.10 / PD-1606-backport-navigation

layouts/partials/docs-nav.html
=> PD-1606 / 13.0 / PD-1606-backport-navigation (by DjP-iX)

layouts/partials/docs-nav.html
=> PD-1606 / 13.3 / PD-1606-backport-navigation (by DjP-iX)

layouts/partials/docs-nav.html
=> PD-1606 / 23.10 / PD-1606-backport-navigation (by DjP-iX)

layouts/partials/docs-nav.html
=> PD-1606 / 24.04 / PD-1606-backport-navigation (by DjP-iX)

layouts/partials/docs-nav.html
=> PD-1606 / 3.0 / PD-1606-backport-navigation (by DjP-iX)

static/includes/TNDataCollection.md
Reinserts command to check data collection that had been previously scrubbed. 
=> PD-1744 / 25.10 / Update TNDataCollection.md

static/includes/TNDataCollection.md
Reinserts command to check data collection that had been previously scrubbed. 
Original PR: https://github.com/truenas/documentation/pull/3511
Jira URL: https://ixsystems.atlassian.net/browse/PD-1744
=> PD-1744 / 25.04 / Update TNDataCollection.md (by DjP-iX)

content/_index.md, i18n/en.yaml, layouts/partials/docs-nav.html, layouts/partials/page-header.html, static/includes/23.10FeatureList.md
=> Rework 23.10 header for archival

layouts/partials/docs-nav.html
=> Remove archived 23.10 docs links from the version selector (25.04)

layouts/partials/docs-nav.html
When this is ready, backport this change to all other active branches.
=> Remove archived 23.10 docs links from the version selector (3.0)

layouts/partials/docs-nav.html
When this is ready, backport this change to all other active branches.
=> Remove archived 23.10 docs links from the version selector (13.0)

layouts/partials/docs-nav.html
When this is ready, backport this change to all other active branches.
=> Remove archived 23.10 docs links from the version selector (13.3)

layouts/partials/docs-nav.html
When this is ready, backport this change to all other active branches.
=> Remove archived 23.10 docs links from the version selector (24.10)

content/TCGettingStarted/TCReleaseNotes.md
=> Update TCReleaseNotes.md (compatible versions)

content/GettingStarted/SCALEReleaseNotes.md, static/includes/25.04FeatureList.md
This feature does not have a lot of end-user visibility, so after discussions with engineering, we settled on just clarifying the feature wording somewhat. 
=> PD-814 / 25.04 / PD-814-zfs-block-cloning-with-i-scsi-review

content/UserGuide/SystemManagement/_index.md
=> Add experimental notice to NAS users and groups descriptor in TC 3.0 docs

content/SCALE/GettingStarted/Configure/SetUpSharing.md, content/SCALE/SCALETutorials/Credentials/ManageLocalGroups.md, content/SCALE/SCALETutorials/Shares/SMB/_index.md
=> PD-1805 / 25.10 / samba auth rename (master)

content/GettingStarted/Configure/SetUpSharing.md, content/SCALETutorials/Credentials/ManageLocalGroups.md, content/SCALETutorials/Shares/SMB/_index.md
=> PD-1805 / 25.04 / samba authentication rename (25.04)

content/TruenasApps/StableApps/nextcloud.md
Updated a few typos I noticed while following the documentation to install Nextcloud.
=> Update nextcloud.md typos

content/TruenasApps/CommunityApps/tailscale.md
+ how to connect to custom headscale server
+ how to advertise as exit node
=> Added instructions to connect to headscale server

content/SCALETutorials/DataProtection/TrueCloudTasks.md
Approved by SME (Logan Cary) on 03/03/25
=> PD-1695 / 25.04 / PD-1695-clarify-true-cloud-password-encryption

content/SCALE/SCALETutorials/SystemSettings/Advanced/ManageGlobal2FASCALE.md, static/includes/BasicReplicationProcess.md
Changes ported from 24.10 proposed changes.
=> PD-1792 / 25.10 / port ssh password updates to master/25.10

content/SCALETutorials/SystemSettings/Advanced/ManageGlobal2FASCALE.md, static/includes/BasicReplicationProcess.md
Quick port from the 24.10 proposed changes.
=> PD-1792 / 25.04 / update ssh password text (25.04)

content/SCALE/SCALETutorials/SystemSettings/Advanced/DeveloperMode.md
=> PD-1687 / 25.10 / Update DeveloperMode.md

content/SCALETutorials/SystemSettings/Advanced/DeveloperMode.md
Original PR: https://github.com/truenas/documentation/pull/3568
Jira URL: https://ixsystems.atlassian.net/browse/PD-1687
=> PD-1687 / 25.04 / Update DeveloperMode.md (by DjP-iX)

content/UserGuide/Alerts/AlertManage.md
This PR updates the SMTP email configuration information with the troubleshooting tips in the PD ticket.
=> PD-1791 / 3.0 / PD-1791 Update TC SMTP Configuration Information

content/SCALETutorials/Apps/_index.md, content/SCALEUIReference/Apps/_index.md, static/custom.css, static/includes/AppsHostIP.md, static/includes/AppsSupportTimeline.md, words-to-ignore.txt
=> D 1817 24.04 message kubernetes migration and 24 10 apps update cutoff

content/GettingStarted/SCALEReleaseNotes.md, static/includes/MigratingVMs.md, static/includes/UpgradeNotesBoilerplate.md
The VM migration process has been simplified somewhat since BETA.1. This captures those changes.
Also includes a typo fix and removes a Notable change to avoid confusion
=> Release note clarifications 

content/GettingStarted/SCALEReleaseNotes.md, content/SCALEUIReference/Apps/_index.md, static/custom.css, static/includes/AppsHostIP.md, static/includes/AppsSupportTimeline.md, static/includes/UpgradeNotesBoilerplate.md, words-to-ignore.txt
=> D 1817 24.10 message kubernetes migration and 24 10 apps update cutoff

layouts/partials/docs-nav.html
=> Update docs-nav.html 25.04

layouts/partials/docs-nav.html
=> Update docs-nav.html 24.04

layouts/partials/docs-nav.html
=> Update docs-nav.html 13.0

static/includes/IncusExperimental.md, static/includes/InstanceWarning.md
ports https://github.com/truenas/documentation/pull/3602
=> Add cli warning master

content/TruenasApps/CommunityApps/mealie.md
=> docs: Provide basic configuration information for Mealie

layouts/partials/docs-nav.html
git cherry-pick -x e00f145d924531f3d4bc66dec2fd5ed8127dd109
git cherry-pick -x 7c4a05b3867f96b85b4daa4357b134625fe77417
git cherry-pick -x 348074eb9d2d3c31dec62b63c6b717e318f3d3a2
git cherry-pick -x 32ab47fd1cc36022f978d89f5572cdf3f073bee0
…eeded)
Jira URL: …
=> PD-1825 / 13.0 / add small groupings to TrueNAS version selector (backports n… (by Mrt134)

layouts/partials/docs-nav.html
git cherry-pick -x e00f145d924531f3d4bc66dec2fd5ed8127dd109
git cherry-pick -x 7c4a05b3867f96b85b4daa4357b134625fe77417
git cherry-pick -x 348074eb9d2d3c31dec62b63c6b717e318f3d3a2
git cherry-pick -x 32ab47fd1cc36022f978d89f5572cdf3f073bee0
…eeded)
Jira URL: …
=> PD-1825 / 13.3 / add small groupings to TrueNAS version selector (backports n… (by Mrt134)

layouts/partials/docs-nav.html
git cherry-pick -x e00f145d924531f3d4bc66dec2fd5ed8127dd109
git cherry-pick -x 7c4a05b3867f96b85b4daa4357b134625fe77417
git cherry-pick -x 348074eb9d2d3c31dec62b63c6b717e318f3d3a2
git cherry-pick -x 32ab47fd1cc36022f978d89f5572cdf3f073bee0
…eeded)
Jira URL: …
=> PD-1825 / 24.04 / add small groupings to TrueNAS version selector (backports n… (by Mrt134)

layouts/partials/docs-nav.html, static/custom.css
…eeded)
Jira URL: https://ixsystems.atlassian.net/browse/PD-1825
=> PD-1825 / 25.04 / add small groupings to TrueNAS version selector (backports n… (by Mrt134)

layouts/partials/docs-nav.html
git cherry-pick -x e00f145d924531f3d4bc66dec2fd5ed8127dd109
git cherry-pick -x 7c4a05b3867f96b85b4daa4357b134625fe77417
git cherry-pick -x 348074eb9d2d3c31dec62b63c6b717e318f3d3a2
git cherry-pick -x 32ab47fd1cc36022f978d89f5572cdf3f073bee0
…eeded)
Jira URL: …
=> PD-1825 / 3.0 / add small groupings to TrueNAS version selector (backports n… (by Mrt134)

content/SCALETutorials/Credentials/DirectoryServices/ConfigLDAPSCALE.md
=> PD-1686 / 25.04 / PD-1686-review-ldap-config-instructions-for-additional-cautions

config.toml
increasing timeout value as part of a check
=> Update config.toml (timeout)

static/includes/SCALEAdvancedScheduler.md
=> PD-1697 / 25.04 / PD-1697-fix-smart-tests-advanced-scheduler-docs

content/SCALETutorials/Storage/Disks/ReplacingDisks.md
Original PR: https://github.com/truenas/documentation/pull/3652
Jira URL: https://ixsystems.atlassian.net/browse/PD-1667
=> PD-1667 / 24.10 / PD-1667-investigate-and-document-disk-replacement-procedure-for-non-hotswappable-systems (by linzi-ix)

static/includes/SCALEAdvancedScheduler.md
Original PR: https://github.com/truenas/documentation/pull/3661
Jira URL: https://ixsystems.atlassian.net/browse/PD-1697
=> PD-1697 / 24.10 / PD-1697-fix-smart-tests-advanced-scheduler-docs (by linzi-ix)

content/_index.md
Adds a quick radius to better match other page elements in dark mode
=> Minor styling improvement for docsbot embed

content/GettingStarted/SCALEReleaseNotes.md, data/properties/scale-downloads.yaml, data/properties/scale-releases.yaml
=> PD-1868 / 24.10 / PD-1868 - 24.10.2.1 release docs

content/UserGuide/ReplicationManagement.md, static/includes/TCCloudConnectSystems.md
Couple of broken images and malformed links in the 3.0 docs.
=> Fix up some errors caught by ahrefs testing (TC 3.0 branch)

content/SCALETutorials/ConfigReportsScale.md, static/includes/NetdataUI.md, static/includes/netdatareporting.md
=> PD-1872 / 24.10 / Pd 1872 review reporting content for obsolete netdata references

static/includes/COREFeatureSupport.md
=> PD-1827 / 13.0 / PD-1827-improve-core-virtualization-messaging

static/includes/COREFeatureSupport.md
git cherry-pick -x 7ad4861a796a7a3ef578be499e70e7800886e19f
git cherry-pick -x 0043a2f8046f187d3694d865aabedbfaae807445
git cherry-pick -x bf0b0139293ae11d2326f390d0842cee705a4742
Original PR: https://github.com/truenas/documentation/pull/3675
Jira URL: https://ixsystems.atlassian.net/browse/PD-1827
=> PD-1827 / 13.3 / PD-1827-improve-core-virtualization-messaging (by linzi-ix)

layouts/partials/docs-nav.html
=> PD-1848 / 24.10 / Pd 1848 follow up navigation

layouts/partials/docs-nav.html
Original PR: https://github.com/truenas/documentation/pull/3690
Jira URL: https://ixsystems.atlassian.net/browse/PD-1848
=> PD-1848 / 13.0 / Pd 1848 follow up navigation (by DjP-iX)

layouts/partials/docs-nav.html
Original PR: https://github.com/truenas/documentation/pull/3690
Jira URL: https://ixsystems.atlassian.net/browse/PD-1848
=> PD-1848 / 24.04 / Pd 1848 follow up navigation (by DjP-iX)

layouts/partials/docs-nav.html
Original PR: https://github.com/truenas/documentation/pull/3690
Jira URL: https://ixsystems.atlassian.net/browse/PD-1848
=> PD-1848 / 3.0 / Pd 1848 follow up navigation (by DjP-iX)

content/GettingStarted/SCALEReleaseNotes.md
=> Add notice about updater issue to 25.04.0 relnotes

content/GettingStarted/SCALEReleaseNotes.md
=> (25.04.0) Remove republish notice as it is no longer relevant

content/SCALETutorials/Credentials/ManageLocalGroups.md, static/includes/ConfigureAccessSettings.md
=> Pd 1862 typo fix

content/GettingStarted/Install/InstallingSCALE.md
git cherry-pick -x 6a6eecc447b36e4b8e9df24311d1950da09ff589
git cherry-pick -x 0956e88e5c0b9f813eeaa72bf460d29d1fff3445
git cherry-pick -x 1d00010ae2bfe8089faa47123c0eb6ff5e75dbd7
Original PR: https://github.com/truenas/documentation/pull/3702
Jira URL: https://ixsystems.atlassian.net/browse/PD-1708
=> PD-1708 / 24.10 / PD-1708-windows-users-verifying-sha-256-checksums-natively (by linzi-ix)

content/SCALE/SCALETutorials/Shares/MixedModeShares.md, content/SCALE/SCALETutorials/Shares/SMB/SetUpBasicTimeMachineSMBShare.md, static/includes/TimeMachineMultiprotocol.md
=> Add time machine/multiprotocol advisory 25.10

content/GettingStarted/SCALEReleaseNotes.md
=> 25.04.0 Escalate known issue with previous instance pool import

static/includes/AppsHostIP.md, static/includes/AppsSupportTimeline.md
Re-reviewed with latest development strategy and updating this notice accordingly.
=> Clarify some of the Apps port binding changes and disruptiveness

static/includes/AppsHostIP.md, static/includes/AppsSupportTimeline.md
=> Clarify App Timelines

static/includes/AppsHostIP.md, static/includes/AppsSupportTimeline.md
Backports https://github.com/truenas/documentation/pull/3719
=> Clarify app timelines 24.10

content/GettingStarted/Install/InstallingSCALE.md, content/SCALETutorials/SystemSettings/General/ManageSysConfigSCALE.md, content/SCALETutorials/SystemSettings/UpdateHASCALE.md, content/SCALETutorials/SystemSettings/UpdateSCALE.md, content/SCALEUIReference/SystemSettings/UpdateScreensSCALE.md, static/includes/DownloadSystemConfigFileSCALE.md, static/includes/SecretSeed.md
git cherry-pick -x 8c33c98343d1d20d3e3c0f1338f6808a68340f2b
git cherry-pick -x 614403aecd90b3f1dba1ab3f9b1ac0f92c54e684
git cherry-pick -x bda68380e400cbf26c95abfba206500c8d516a91
git cherry-pick -x 6a5f16d5ce9e3a0169ad935b3f9e27b2c88776a3
git cherry-pick -x 55f8340cd63488cb6483409fb760feceb0b43b97
git cherry-pick -x 4e75de1d2a546b2484485db48840469a33b5fe5a
git cherry-pick -x 49651b34b338a3aeceebc90cffd7b4a33382fe0a
git cherry-pick -x 86c802307cb2897ee3b3d95c9b6a2fafb1935a5b
git cherry-pick -x b87e6518c3977ba94ece912b316e279c993162ba
git cherry-pick -x 5b366475e695e919595c045b78a045883453d30d
git cherry-pick -x dac1bf2dfd6e0ad38b5b676e56519e13788bd3fc
If the original PR was merged via a squash, you …
=> PD-1683 / 24.10 / Pd 1683 update config file secret seed content (by micjohnson777)

content/SCALEUIReference/ReportingScreensSCALE.md, words-to-ignore.txt
git cherry-pick -x 1ca82e42183be4ddb6fbc8eb306e6f01e3e451f7
git cherry-pick -x e07d483f67568d0cf6646115189c3350cb492cb6
git cherry-pick -x 243b022575d9bd340193066e98a628d08df89534
git cherry-pick -x 0f0486ce802ced7198db7ba9ea3bc75afaa428bf
git cherry-pick -x 99ac9c0a879414906ea4bf7b6f5b622f6d33d694
git cherry-pick -x 65dfc5ecdc494fd0a06887d1589059e5baaba156
git cherry-pick -x 2a464e00297fc41185c728c69e42f1a573a22794
git cherry-pick -x 501810b962cbc9106d833ea70c804d001e1f09e5
git cherry-pick -x 69e9d9e355427e379222aa11c9546d63cdbf1ddb
git cherry-pick -x 2312a410fcb0d51bdb11e537938573b58671e53e
git cherry-pick -x …
=> PD-1860 / 25.04 / PD-1860 Update Reporting UI Ref (by micjohnson777)

content/SCALETutorials/Shares/AddingNFSShares.md, content/SCALEUIReference/Shares/NFSSharesScreens.md
=> PD-1724 / 25.04 / PD-1724-review-nfs-maproot-descriptions

content/Hardware/FSeries.md
=> PD-1855-update-stencil-pack-f-series

layouts/search/list.html
=> PD-1876 / 25.10 / PD-1876-docs-search-weirdness

layouts/search/list.html
=> PD-1876 / 13.0 / PD-1876-docs-search-weirdness (by DjP-iX)

layouts/search/list.html
=> PD-1876 / 3.0 / PD-1876-docs-search-weirdness (by DjP-iX)

layouts/search/list.html
=> PD-1876 / 24.10 / PD-1876-docs-search-weirdness (by DjP-iX)

layouts/search/list.html
=> PD-1876 / 24.04 / PD-1876-docs-search-weirdness (by DjP-iX)

layouts/search/list.html
=> PD-1876 / 13.3 / PD-1876-docs-search-weirdness (by DjP-iX)

content/GettingStarted/COREReleaseNotes.md, content/_index.md, data/properties/core-downloads.yaml, data/properties/core-releases.yaml, layouts/partials/page-header.html, static/includes/13.3FinalRelease.md, static/includes/COREUpgradePaths.md, words-to-ignore.txt
=> 13.3-U1.2 release notes

content/SCALE/SCALEUIReference/Shares/NFSSharesScreens.md, content/SCALE/SCALEUIReference/SystemSettings/Services/NFSServiceScreen.md
- Update link to go to the correct subsection
- Update sessions notes with more depth and explanation and troubleshooting about an inaccurate sessions list.
=> PD-1688 / 25.10 / update NFS Sessions (master)

content/SCALEUIReference/Shares/NFSSharesScreens.md, content/SCALEUIReference/SystemSettings/Services/NFSServiceScreen.md
- Update link to go to the correct subsection
- Update sessions notes with more depth and explanation and troubleshooting about an inaccurate sessions list.
Original PR: https://github.com/truenas/documentation/pull/3760
Jira URL: https://ixsystems.atlassian.net/browse/PD-1688
=> PD-1688 / 25.04 / update NFS Sessions (by Mrt134)

layouts/partials/toc-panel.html, static/custom.css
=> PD-1906 / 25.10 / Pd 1906 update apps truenas com resource article styling

layouts/partials/toc-panel.html, static/custom.css
=> PD-1906 / 13.3 / Pd 1906 update apps truenas com resource article styling (by DjP-iX)

layouts/partials/toc-panel.html, static/custom.css
=> PD-1906 / 24.04 / Pd 1906 update apps truenas com resource article styling (by DjP-iX)

layouts/partials/toc-panel.html, static/custom.css
=> PD-1906 / 24.10 / Pd 1906 update apps truenas com resource article styling (by DjP-iX)

layouts/partials/toc-panel.html, static/custom.css
=> PD-1906 / 25.04 / Pd 1906 update apps truenas com resource article styling (by DjP-iX)

layouts/partials/toc-panel.html, static/custom.css
=> PD-1906 / 3.0 / Pd 1906 update apps truenas com resource article styling (by DjP-iX)

static/includes/MultipleInterfacesOnNetwork.md
=> 25.04 - Update MultipleInterfacesOnNetwork.md

content/GettingStarted/Migrate/MigratePrep.md, content/GettingStarted/Migrate/MigratingFromCORE.md, content/SCALETutorials/SystemSettings/General/ManageSysConfigSCALE.md, static/includes/WhyUploadConfig.md
git cherry-pick -x a4d71566da81f3e9d2d03519dbc19f94672f1a2e
git cherry-pick -x c05c464ccae834562c5e888fff091f1e904fa2f4
git cherry-pick -x ad6ad987530645eddc8186e5e9ec1e2ed20f87ff
git cherry-pick -x 0560cdc2d51dc3d3cb199973bbda0f50a8fba1f7
git cherry-pick -x c49633b3e960a94e74b036fe8166bd6d36264758
git cherry-pick -x d20f71d1da1cf6fb3637600388727459f240effb
git cherry-pick -x 74e7f9988ca44a68a72997cdaae79cb19365d914
Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons …
=> PD-1888 / 25.04 / Pd-1888 add notes about uid gid changes from true nas 13 to true nas 25 04 (by DjP-iX)

content/GettingStarted/Configure/UIConfigurationSCALE.md, content/GettingStarted/Configure/VMandAppConfigSCALE.md, content/GettingStarted/DataMigrationSyncthing.md, content/GettingStarted/SCALEReleaseNotes.md, content/SCALETutorials/DataProtection/RsyncTasksSCALE.md, content/SCALETutorials/Datasets/EncryptionSCALE.md, content/SCALETutorials/SystemSettings/Advanced/ManageGPUSCALE.md, content/SCALETutorials/SystemSettings/ManageBootEnvironSCALE.md, content/SCALETutorials/Virtualization/_index.md, content/SCALEUIReference/Apps/InstallCustomAppScreens.md, content/_index.md, data/menu/more.yml, layouts/partials/docs-nav.html, layouts/shortcodes/section-cards.html, static/includes/24.10FeatureList.md, static/includes/NetdataUI.md
=> PD-1908 / 24.10 / Pd 1908 decommission apps content from docs hub 24.10

layouts/partials/docs-nav.html
=> PD-1908 / 3.0 / Pd-1908 backport docs nav update

layouts/partials/docs-nav.html
Original PR: https://github.com/truenas/documentation/pull/3788
Jira URL: https://ixsystems.atlassian.net/browse/PD-1908
=> PD-1908 / 13.0 / Pd-1908 backport docs nav update (by DjP-iX)

layouts/partials/docs-nav.html
Original PR: https://github.com/truenas/documentation/pull/3788
Jira URL: https://ixsystems.atlassian.net/browse/PD-1908
=> PD-1908 / 13.3 / Pd-1908 backport docs nav update (by DjP-iX)

layouts/partials/docs-nav.html
=> PD-1896 / 25.04 / PD-1896-archive-24-04-docs-25.04

static/includes/AppsSupportTimeline.md
=> Pd-1973-Fix-actions-required

static/includes/AppsSupportTimeline.md
Previous PR didn't auto backport
Original PR: https://github.com/truenas/documentation/pull/3831
Jira URL: https://ixsystems.atlassian.net/browse/PD-1973
=> PD-1973 / 25.10 / PD 1973 Fix actions required backports (by DjP-iX)

layouts/partials/docs-nav.html
Original PR: https://github.com/truenas/documentation/pull/3817
Jira URL: https://ixsystems.atlassian.net/browse/PD-1896
=> PD-1896 / 13.0 / PD-1896-archive-24-04-docs-25.04 (by DjP-iX)

layouts/partials/docs-nav.html
Original PR: https://github.com/truenas/documentation/pull/3817
Jira URL: https://ixsystems.atlassian.net/browse/PD-1896
=> PD-1896 / 13.3 / PD-1896-archive-24-04-docs-25.04 (by DjP-iX)

layouts/partials/docs-nav.html
Original PR: https://github.com/truenas/documentation/pull/3817
Jira URL: https://ixsystems.atlassian.net/browse/PD-1896
=> PD-1896 / 24.10 / PD-1896-archive-24-04-docs-25.04 (by DjP-iX)

layouts/partials/docs-nav.html
Original PR: https://github.com/truenas/documentation/pull/3817
Jira URL: https://ixsystems.atlassian.net/browse/PD-1896
=> PD-1896 / 3.0 / PD-1896-archive-24-04-docs-25.04 (by DjP-iX)

layouts/partials/site-footer.html, static/custom.css
=> PD-2005 / 13.0 / Pd 2005 update footer menu on docs (by DjP-iX)

layouts/partials/site-footer.html, static/custom.css
=> PD-2005 / 13.3 / Pd 2005 update footer menu on docs (by DjP-iX)

layouts/partials/site-footer.html, static/custom.css
=> PD-2005 / 3.0 / Pd 2005 update footer menu on docs (by DjP-iX)

layouts/partials/site-footer.html, static/custom.css
=> PD-2005 / 25.04 / Pd 2005 update footer menu on docs (by DjP-iX)

layouts/partials/site-footer.html, static/custom.css
=> PD-2005 / 24.10 / Pd 2005 update footer menu on docs (by DjP-iX)

data/properties/scale-downloads.yaml
.0 and .1 added SCALE to the paths
=> Corrected Fangtooth paths

content/SCALE/SCALEUIReference/Credentials/BackupCredentials/CloudCredentialScreens.md, static/includes/AddStorjCloudCredential.md
=> PD-2017 / 25.10 / PD-2017-document-new-endpoint-option-for-cloud-sync-credentials

content/SCALETutorials/Datasets/PermissionsSCALE.md
…tainers
Original PR: https://github.com/truenas/documentation/pull/3884
Jira URL: https://ixsystems.atlassian.net/browse/PD-1976
=> PD-1976 / 25.04 / PD-1976-document-how-to-grant-permissions-to-root-in-unprivileged-con… (by linzi-ix)

content/GettingStarted/Install/InstallingSCALE.md
=> PD-2055   Windows Using Sha 256 checksum command is wrong

content/SCALEUIReference/Shares/SMBSharesScreens.md
git cherry-pick -x ed91bb9e7961481c49ddd4d5503e447d206b9e30
git cherry-pick -x 61ca17af4df3a01eded83cd0ddf53f0ba3803f42
git cherry-pick -x e88133dda5a0ab5c3371f24c88892811df3fde26
git cherry-pick -x c1ace9722f9d528053ab0e18676eb8c151ed7091
Original PR: https://github.com/truenas/documentation/pull/3901
Jira URL: https://ixsystems.atlassian.net/browse/PD-2041
=> PD-2041 / 25.04 / PD-2041-documentation-about-legacy-afp-shares-is-incorrect (by linzi-ix)

static/includes/TopToolbar.md
Add an Enterprise-specific note that points the reader to the hardware documentation section for any additional content specific to a TrueNAS product that might impact power behaviors.
=> PD-1822 / 25.10 / PD-1822

content/SCALETutorials/Storage/Disks/ReplacingDisks.md
=> PD-1776 / 24.10 / PD-1776   Add section for replacing disk or disks 'in place'

content/GettingStarted/Getting Support/_index.md, static/includes/CommunityForums.md
git cherry-pick -x bc5eab441a75dd77301b02158c45ec53a89f2aa4
git cherry-pick -x 0dee00bc45ac713ad781975012826f99765d96bc
git cherry-pick -x 0dd23a26a5fafd74a70f393b263f188741d97663
There's some elements that aren't being updated or are specific to 24.10. Backports to other branches will need to be reviewed to ensure the content changes are appropriate for their TrueNAS version.
Reorganize content a bit, make sure links are functional, and update forum snippet to note it's use for feature suggestions and voting.
Thanks for contributing to TrueNAS documentation! By opening a Pull Request, …
=> PD-2046 / 25.04 / PD-2046 update Getting Support article in 24.10 (by Mrt134)

static/includes/25.04Virtualization.md
=> PD-2056 / 25.10 / Pd 2056 follow up

layouts/partials/docs-nav.html
Original PR: https://github.com/truenas/documentation/pull/3965
Jira URL: https://ixsystems.atlassian.net/browse/PD-2098
=> PD-2098 / 24.04 / PD-2098-improve-handling-for-nightly-docs (by DjP-iX)

content/SCALETutorials/Apps/Docker.md, content/SCALEUIReference/Apps/LaunchDockerImageScreens.md
22.12 version of https://github.com/truenas/documentation/pull/3975
=> PD-2098 / 22.12 / Pd 2098 investigate 404 error list provided from marketing 22.12

content/GettingStarted/SCALEReleaseNotes.md, content/SCALETutorials/SystemSettings/Services/SSHServiceSCALE.md, content/SCALEUIReference/SystemSettings/Services/SSHServiceScreenSCALE.md, data/properties/scale-releases.yaml, static/includes/UpgradeNotesBoilerplate.md, static/includes/auxiliary-parameters-ssh.md
=> PD-2146 / 25.04 / Pd 2146 update ssh auxiliary parameters warnings

static/llms.txt
=> PD-2066 / 13.3 / Pd 2066 research and implement llms txt file for documentation websites 13.3

static/llms.txt
=> PD-2066 / 24.10 / Pd 2066 research and implement llms txt file for documentation websites 24.10

static/llms.txt
=> PD-2066 / 24.04 / Pd 2066 research and implement llms txt file for documentation websites 24.04

content/SCALE/SCALETutorials/SystemSettings/Services/SSHServiceSCALE.md, content/SCALE/SCALEUIReference/SystemSettings/Services/SSHServiceScreenSCALE.md, data/properties/scale-releases.yaml, static/includes/UpgradeNotesBoilerplate.md, static/includes/auxiliary-parameters-ssh.md
git cherry-pick -x 2a1886f7f4dab7b31869536c0d78a7253d8e5483
git cherry-pick -x 6a1640b23ce11def90ea77a30049a275f3bdaa2e
git cherry-pick -x 3dbe6385d9eef99f3219cffc242e1e033e730397
git cherry-pick -x 5d075441cf90c565ec220415cd01aafe18b031eb
git cherry-pick -x 20fb26ae83fa0cb713f462aa7004f7dbf92c8792
git cherry-pick -x 8a7854d9c90eb4ee34547bb00c374c28960202c6
git cherry-pick -x c2321e3ad3e9278b46a06b0846a1433497f38516
Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons …
=> PD-2146 / 25.10 / Pd 2146 update ssh auxiliary parameters warnings (by DjP-iX)

content/SCALETutorials/Network/ContainerNASBridge.md, static/includes/DatasetPresetOptions.md
Original PR: https://github.com/truenas/documentation/pull/3994
Jira URL: https://ixsystems.atlassian.net/browse/PD-2117
=> PD-2117 / 25.04 / Pd 2117 incorrect smb preset listed (by DjP-iX)

content/SCALE/GettingStarted/SCALEReleaseNotes.md
https://ixsystems.atlassian.net/browse/NAS-136947
=> NAS-136947: Add early note about Nvidia driver change in 25.10 nightlies

data/properties/core-downloads.yaml, data/properties/scale-downloads.yaml, data/properties/scale-releases.yaml, static/includes/SCALEUpgradePaths.md
This PR updates the /data/properties/scale-downloads.yaml and /data/properties/scale-releases.yaml files
Do not backport this PR.
=> PD-1996 / 25.10 / PD-1996 Update Release Schedules

data/properties/component_versions.yaml
=> Correct 25.04.2 Nvidia Driver

CSV-TABLE-SETUP.md, scripts/combine-changelogs.py, static/js/csv-changelog-table.js
Original PR: https://github.com/truenas/documentation/pull/4051
Jira URL: https://ixsystems.atlassian.net/browse/PD-1966
=> PD-1966 / 25.10 / Pd 1966 update changelog table (by DjP-iX)

content/GettingStarted/SCALEReleaseNotes.md, data/properties/scale-downloads.yaml, data/properties/scale-releases.yaml, static/includes/SCALEUpgradePaths.md, words-to-ignore.txt
=> PD-2180 / 25.04 / Pd 2180 25 04 2 3 maintenance release docs

content/SCALE/GettingStarted/SCALEReleaseNotes.md
=> Remove 25.10 release notes alias from master (branch is publishing)

layouts/partials/docs-nav.html
Ports the updated version switcher to add the 25.10 branch navigation options to previous versions
=> PD-1970 / 25.04 / PD-1970-port-version-switcher

layouts/partials/docs-nav.html
Ports the updated version switcher to add the 25.10 branch navigation options to previous versions
Original PR: https://github.com/truenas/documentation/pull/4055
Jira URL: https://ixsystems.atlassian.net/browse/PD-1970
=> PD-1970 / 13.3 / PD-1970-port-version-switcher (by DjP-iX)

layouts/partials/docs-nav.html
Ports the updated version switcher to add the 25.10 branch navigation options to previous versions
Original PR: https://github.com/truenas/documentation/pull/4055
Jira URL: https://ixsystems.atlassian.net/browse/PD-1970
=> PD-1970 / 24.10 / PD-1970-port-version-switcher (by DjP-iX)

layouts/partials/docs-nav.html
=> PD-2192 / 26.04 / fix version select behavior for 25.10 version option

layouts/partials/docs-nav.html
Original PR: https://github.com/truenas/documentation/pull/4070
Jira URL: https://ixsystems.atlassian.net/browse/PD-2192
=> PD-2192 / 13.0 / fix version select behavior for 25.10 version option (by Mrt134)

static/includes/Jobs.md
Spoke with William to confirm changes.
Original PR: https://github.com/truenas/documentation/pull/4061
Jira URL: https://ixsystems.atlassian.net/browse/PD-2150
=> PD-2150 / 25.10 / Update Jobs.md (by linzi-ix)

data/properties/scale-downloads.yaml
See: https://forums.truenas.com/t/truenas-25-10-beta-1-is-now-available/51202/8
Original PR: https://github.com/truenas/documentation/pull/4090
Jira URL: https://ixsystems.atlassian.net/browse/PD-1966
=> PD-1966 / 25.10 / Fix 25.10-BETA.1 Download Link (by DjP-iX)

content/SCALE/SCALETutorials/Shares/NVMe-oF/Managing-NVMe-of-Subsystems.md, content/SCALE/SCALETutorials/Shares/NVMe-oF/_index.md, static/includes/NVMeoTCPESXiLimitation.md
=> Backport nvme of known issue

data/menu/more.yml, static/custom.css
Original PR: https://github.com/truenas/documentation/pull/4101
Jira URL: https://ixsystems.atlassian.net/browse/PD-2173
=> PD-2173 / 25.10 / PD-2173-make-apps-market-links-more-prominent-on-the-docs-hub (by linzi-ix)

data/menu/more.yml, static/custom.css
Original PR: https://github.com/truenas/documentation/pull/4101
Jira URL: https://ixsystems.atlassian.net/browse/PD-2173
=> PD-2173 / 25.04 / PD-2173-make-apps-market-links-more-prominent-on-the-docs-hub (by linzi-ix)

static/custom.css
https://github.com/truenas/documentation/pull/4116 Did not fix the issue
Original PR: https://github.com/truenas/documentation/pull/4118
Jira URL: https://ixsystems.atlassian.net/browse/PD-2173
=> PD-2173 / 25.04 / PD-2173-Another-hover-fix (by DjP-iX)

static/custom.css
https://github.com/truenas/documentation/pull/4116 Did not fix the issue
Original PR: https://github.com/truenas/documentation/pull/4118
Jira URL: https://ixsystems.atlassian.net/browse/PD-2173
=> PD-2173 / 25.10 / PD-2173-Another-hover-fix (by DjP-iX)

content/GettingStarted/SCALEReleaseNotes.md, data/properties/scale-downloads.yaml, data/properties/scale-releases.yaml, static/includes/SCALEUpgradePaths.md
=> PD-2211 / 25.04 / Pd 2211 25 04 2 4 release notes

data/properties/scale-downloads.yaml, data/properties/scale-releases.yaml, static/includes/SCALEUpgradePaths.md
Original PR: https://github.com/truenas/documentation/pull/4097
Jira URL: https://ixsystems.atlassian.net/browse/PD-2211
=> PD-2211 / 25.10 / Pd 2211 25 04 2 4 release follow up (by DjP-iX)

content/GettingStarted/SCALEReleaseNotes.md
=> Update SMB fix description in 25.04.2.4 release notes

data/properties/core-releases.yaml, layouts/partials/docs-nav.html
=> PD-2234-archive-13-3-documentation-25.04

data/properties/core-releases.yaml, layouts/partials/docs-nav.html
git cherry-pick -x e3adb9a0e7351d7f753e92296dc39497ad5f75be
git cherry-pick -x 93c2306065441a366b738ef35ba8b250c21efd1b
git cherry-pick -x e02c2e91c93396862c6db50ef13e1c0eaeb12d3b
Original PR: https://github.com/truenas/documentation/pull/4165
Jira URL: https://ixsystems.atlassian.net/browse/PD-2234
=> PD-2234 / 3.0 / Pd 2234 archive 13 3 documentation (by linzi-ix)

content/SCALETutorials/DataProtection/CloudSyncTasks/AddGooglePhotosCloudSyncTask.md
Original PR: https://github.com/truenas/documentation/pull/4168
Jira URL: https://ixsystems.atlassian.net/browse/PD-2206
=> PD-2206 / 25.10 / Pd 2206 update content around google photos use (by DjP-iX)

static/js/csv-changelog-tab-init.js, static/js/csv-changelog-table.js
Fixes issues with loading individual release changelogs and the changelog search functionality. 
=> PD-1967 / 25.10 / Pd 1967 fix changelog table

content/GettingStarted/SCALEReleaseNotes.md, layouts/shortcodes/changelog-scripts.html, static/js/csv-changelog-tab-init.js
=> PD-1967 / 25.10 / Pd 1967 changelog fix 2

content/SCALE/GettingStarted/SCALEReleaseNotes.md, layouts/shortcodes/changelog-scripts.html, static/js/csv-changelog-tab-init.js, static/js/csv-changelog-table.js
Fixes issues with loading individual release changelogs and the changelog search functionality. 
Original PR: https://github.com/truenas/documentation/pull/4192
Jira URL: https://ixsystems.atlassian.net/browse/PD-1967
=> PD-1967 / 26.04 / Pd 1967 fix changelog table (by DjP-iX)

static/data/changelog-versions.json
* Update changelog-versions.json
* rename
* rename
=> PD-1967 / 26.04 / Pd 1967 fix 3 (#4196)

content/GettingStarted/SCALEReleaseNotes.md
=> Add known issue (NAS-137818) to 25.10 list.

content/SCALETutorials/Shares/SMB/AddSMBShadowCopies.md
Original PR: https://github.com/truenas/documentation/pull/4187
Jira URL: https://ixsystems.atlassian.net/browse/PD-2254
=> PD-2254 / 25.10 / Pd 2254 smb shadow copies additional explanation (by DjP-iX)
