truenas/documentation

- .github/workflows/gh-pages.yml
- .github/workflows/main.yml
> Add workflow for deploying site on gh pages

- .github/CODEOWNERS
This will add the Docs team as a default reviewer on pull requests.
> Add CODEOWNERS for default reviewers.

- README.md
> Update README with how to build locally

- content/en/_index.html
- content/en/articles/_index.md
- layouts/shortcodes/inprog.html
> DOCS-254 Add "in progress" message to main page.

- .github/workflows/gh-pages-pullRequest.yml
- config.toml
> Testing the PR build action.

- content/en/_index.html
- content/en/docs/_index.md
> DOCS-206: minor cleanup to a couple top-level index pages.

- content/en/articles/TrueNAS/legacy_documentation.md
Website policy restricts me from testing this locally. If this iframe works correctly, I'll be adding the FreeNAS guides in that section and working on any needed styling improvements.
> DOCS-269: add article with iframe to previous style docs.

- content/en/articles/TrueNAS/legacy_documentation.md
> DOCS-269: add height value to make iframe readable

- content/en/docs/FreeNAS/fn_previous_guides.md
- content/en/docs/FreeNAS/hardware-guide.md
> Add doc with embedded link to the FreeNAS Hardware Guide.

- .vscode/settings.json
- deploy
- deploy.py
> Python script to deploy to webserver manually.

- assets/scss/_variables_project.scss
- content/en/docs/FreeNAS/articles/getting-started/index.md
> DOCS-263 modify shortcode to include a "version" parameter.

- .github/workflows/gh-PR-preview.yml
> Add workflow for build preview on PRs

- .github/workflows/gh-PR-preview.yml
> work on PR build preview.

- .github/workflows/gh-PR-preview.yml
> Get PR preview build working.

- content/en/docs/TrueNAS/ui-reference-guide/ZFS-references.md.txt
Trying a Windows/GitHub Desktop -only workflow, to see how it goes.
Copied the existing ZFS primer from the guide and reworked it for Markdown.
> DOCS-264: Port ZFS Primer to Reference Guide

- content/en/docs/FreeNAS/articles/pr_preview_test_build/index.md
I'm going to test the PR merging/deleting workflow from PR #33
> Testing changes through a PR for the PR preview.

- content/en/docs/FreeNAS/articles/pr_preview_test_build/index.md
> testing once again, the clean server workflow.

- content/en/docs/FreeNAS/articles/pr_preview_test_build/index.md
> test delete PR branch workflow trigger.

- content/en/docs/FreeNAS/articles/pr_preview_test_build/index.md
> yet another change to test workflow trigger.

- config.toml
Created a GCSE for the website. I *think* this will work, but I won't know for sure until the site is 100% public.
> Add GCSE ID to the theme for site searching.

- content/en/docs/TrueNAS/plugins.md
> DOCS-336: Add process summary for TrueNAS plugins

- content/en/docs/TrueNAS/update/ha-update-enterprise.md
> DOCS-338: Add process summary to WIP HA update article.

- content/en/docs/TrueNAS/alerts.md
> DOCS-335: Add Alerts summary

- content/en/docs/TrueNAS/disk-replace.md
> DOCS-334: Add Disk Replacement Summary

- content/en/docs/TrueNAS/high-availability.md
> DOCS-333: Add High Availability summary

- content/en/docs/TrueNAS/cloudsync.md
> DOCS-332: Add cloud sync summary.

- content/en/docs/TrueNAS/editingacls.md
> DOCS-331: Add ACL Management summary

- content/en/docs/TrueNAS/activedirectory.md
> DOCS-330: Add active directory config summary

- content/en/docs/TrueNAS/replication.md
> DOCS-329: Add replication tasks summary

- content/en/docs/previous-version-documentation/tn_legacy_documentation.md
> Fix https error with TrueNAS legacy doc iframe

- content/en/docs/TrueNAS/lifecycle.md
> add lifecycle doc

- content/en/docs/TrueNAS/hardware-guide.md
- Doesn't work in local build testing, but fix is identical to working iframes on live site.
> DOCS-446: fix iframe display for hardware guide article

- config.toml
> DOCS-443 made sidebar collapsed

- content/en/docs/TrueNAS/system-alerts.md
> DOCS-442 doc on configuring system alerts

- content/en/docs/TrueNAS/system-reporting.md
> DOCS-441 doc on configuring system reporting.

- config.toml
- content/en/docs/TrueNAS/system-alerts.md
> Testing relative paths with PR

- content/en/_index.html
> DOCS-479: Reactivate WIP blurb for front page.

- .github/workflows/gh-PR-preview.yml
> pull pr number instead of branch name.

- content/en/docs/TrueNAS/software-guides/storage/datasets.md
> DOCS-492 write how-to for creating dataset.

- .github/workflows/gh-PR-preview.yml
- .github/workflows/gh-publish.yml
> Testing PR preview action with new server.

- .github/workflows/gh-PR-preview.yml
> PR to test comment functionality.

- content/en/docs/TrueNAS/software-guides/storage/zvols.md
> DOCS-493 how-to for creating Zvol.

- content/en/docs/TrueNAS/software-guides/reporting-disk-temp.md
> DOCS-437 add doc on disk temp reporting.

- content/en/docs/TrueCommand/admins/install.md
> DOS-548 update TC install instruct on docs site.

- content/en/truenas-roadmap/_index.md
> DOCS-529 Add link (for now) to TN public roadmap.

- assets/scss/_variables_project.scss
Merging Dennis' fantastic fix to the front page.
> DOCS-557: fix dropdowns

- content/en/_index.html
- content/en/intro/release-notes/TN-12_0.md
- content/en/intro/release-notes/_index.md
> DOCS-557: add placeholder for release notes

- assets/icons/logo.svg
- config.toml
- content/en/_index.html
> DOCS-593 Add new logos to site.

- package-lock.json
> update npm package stuff.

- version-release.py
> Improve print statement and output info in version script

- version-release.py
Not finished yet. Don't merge.
> Big changes for running script on docs site server.

- version-release.py
> Make it so args can be passed in one line.

- version-release.py
> Made the script with functions

- assets/scss/_variables_project.scss
- content/en/_index.html
Adjusted colors, font, and buttons.
> DOCS-602: Adjust front page styling to fit other TrueNAS websites

- content/en/docs/solutions/openstack/cinder.md
This driver is open source and completely supported by the community, so refer to that projects documentation.
> DOCS-608: Add basic article about Cinder driver.

- content/en/docs/sharing/nfs/nfs-share.md
> DOCS-633 Write article for creating basic NFS share.

- assets/scss/_variables_project.scss
- layouts/partials/footer.html
> DOCS-696: Adjust footer color

- content/en/docs/sharing/afp/afp-share.md
> DOCS-635 Write AFP article.

- content/en/docs/tasks/administrative/users.md
> DOCS-639 article for creating users.

- config.toml
> DOCS-717: Clear "Version" menu

- content/en/docs/tasks/administrative/groups.md
> DOCS-640 managing groups how-to

- content/en/hub/initial-setup/directory-services/activedirectory.md
> DOCS-715: Update AD article

- content/en/_index.html
- content/en/hub/tasks/scheduled/cron-jobs.md
> DOCS-706 article on cron jobs

- content/en/hub/hardware/fn-mini/mini-config-data-recovery.md
> DOCS-701: Publish Mini Config/Data Recovery Guide.

- content/en/hub/hardware/expansion-shelves/sas-connections.md
> DOCS-720: publish SAS Connections Guide

- layouts/partials/navbar.html
> DOCS-727: Update logo link to Docs site front page

- content/en/hub/tasks/scheduled/smart.md
> DOCS-708 S.M.A.R.T. test how-to

- content/en/hub/contributing/_index.md
> DOCS-728: Add text about TrueNAS slack channel to Contributing section

- content/en/hub/initial-setup/install/getting-started/index.md
> Update Index.md - Don't Recommend WD Red Drives

- content/en/_index.html
- content/fr/_index.html
> DOCS-739: Move TrueNAS Hardware Requirements link on front page

- content/en/hub/tasks/scheduled/scrub.md
> DOCS-709 scrub task how-to

- package-lock.json
- package.json
> Update npm stuff.

- content/en/hub/tasks/task-manager.md
- package-lock.json
- package.json
Had to install the material design icon font to use an icon from the UI.
> DOCS-641 article for UI Task Manager

- content/en/hub/tasks/advanced/system-dataset.md
> DOCS-656 change system dataset how-to

- content/en/hub/additional-topics/eula.md
> DOCS-669: add TN EULA

- config.toml
- layouts/partials/footer.html
> DOCS-749: Add link to iX Account Services site

- content/en/hub/initial-setup/install/getting-started/index.md
> DOCS-760 advice against using USB for TN

- content/en/hub/additional-topics/preferences.md
> DOCS-649 add how-to for user preferences.

- content/en/hub/tasks/advanced/sed-drives.md
> DOCS-654: Create sed-drives.md

- content/en/hub/initial-setup/directory-services/ldap.md
> DOCS-692 how-to for connecting to LDAP

- content/en/hub/tasks/administrative/certificates.md
I have a link to the CA document that is not written yet in the text. The link path
should work fine once the CA doc is written.
> DOCS-665 add certificate article.

- content/en/hub/tasks/administrative/certificate-authorities.md
- content/en/hub/tasks/administrative/certificates.md
Also touched up some things in the Certificate article
> DOCS-664 add CA article

- content/en/hub/initial-setup/login.md
Turns out this information was mostly there. Just added the little bit
that wasn't.
> DOCS-645 Add interface troubleshooting info.

- package-lock.json
- package.json
> Update npm package list.

- content/en/hub/tasks/administrative/system-reporting.md
> DOCS-657 expand system reporting and graphs.

- content/en/hub/tasks/advanced/tunables.md
> DOCS-660 article on system tunables.

- config.toml
> add legacy to drop down

- content/en/hub/initial-setup/install/getting-started/index.md
- Comments on install media creation Windows and Linux.
- Added comments on boot process.
- Added comment about legacy BIOS sunsetting.
- Changed FreeNAS to TrueNAS throughout.
ToDo:
- Link to install media should point to TrueNAS
- Step by step guide should have a screenshot of the EFI/legacy BIOS selection screen
> Clarifications

- content/en/hub/scale/dev-notes.md
> Update VM Dev notes

- .github/workflows/gh-PR-preview.yml
- .github/workflows/gh-publish.yml
> DOCS-797 Fix Github action PR builder

- content/en/hub/tasks/administrative/rest-api.md
> spelling correction

- content/en/hub/tasks/administrative/backup-config.md
> DOCS-662 article on saving system config

- content/en/hub/tasks/administrative/system-alerts.md
> DOCS-658: Update system-alerts.md

- content/en/hub/tasks/scheduled/replication/_index.md
> DOCS-794 Add note about "resumable" token for replication.

- content/en/hub/initial-setup/storage/upgrading-pool.md
> DOCS-663 article on upgrading pool.

- content/en/hub/initial-setup/install/getting-started/index.md
> Docs 805 Ryzen update

- content/en/hub/additional-topics/ipmi-faq.md
- content/en/hub/hardware/notices/ipmi-faq.md
> kba - ipmi faq

- content/en/hub/hardware/rma-policy.md
> kba - rma-policy.md

- content/en/hub/tasks/administrative/etc-host-persistence.md
> DOCS-477: kba - etc-host-persistence.md

- content/en/hub/initial-setup/directory-services/ms-ldap-defaults-2020.md
> DOCS-477: kba - ms-ldap-defaults-2020.md

- content/en/hub/tasks/scheduled/scrub-resilver-notice.md
> DOCS-477: kba - scrub-resilver-notice.md

- content/en/hub/sharing/smb/smb1.md
> DOCS-477: kba - smb1.md

- content/en/hub/hardware/notices/wd-smr.md
> DOCS-477: kba - wd-smr.md

- content/en/hub/hardware/expansion-shelves/es12-bsg.md
> DOCS-817: Fix one additional document link

- content/en/hub/intro/release-notes/fn-11_3-U4.md
> DOCS-827: 11.3-U4.1 Release notes

- content/en/hub/additional-topics/errata/_index.md
- content/en/hub/additional-topics/errata/zfs-pool.md
> Docs 736 errata

- assets/scss/_variables_project.scss
> DOCS-833: update one icon source path

- content/en/hub/intro/release-notes/tn-11_3-U4_1.md
> DOCS-820: TN 11.3-U4.1 Release Notes

- content/en/hub/additional-topics/legacy/api/v1-api.html
> add legacy v1 API html

- content/en/hub/initial-setup/best-practices/manage-tls.md
> add note about rebooting

- assets/scss/_nav.scss
- config.toml
- Make title visible in tab but invisible on home page (title is covered by SVG)
> DOCS-856: Fix Home page title

- config.toml
- themes/docsy/layouts/_default/baseof.html
- themes/docsy/layouts/hub/baseof.html
early test, not for merging yet
> DOCS-859: Replace Google Analytics with Google Tag Manager

- config.toml
- themes/docsy/layouts/_default/content.html
- themes/docsy/layouts/partials/reading-time.html
> DOCS-865 Readtime patch

- themes/docsy/layouts/partials/tags.html
> tagcloud fix

- assets/scss/_variables_project.scss
> Docs-875 update css for tagcloud

- content/en/hub/hardware/fn-certified/multipath.md
> DOCS-831: Convert and publish FNC wide porting statement

- content/en/hub/sharing/smb/smb1.md
This is the #1 use case and concern, so mention it.
Yep!
> Mention Windows Explorer/WS-Discovery 

- content/en/hub/sharing/smb/smb-share.md
We don't explain what SMB is at all, and many users won't know. Give a bit of description first - after all as a file server, SMB shares will be a #1 use case.  Also remove useless sentence _"If sharing a lot of data securely with many users is the goal, then setting up an SMB share can help"_ - wishy washy and doesnt say much. Replace by actual useful info.
> Provide a better overview of SMB

- content/en/hub/intro/RecommendedUpdateforZFS.md
- content/en/hub/intro/release-notes/fn-11_3-U4.md
- content/en/hub/intro/release-notes/tn-11_3-U4_1.md
Add tags to differentiate between FreeNAS and TrueNAS Enterprise
> DOCS-899: Publish "Recommended ZFS Update" statement

- content/en/hub/truecommand/DockerUpdate.md
changes from testing the instructions and discussing with Ken.
> DOCS-934: Rework TC Container Update article

- content/en/hub/initial-setup/install/PhysicalHardware/index.md
> DOCS-931: Update hardware requirements (physical install)

- content/en/hub/hardware/expansion-shelves/es12-bsg.md
- content/en/hub/hardware/expansion-shelves/es24-bsg.md
- content/en/hub/hardware/expansion-shelves/es60-bsg.md
- content/en/hub/hardware/expansion-shelves/sas-connections.md
- content/en/hub/hardware/fn-certified/fn-certified-bsg.md
- content/en/hub/hardware/fn-certified/multipath.md
- content/en/hub/hardware/m-series/m-series-bsg.md
- content/en/hub/hardware/m-series/m-series-satadom-replacement.md
- content/en/hub/hardware/m-series/m-series-sov.md
- content/en/hub/hardware/mini/FamilySoV.md
- content/en/hub/hardware/mini/MiniBSG.md
- content/en/hub/hardware/mini/MiniEE+HUG.md
- content/en/hub/hardware/mini/MiniEE+XOOBM.md
- content/en/hub/hardware/mini/MiniX+HUG.md
- content/en/hub/hardware/mini/MiniX+XL+OOBM.md
- content/en/hub/hardware/mini/MiniXHUG.md
- content/en/hub/hardware/mini/MiniXL+HUG.md
- content/en/hub/hardware/mini/mini-config-data-recovery.md
- content/en/hub/hardware/notices/ipmi-faq.md
- content/en/hub/hardware/notices/lsi9300-timeout.md
- content/en/hub/hardware/notices/wd-smr.md
- content/en/hub/hardware/rma-policy.md
- content/en/hub/hardware/stencils.md
- content/en/hub/hardware/x-series/x-series-controller-replacement.md
- content/en/hub/hardware/x-series/x-series-sov.md
- content/en/hub/hardware/x-series/xseries-bsg.md
- content/en/hub/initial-setup/install/PhysicalHardware/index.md
> docs-917: Update index.md

- content/en/hub/intro/release-notes/tn-12_0-beta2.md
> DOCS-940: Add link to Security Site CVE for 12.0-BETA2.1 release notes

- layouts/partials/footer.html
> Docs-956 linkfix

- content/en/hub/initial-setup/storage/encryption.md
> Docs-942 Update encryption.md

- content/en/hub/truecommand/tc_cloud.md
> Docs-699-TC-Cloud

- content/en/hub/tasks/scheduled/replication/advanced.md
> NAS-107531: Add quick "gotcha" note about large-block replication

- content/en/_index.html
- content/en/hub/solutions/kubernetes.md
- Update home page "Solutions" links to reflect article order
- Include links to Kubernetes drivers project repository and README.
> DOCS-1028: Add simple Kubernetes open source drivers overview

- content/en/hub/initial-setup/storage/encryption.md
> DOCS-1029: Add caution about early GELI > ZFS migration

- content/en/hub/initial-setup/networking/DefaultPorts.md
- content/en/hub/initial-setup/networking/_index.md
> DOCS-1042-ports

- content/en/hub/intro/COREHardwareGuide.md
> Docs-868-optical

- content/en/hub/scale/dev-notes.md
> Update dev notes outlining limited k8s support

- content/en/hub/initial-setup/storage/sed-drives.md
> DOCS-1021-SED

- content/en/hub/intro/truenas-roadmap.md
> DOCS-1071: Update Software Releases Roadmap

- content/en/hub/initial-setup/storage/encryption.md
> DOCS-935-encryption-icons

- content/en/hub/tasks/advanced/virtual-machines.md
> DOCS-900-vmstop

- content/en/hub/initial-setup/install/PhysicalHardware/index.md
> Change Article Title for Installation

- content/en/hub/tasks/scheduled/replication/advanced.md
> NAS-107847-naming-schema

- layouts/partials/page-meta-links.html
Request to consolidate issue tracking into the NAS Jira project.
> DOCS-1209: Update issue tracker link

- content/en/hub/initial-setup/security/directory-services/ldap.md
Add link to Certificates article and ensure the import certificate text is accurate.
> NAS-107930: Review LDAP setup text

- content/en/hub/initial-setup/install/FirstTimeInstall/index.md
> DOCS-1224: Embed TrueNAS Channel install tutorials

- content/en/hub/intro/DataCollectionStatement.md
- content/en/hub/intro/eula.md
> NAS-108034: Update EULA and Data Collection statement

- content/en/hub/scale/dev-notes.md
> Update notes with catalog item deployment examples

- content/en/hub/initial-setup/support.md
> DOCS-1244: TrueCommand Support article

- content/en/hardware/expansion-shelves/ES102BSG.md
- content/en/hardware/expansion-shelves/ES24FBSG.md
- content/en/hardware/expansion-shelves/es12-bsg.md
- content/en/hardware/expansion-shelves/es24-bsg.md
- content/en/hardware/expansion-shelves/es60-bsg.md
- content/en/hardware/expansion-shelves/sas-connections.md
Re-weight existing expansion shelf pages
> DOCS-967: Publish ES102 BSG

- content/en/hub/tasks/administrative/EnclosureManagement.md
> DOCS-1299: Add power supply bold syntax

- config.toml
- content/en/hub/_index.md
- layouts/partials/page-meta-links.html
> DOCS-1318: activate site RSS feed

- content/en/hub/initial-setup/support.md
> DOCS-1303: Add debug to support.md

- content/en/hub/solutions/AsigraPlugin.md
- content/en/hub/tasks/advanced/plugins.md
Slight expansion of text and move existing text from Plugins article to standalone article in the Solutions section.
> DOCS-1302: Add Asigra Plugin article

- content/en/hub/sharing/afp/afp-share.md
> DOCS-1394: Fix Typo

- content/en/hub/solutions/vmware/TrueNASvCenterPlugin/RelNotes3.3.0.md
- content/en/hub/solutions/vmware/TrueNASvCenterPlugin/vcenter-datastore.md
- content/en/hub/solutions/vmware/TrueNASvCenterPlugin/vcenter-install.md
- content/en/hub/solutions/vmware/TrueNASvCenterPlugin/vcenter-rbac.md
- content/en/hub/solutions/vmware/TrueNASvCenterPlugin/vcenter-snapshots.md
- content/en/hub/solutions/vmware/TrueNASvCenterPlugin/vcenter-systems.md
- content/en/hub/solutions/vmware/best-practices.md
- content/en/hub/solutions/vmware/vmware-snapshots.md
Use the VMware tag for content housed in that section.
> DOCS-1389: Unify VMware tag

- content/en/hub/initial-setup/system-alerts.md
Update photo to more current UI
> DOCS-1386: Update email photo

- content/en/hub/tasks/advanced/high-availability.md
Update photos for HA to TrueNAS Enterprise (TN12)
> DOCS-1396: Update HA Photos to TN12

- content/en/hub/initial-setup/networking/ddns.md
Update DDNS photo to TN12.  The table will not be modified as the Custom Server/Path are available only under Custom, but still applicable as an option if chosen.
> DOCS-1387: Update Dynamic DNS Photo

- assets/scss/_variables_project.scss
Bring footer aboved other page elements
> DOCS-1392: fix footer z-index

- content/en/hub/intro/release-notes/TN12_0U1.md
> DOCS-1417: Add TN 12.0-U1 Release Notes

- content/en/hub/sharing/FTP-SFTP/_index.md
> remove dead image on ftp page

- content/en/hub/sharing/smb/smb-share.md
> DOCS-1003-smb-windows-bug

- content/en/hub/intro/release-notes/TN12_0U1.md
> Adjust date for enterprise train publish

- content/en/hub/initial-setup/install/tn-vm-install.md
> Note that the usual installing in VMWare/ESXi under UEFI wont work due to NAS-107298. Use BIOS instead for now.

- content/en/hub/initial-setup/FirstTimeLogin/systemsettings.md
> NAS-108766: Update Serial Console field description.

- content/en/hub/initial-setup/install/tn-vm-install.md
We give an example, instead of setting out how it's done generally. Need to give the general principles. Try this.
> Improve VM install, so it can be better used on other hypervisors

- content/en/hub/initial-setup/storage/datasets.md
Added links to the Quotas article in the ZFS Datasets article under ## Managing Datasets.
> DOCS-1420 Write new "Quotas" article

- content/en/hub/sharing/smb/smb-share.md
Clarify and correct multiple points in SMB documentation.
> Various corrections for SMB documentation

- content/en/hub/additional-topics/reference/SMB-references.md
> Fix documentation regarding shadow copies

- content/en/hub/sharing/smb/smb-share.md
Small formatting fix, and alter some comments about logging.
> Fix more smb issues

- content/en/hub/initial-setup/storage/ImportDisk.md
> Docs-1496-import-disk

- content/en/hub/scale/dev-notes.md
> NAS-108820: Remove erroneous SCALE Dev Notes entry

- content/en/hub/sharing/iscsi/fibrechannel.md
Adding Fibre Channel Hardware requirements per DOCS-1305
> DOCS-1305 - Adding TrueNAS Storage systems with a Fibre Channel Option

- assets/scss/_variables_project.scss
- content/en/hub/intro/release-notes/TN12_0U1.md
- Final approved table will be added to template for future TrueNAS Release Notes publications.
> DOCS-1549: Add TrueNAS Quality Lifecycle table to 12.0-U1 release notes

- content/en/hub/intro/whatis.md
- content/en/hub/scale/ScaleIntro.md
- content/en/hub/scale/_index.md
> Docs 1066 Scale Intro

- content/en/hub/scale/ScaleIntro.md
- content/en/hub/scale/dev-notes.md
> Docs-1067 Add Scale Tags

- content/en/truecommand/overview/tcwhatis.md
> Docs-1072 Update tcwhatis.md

- content/en/hub/intro/release-notes/TN12_0U1_1.md
> DOCS-1606: Write 12.0-U1.1 Release Notes

- content/en/hub/solutions/vmware/TrueNASforVMware.md
> Docs-1080-vmware-vaai

- .github/workflows/DailyLinkCheck.yml
- .github/workflows/main.yml
- content/en/hub/intro/whatis.md
- static/config.json
> DOCS-1621: Add new link to whatis.md (link check test)

- content/en/hub/initial-setup/install/FirstTimeInstall/index.md
> Simplify and clarify the method of creating a USB stick for Windows

- config.toml
- content/en/hardware/fn-certified/multipath.md
- content/en/hardware/legacy/mini-gen2/fn-bmc-watchdog.md
- content/en/hardware/notices/rma-policy.md
- content/en/hub/additional-topics/UsageRecommendations/MediaEntertainment.md
- content/en/hub/contributing/template/index.md
- content/en/hub/initial-setup/install/MajorUpgrade.md
- content/en/hub/initial-setup/install/update/ha-update-enterprise.md
- content/en/hub/initial-setup/security/accounts/groups.md
- content/en/hub/initial-setup/security/accounts/users.md
- content/en/hub/initial-setup/security/certificates.md
- content/en/hub/intro/COREHardwareGuide.md
- content/en/hub/intro/RecommendedUpdateforZFS.md
- content/en/hub/tasks/advanced/jails.md
- content/en/hub/tasks/advanced/virtual-machines.md
- content/en/truecommand/InstallUpdate/tc_cloud.md
- content/en/truecommand/overview/releasenotes/_index.md
- content/en/truecommand/overview/releasenotes/eolstatements/_index.md
- content/en/truecommand/overview/releasenotes/eolstatements/tc-1-0-eol.md
- content/en/truecommand/overview/releasenotes/eolstatements/tc-1-1-eol.md
> Docs 1624 dead links

- themes/docsy/layouts/partials/head.html
> DOCS-1624-links-take2

- content/en/hub/additional-topics/reference/UIFieldDescriptions/NetworkFields.md
> DOCS-1614: Update NetworkFields.md

- content/en/hub/additional-topics/legacy/fn-legacy-docs/legacy-smb-acl.md
- content/en/hub/additional-topics/reference/SMB-references.md
> DOCS-1612: Update SMB-reference

- content/en/hub/intro/release-notes/TN12_0U1.md
Release Notes for 12.0-U1 updated with Aux Parameters name changes
> DOCS:1627-update release notes 12U1.md

- content/en/hub/intro/release-notes/TN12_0U1_1.md
Update 12.0-U1.1 Release Notes with SMB Aux. Parameters update
> DOCS-1627: update release notes 12U11.md

- content/en/hub/additional-topics/reference/UIFieldDescriptions/NetworkFields.md
- content/en/hub/initial-setup/networking/lagg.md
- content/en/hub/initial-setup/networking/vlan.md
> DOCS-1615: Update NetworkFields.md

- content/en/hub/intro/release-notes/TN12_0U1_1.md
Update Release Notes 12.0-U1.1 to reflect zlib known issue
> DOCS-1630-Add zlib to release notes.md

- content/en/hardware/mini/MiniX+HUG.md
- content/en/hardware/mini/MiniXL+HUG.md
> DOCS-1580: publish mini x+/xl+ hugs

- content/en/hub/initial-setup/storage/ImportDisk.md
- content/en/hub/initial-setup/storage/ManagingPools.md
- content/en/hub/initial-setup/storage/datasets.md
- content/en/hub/initial-setup/storage/encryption.md
- content/en/hub/initial-setup/storage/fusion-pool.md
- content/en/hub/initial-setup/storage/pools.md
- content/en/hub/initial-setup/storage/quotas.md
- content/en/hub/initial-setup/storage/sed-drives.md
- content/en/hub/initial-setup/storage/zfs-snapshots.md
- content/en/hub/initial-setup/storage/zvols.md
> DOCS-1763: Re-sort storage articles

- content/en/hub/intro/release-notes/12.0U2.md
> DOCS-1619 - 12.0U2 release notes

- content/TrueCommand/API/_index.md
> DOCS-1667:  Add nolisttrue to TC API main index

- content/TrueCommand/API/users/_index.md
> DOCS-1667: Add nolisttrue to TC API users index

- content/TrueCommand/API/teams/_index.md
> DOCS-1667: Add nolisttrue to TC API teams index

- content/TrueCommand/API/ssl/_index.md
> DOCS-1667: Add nolisttrue to TC API Sys index

- content/TrueCommand/API/servers/_index.md
> DOCS-1667: Add nolisttrue to TC API servers index

- content/TrueCommand/API/rpc/_index.md
> DOCS-1667: Add nolisttrue to TC API rpc index

- content/TrueCommand/API/reports/_index.md
> DOCS-1667: Add nolisttrue to TC API reports index

- content/TrueCommand/API/notices/_index.md
> DOCS-1667: add nolisttrue to TC API notices index

- content/TrueCommand/API/logs/_index.md
> DOCS-1667: Add nolisttrue TC API logs index

- content/TrueCommand/API/freenas/_index.md
> DOCS-1667: add nolisttrue to TC API freenas index

- content/TrueCommand/API/external/_index.md
> DOCS-1667: Add no list true TC API external index

- content/TrueCommand/API/email/_index.md
> DOCS-1667: Add no list true TC API email

- content/TrueCommand/API/data/_index.md
> DOCS-1667: no list true to TC API data index

- content/TrueCommand/API/cluster/_index.md
> DOCS-1667: no list true to TCI API cluster

- content/TrueCommand/API/alerts/_index.md
> DOCS-1667:  Add no list true TC API alerts index

- content/TrueCommand/API/alertplugins/_index.md
> DOCS-1667: Add no list true to alert plugins index

- content/en/hub/solutions/kubernetes.md
> update democratic-csi doc

- content/en/hub/intro/release-notes/12.0U2.1.md
> DOCS-1798: Publish TrueNAS 12.0-U2.1 Release Notes

- content/en/hub/scale/dev-notes.md
> Update notes about PCI Passthrough

- content/TrueCommand/Administration/AddSystems.md
> DOCS-1032: Fixing image links for AddSystems.md

- content/TrueCommand/Administration/Settings.md
> DOCS-1032: Editing graphics and updating Settings.md

- content/en/hub/sharing/iscsi/iscsi-share.md
> DOCS-1755 Added edit for linux iscsi portal discovery with CHAP

- content/en/truecommand/overview/DevNotes.md
- content/en/truecommand/overview/tc2DevNotes.md
Adding TrueCommand 2 Dev Notes
> DOCS-1827: Adding TrueCommand2 Dev Notes

- themes/docsy/layouts/partials/tags.html
> fix tag cloud

- content/en/truecommand/_index.md
> tc-links-fix

- content/en/truecommand/overview/DevNotes.md
> DOCS-1827: Fix Broken link on DevNotes.md

- content/en/hardware/_index.md
- content/en/hub/_index.md
- content/en/hub/additional-topics/reference/L2arcReference.md
- content/en/hub/intro/COREHardwareGuide.md
- content/en/hub/intro/release-notes/12.0U2.1.md
- content/en/hub/scale/tc_on_scale.md
- content/en/hub/tasks/advanced/tunables.md
- content/en/truecommand/_index.md
- content/en/truecommand/overview/DevNotes.md
- content/en/truecommand/overview/tcwhatis.md
> Review daily link check report and fix broken links

- content/Hardware/Stencils.md
- static/custom.css
> DOCS-1703: Fix Visio stencil download

- content/en/hardware/notices/eolnotices/FreeNASCertified.md
> DOCS-569 - Master Branch

- content/en/hardware/notices/eolnotices/TrueNASMiniE+.md
- content/en/hardware/notices/eolnotices/TrueNASMiniE.md
> DOCS-1821: Publish E+ EoL (master)

- content/TrueCommand/Introduction/Overview.md
- content/_index.md
- layouts/partials/site-footer.html
- layouts/partials/site-header.html
- themes/hugo-geekdoc/layouts/partials/site-footer.html
> Make Footer links non-relative

- content/en/hub/intro/release-notes/TN12_0U1.md
> DOCS-1628-Master

- content/ReleaseNotes/CORE/12.0U1.md
> DOCS-1628: Backport corruption known issue to docshubtwo

- content/CORE/Virtualization/Plugins/ManagePlugins.md
> fix markdown for relref

- content/CORE/Virtualization/Jails/Create.md
- content/CORE/Virtualization/Plugins/CreatePlugin.md
- content/CORE/Virtualization/Plugins/ManagePlugins.md
- content/CORE/Virtualization/VirtualMachines/Basic.md
- static/includes/CommunitySupportedFeature.md.part
> DOCS-1769: Unified Support Disclaimer

- content/en/hub/scale/dev-notes.md
This commit adds changes explaining how to add custom catalogs.
> Add note explaining adding custom catalogs

- content/References/Performance/InterconnectDataRates.md
- content/References/Performance/_index.md
> DOCS-1863: Publish Interconnect Maximum Effective Data Rates paper

- content/SCALE/DevNotes.md
> Port changes from PR #704

- README.md
Reworked to have a basic introduction and explain the different solutions that are used in the repository.
> DOCS-1692: Rewrite README

- CONTRIBUTING.md
> DOCS-1816: Rewrite CONTRIBUTING

- content/References/ZFSPrimer.md
Added (video) to line 181 and 185
> Edited zfsprimer.md

- content/TrueCommand/Introduction/TCTermsOfService.md
> DOCS-1771:  Add Terms of Service TC

- content/CORE/Tasks/ResilverPriority.md
- static/includes/TasksResilverPriorityFields.md.part
DOCS-1556: Improved Description of Resilver Priorities
> DOCS-1556: Description of Resilver Priorities

- content/CORE/Sharing/SMB/SMBShare.md
> Docs 1894 - mount examples

- static/includes/TasksResilverPriorityFields.md.part
> DOCS-1556: Fix a word in line 6

- content/ReleaseNotes/ReleaseSchedule.md
> DOCS-1994 remove 12.0-U3 from content/ReleaseNotes/ReleaseSchedule.md

- .github/workflows/build-preview.yml
- content/CORE/Applications/Jails/Create.md
- content/CORE/GettingStarted/Install.md
- static/includes/VirtualMachinesJailNetworking.md.part
> NAS-109837: rework VMware-deployed TrueNAS instructions for VMs

- content/Hardware/Notices/ComponentArticles/NVDIMMUpdate.md
- content/Hardware/Notices/ComponentArticles/SB327.md
Initial draft needs SME review.
> DOCS-2006: Publish NVDIMM Technical Note for M-Series

- .github/workflows/build-external-contrib.yml
- .github/workflows/build-internal-contrib.yml
one for external (forked repos)
> Split github action into two now, one for internal collaborators and

- content/ReleaseNotes/TrueCommand/2.0-Beta.md
> DOCS-2004: TrueCommand 2.0-Beta Release Notes

- content/ReleaseNotes/TrueCommand/2.0-Beta.md
- content/TrueCommand/_index.md
> DOCS-2070: Add 2.0-Beta announcement to TrueCommand home page

- content/ReleaseNotes/CORE/12.0U3.1.md
> DOCS-2079: TrueNAS 12.0-U3.1 release notes

- .github/workflows/build-external-contrib.yml
- .github/workflows/build-internal-contrib.yml
This is to remove false positives where web servers are blocking the automation from checking the URL functionality.
> Add new excludes to workflows

- content/CORE/Tasks/ReplicationTasks/Advanced.md
> DOCS-2107: zvols not used as a remote destination

- content/CORE/GettingStarted/LoggingIn.md
Added info regarding view enclosure link on dashboard
> DOCS-2115: Document View Enclosure link on Dashboard

- content/Hardware/RSeries/R20A.md
ECNs are approved and exported PDF uploaded to web server.
> Publish R20A Doc version 1.1

- content/ReleaseNotes/ReleaseSchedule.md
> DOCS-2228 / Removed TrueNAS 12.0-U4 Roadmap

- content/ReleaseNotes/CORE/12.0U4.md
> DOCS 2117 TrueNAS 12.0-U4 Release Notes

- content/ReleaseNotes/CORE/12.0U4.md
> Update 12.0U4.md - fixed typo

- content/ReleaseNotes/CORE/12.0U4.md
Remove known issue for NAS-110097: issue has been resolved in U4.
> Remove fixed known issue from U4 release notes.

- content/ReleaseNotes/CORE/12.0U4.md
Added bug ticket requested by Caleb St. john and updated total number of bug fixes to reflect that addition.
> DOCS-2117:  12.0-U4 Release Notes Additional Fixes

- layouts/_default/rss.xml
> Adjust RSS feed to use permalinks.

- content/Hardware/ExpansionShelves/ES12BSG.md
> Publish ES12 BSG v1.8

- content/ReleaseNotes/CORE/12.0U4.md
I completely missed this ticket when doing release notes first time around.  Adding to known issues now.
> DOCS-1973: TrueNAS Release Notes Minio

- content/SCALE/Storage/_index.md
DOCS-2065 SCALE Storage Section Intro
> DOCS-2065 SCALE Storage Section Intro

- content/SCALE/DataProtection/_index.md
DOCS-2209 Write Data Protection intro article
> DOCS-2209 Write Data Protection intro article

- content/CORE/Storage/SED.md
> Fix typo in parameter

- content/ReleaseNotes/TrueCommand/2.0.md
This is just an additional section on the 2.0 release notes.
> Add TrueCommand 2.0.1 changelog

- content/ReleaseNotes/CORE/12.0U4.md
Added additional known issue regarding enclosure management and the R-Series.
> DOCS-2316: Enclosure Management R Series Known issue

- content/TrueCommand/SystemManagement/TrueNASConfigManage.md
TC-1781 Automatic config db backup
Added 24 hour backup info.
> TC-1781: Update TrueCommand TrueNASConfigManage.md article

- content/ReleaseNotes/ReleaseSchedule.md
> DOCS-2339: Add 12.0-U4.1 release

- content/SCALE/GettingStarted/Post-installConfiguration.md
Remove BSD typo in SCALE documentation
> Update Post-installConfiguration.md to remove BSD reference

- content/ReleaseNotes/CORE/12.0U4.1.md
> DOCS-2338: Write U4.1 Release Notes

- content/CORE/DirectoryServices/Kerberos.md
Update Windows terminology in Kerberos article and do a grammar pass.
> DOCS-2421 Update terminology in Kerberos article

- content/TrueCommand/SystemManagement/_index.md
> TC-1805: ARC MISS  information

- content/ReleaseNotes/TrueCommand/2.0.md
Add TC 2.0.2 changelog to 2.0 release notes.
> Update TrueCommand 2.0 release notes to include 2.0.2

- content/ReleaseNotes/CORE/12.0U5.1.md
> DOCS-2440: Publish 12.0-U5.1 Release Notes

- static/custom.css
> DOCS-2345 : update tab box border color

- content/ReleaseNotes/vCenterPlugin/3.4.0.md
> DOCS-2223: Write vCenter 3.4.0 Release Notes

- content/CORE/Introduction/COREHardwareGuide.md
- content/ReleaseNotes/SCALE/21.08-BETA.1.md
- content/SCALE/Introduction/SCALEHardwareGuide.md
> DOCS-2350: SCALE 21.08.BETA.1 Release Notes

- content/ReleaseNotes/SCALE/21.08-BETA.1.md
> DOCS-2350:  Fix Typo

- layouts/partials/site-header.html
- static/custom.css
- Make theme button slightly smaller
- Remove unneeded BR in header
> DOCS-2569: Adjust sticky header margin

- content/TrueCommand/SystemManagement/SingleSystem/SingleSystemSettings.md
> TC-1825: Edit Update

- content/SCALE/SystemSettings/ScaleShell.md
> Typo fix ScaleShell.md

- content/References/ZFSDeduplication.md
> DOCS-2522: Add SHA512 To Dedup Article

- content/ReleaseNotes/CORE/12.0U5.1.md
> 12.0-U5.1 Relnotes: Add Asigra plugin upgrade note

- content/CORE/Tasks/GoogleDriveSync.md
- content/SCALE/DataProtection/CloudSyncTaskGoogleDrive.md
- content/SCALE/DataProtection/Replication.md
> DOCS-2571: Remove Double Slashes From IMG Path

- content/Hardware/RSeries/RSeriesBSG.md
> DOCS-2558 Publish R-Series 1.2 BSG

- jenkins/update-master
> Add cache clear step for faster website updates

- jenkins/update-master
Reverts truenas/documentation#1141
> Revert "Add cache clear step for faster website updates"

- content/Hardware/MSeries/MSeriesBSG.md
> DOCS-2791: Publish 3.3 M-Series BSG

- content/SCALE/SystemSettings/ServicesSCALE.md
SSH Video added under appropriate tab.
> DOCS-2643: SCALE SSH Access Video Addition

- content/SCALE/Network/_index.md
> DOCS-2640: Added Embed Video

- content/ReleaseNotes/CORE/12.0U6.1.md
> DOCS-2708: 12.0-U6.1 Release Notes

- content/ReleaseNotes/CORE/12.0U6.1.md
> Update 12.0U6.1 release notes to include security notice links

- content/CORE/DirectoryServices/ActiveDirectory.md
- content/SCALE/Credentials/DirectoryServices/_index.md
Removed references to Windows Server
> DOCS-2829 Incorrect documentation for AD

- content/ReleaseNotes/CORE/12.0U6.1.md
This CVE was for an older release, my copy/paste must have grabbed it accidently.
> remove incorrect link

- content/SCALE/Shares/_index.md
> DOCS-2644 SCALE Shares: SMB video

- content/CORE/GettingStarted/Install.md
> DOCS-2519: update key links

- static/custom.css
Adjust padding on Nav and Page elements to provide a bit of extra space on the sides when the site is viewed on a smaller screen.
Fix stickybar width
Clean up whitespace tabbing in the CSS file.
Adjust Media breaks for the longer top bar.
> DOCS-2892: Polish Docs Hub padding and incidental CSS fixes

- content/ReleaseNotes/SCALE/22.02-RC.1-2.md
> DOCS-2826: SCALE 22.02-RC.1-2 Release Notes

- content/SCALE/Storage/Pools/_index.md
Add video tutorial to the **Creating a Pool** section, removed use of will to make text active voice present tense, fixed bullet list to  parallel construction, adjusted on-screen elements to bold instead of italics, fixed a sentence that made no sense; removed double quotations as emphasis.
> DOCS-2642 Add Video Tutorial (Pool Create)

- content/SCALE/Shares/_index.md
Published the NFS Shares video, corrected grammar, style, and parallel construction issues.
> DOCS-2646 Publish NFS Shares Video

- content/Hardware/ExpansionShelves/SASConnections.md
> DOCS-2890: Update SASConnections.md

- content/TrueCommand/Clustering/ManageClusters.md
> Fix typo in ManageClusters.md

- content/TrueCommand/Clustering/ClusterVolumes.md
> Fix typo in ClusterVolumes.md

- content/ReleaseNotes/CORE/12.0U7.md
- content/SCALE/DataProtection/Replication.md
> Docs 2931 scale publish replication video

- content/ReleaseNotes/CORE/12.0U7.md
> DOCS-2744:  SMB wording fix

- content/SCALE/Storage/SnapshotsSCALE.md
Publish the new manual snapshots video
> DOCS-2909 Publish SCALE Manual Snapshots Video

- content/SCALE/DataProtection/SCALECloudSyncTasks.md
Correct voice and style issues.
> DOCS-2908 Publish SCALE Cloud Sync Video

- content/CORE/Storage/Pools/FusionPool.md
- content/SCALE/Storage/Pools/FusionPoolsScale.md
- content/_includes/FusionPools.md
> DOCS-2799: Fusion Pools/Metadata Vdevs layout

- content/SCALE/Shares/_index.md
> Docs 2645 publish scale how to configure iSCSI video

- content/ReleaseNotes/CORE/12.0U7.md
Fixed two bug ticket tickets where the links were interchanged/reversed
> DOCS-2744: Fix Link Issue

- content/SCALE/CommunityRecommends/hardened-backup-repository-for-veeam/_index.md
Add a user guide to create a hardened backup repository for Veeam Backup with TrueNAS Scale.
A hardened repository will survive to any remote attack, even if all the credentials are stolen.
> [scale] [community] Add a guide for a hardened repository for Veeam

- content/ReleaseNotes/TrueCommand/2.1.md
> Docs 2722 TC 2.1 Release Notes

- content/SCALE/SystemSettings/GeneralSettings.md
> DOCS-3053: Update System Settings > General

- content/CORE/GettingStarted/Install.md
Break out the search string from the link (it's too slow to function in automation testing or local use most of the time).
> DOCS-2986: Update pgp.mit.edu link

- content/TrueNASUpgrades/_index.md
Create a new top-level article that contains the latest information about update trains and software migrations.
> NAS-114297: Add TrueNAS Upgrades splash page

- content/Hardware/XSeries/XSeriesBSG.md
DOCS-3077 File ECN for 1.82 X-Series BSG and publish after approval
> DOCS-3077 File ECN for 1.82 X-Series BSG and publish after approval

- content/ReleaseNotes/CORE/12.0U8.md
- content/ReleaseNotes/ReleaseSchedule.md
DOCS-2968 12.0-U8 Release Notes
> DOCS-2968: 12.0-U8 Release Notes

- content/ReleaseNotes/CORE/12.0U8.md
> DOCS-3172: Add Known Issues

- content/SCALE/Credentials/LocalUsers.md
> Docs 3059 Publish SCALE Local Users Video

- content/_includes/ReplicatedEncryptedUnlock.md
> DOCS-3124: Update Unlocking Key Encrypted Replicated Dataset

- content/TrueCommand/Clustering/ClusterVolumes.md
- content/TrueCommand/Clustering/_index.md
> Docs 3185 TC cluster volumes add reverse DNS requirement Note

- content/CORE/Applications/Jails/Create.md
- content/CORE/Applications/Plugins/CreatePlugin.md
- content/CORE/Applications/Plugins/ManagePlugins.md
- content/CORE/Applications/VirtualMachines/Basic.md
- static/includes/General/CommunitySupportedFeature.md.part
- static/includes/General/EnterpriseSupportMustBeLicensed.md.part
- static/includes/General/FeatureSupport.md.part
- static/includes/General/NoEnterpriseSupport.md.part
Enterprise has access to plugins with a license. I needed to remove the "core only" comment and add Enterprise access can be aquired info.
> DOCS-3134: Add Minio and Update Plugin Docs

- content/ReleaseNotes/SCALE/22.02.0.md
> Update 22.02.0.md for new Known Issue

- content/SCALE/Storage/Pools/PermissionsSCALE.md
> Fix typo in PermissionsSCALE.md

- static/includes/General/LifecycleTable.html.part
table now reflects additional QA cycles that are run and other verbiage changes.
> DOCS-3269: update lifecycle table

- content/ReleaseNotes/SCALE/22.02.0.md
> DOCS-3271 - add NFS Known Issue

- content/SCALE/GettingStarted/MigratingFromCORE.md
> DOCS-3273: Include Scale Manual Update File Link

- content/SCALE/ScaleSecurityReports/_index.md
> DOCS-2979: SCALE Security Site

- content/_index.md
> DOCS-3488: Add link to 13.0 beta docs branch/PR

- content/ReleaseNotes/CORE/12.0U8.md
> DOCS-3480 Update 12.0U8.md

- content/CORE/GettingStarted/StoringData.md
> DOCS-3149: Pool Creation with Non-Unique Serial Numbers 13.0

- content/ReleaseNotes/CORE/12.0Beta1.md
- content/ReleaseNotes/CORE/12.0Beta2.md
- content/ReleaseNotes/CORE/12.0RC1.md
- content/ReleaseNotes/CORE/12.0Release.md
- content/ReleaseNotes/CORE/12.0U1.1.md
- content/ReleaseNotes/CORE/12.0U1.md
- content/ReleaseNotes/CORE/12.0U2.1.md
- content/ReleaseNotes/CORE/12.0U2.md
- content/ReleaseNotes/CORE/12.0U3.1.md
- content/ReleaseNotes/CORE/12.0U3.md
- content/ReleaseNotes/CORE/12.0U4.1.md
- content/ReleaseNotes/CORE/12.0U4.md
- content/ReleaseNotes/CORE/12.0U5.1.md
- content/ReleaseNotes/CORE/12.0U5.md
- content/ReleaseNotes/CORE/12.0U6.1.md
- content/ReleaseNotes/CORE/12.0U6.md
- content/ReleaseNotes/CORE/12.0U7.md
- content/ReleaseNotes/CORE/12.0U8.1.md
- content/ReleaseNotes/CORE/12.0U8.md
- content/ReleaseNotes/CORE/13.0Beta1.md
- content/ReleaseNotes/CORE/FreeNAS/_index.md
- content/ReleaseNotes/CORE/TrueNAS/_index.md
> DOCS-3462: 12.0-U8.1 Release Notes

- .github/workflows/build-internal-contrib.yml
> DOCS-3648: Update the internal-contrib.yml file

- content/References/ConceptsAndTerms.md
Reconciling Marketing ZFS Doc and the DOCS hub ZFS Terminology.
> DOCS-3655-Review-ZFS-terminology-content

- content/References/L2ARC.md
> improved some sentences in L2ARC

- content/Archive.md
- content/CORE/UIReference/Tasks/_index.md
- content/Hardware/Notices/ComponentArticles/WDSMR.md
- content/Hardware/Notices/RMAPolicy.md
- content/Hardware/Notices/_index.md
- content/References/IPMIFAQ.md
- content/SCALE/SCALEUIReference/Storage/Pools/EncryptionSCALE.md
- content/TrueCommand/API/_index.md
- content/TrueCommand/TCGettingStarted/Install/_index.md
- content/_includes/COREReleaseNotes/12.0/12.0U6.md
- content/_includes/TCReleaseNotes/1.3.2.md
Fixed up a few more redirects.
Checked the Archive and fixed a couple links to PDF converted notices.
> Update archive and add some additional aliases

- content/CORE/CORETutorials/DirectoryServices/LDAP.md
Fix typo error: Sever -> Server
> Fix typo in LDAP.md

- content/Hardware/ExpansionShelves/ES60BSG.md
> DOCS-3700  ES60 BSG Update on Powering On

- static/includes/Reference/CertificatesInternalandCSR.md.part
> Remove dead link

- content/CORE/UIReference/System/Failover.md
Commento suggestion of correction for Update to Failover.md.
> Update to Failover.md

- content/CORE/COREReleaseNotes.md
- content/SCALE/SCALEReleaseNotes.md
- content/TrueCommand/TCReleaseNotes.md
> Update software release schedules with latest dates

- content/SCALE/SCALEUIReference/Apps/UsingApps.md
> DOCS-3795: Install Official App Plex

- content/CORE/COREReleaseNotes.md
Initial Work.  Kept all Private tickets as private (and removed from document) until a further reviewer can double check my recommendations.  Updated Known Issues with fixes implemented in 13.0-U1.
> DOCS-2897: 13.0-U1-Release Notes

- content/CORE/COREReleaseNotes.md
> Add SMB shadow copy Known Issue

- content/TrueCommand/TCReleaseNotes.md
> Update 2.2 release date

- content/CORE/COREReleaseNotes.md
> DOCS-3941: 13.0-U1.1 Release Notes

- content/CORE/CORETutorials/Storage/Pools/ManagingPools.md
Reconstructs what I think was the original intention of #1350.
---
> ManagingPools.md: fix bad merge

- content/CORE/CORETutorials/DirectoryServices/ActiveDirectory.md
- content/CORE/CORETutorials/DirectoryServices/Kerberos.md
- content/CORE/CORETutorials/DirectoryServices/LDAP.md
- content/CORE/CORETutorials/DirectoryServices/NIS.md
- content/CORE/UIReference/DirectoryServices/ADScreen.md
- content/CORE/UIReference/DirectoryServices/IdmapScreen.md
- content/CORE/UIReference/DirectoryServices/KerberosScreens.md
- content/CORE/UIReference/DirectoryServices/LDAPScreen.md
- content/CORE/UIReference/DirectoryServices/NISScreen.md
Changes for style off of 3748 parent task.
> DOCS-3994 style review changes : Style review changes as part of DOCS-3748 parent branch

- content/CORE/CORETutorials/SystemConfiguration/UsingConfigurationBackups.md
Fixed while reading the docs and just casually seeing it :)
> Fix minor typo in configuration backup

- content/CORE/COREReleaseNotes.md
> Update U2 testing/release dates

- content/TrueCommand/TCReleaseNotes.md
> DOCS-2833: TC 2.2 Release Notes

- content/TrueCommand/TCGettingStarted/Install/UpdateDocker.md
- content/TrueCommand/TCReleaseNotes.md
> DOCS-2833: Add data backup warning to release notes.

- content/TrueNASUpgrades/_index.md
> DOCS-3910: Link to previous version downloads

- content/SCALE/SCALEReleaseNotes.md
> DOCS-3933: 22.02.3 release notes

- content/Archive.md
> DOCS-3977: Suggested clarification from commento

- content/SCALE/GettingStarted/FirstTimeLogin.md
> DOCS-3650: The SCALE Dashboard Tour Video

- content/References/_index.md
> DOCS-4193: Link on references needs to be updated

- content/SCALE/SCALETutorials/CommunityRecommends/hardened-backup-repository-for-veeam/_index.md
_Not sure if this is the right way to report some typos, even tough I have read the [README] and [CONTRIBUTING]._
As I skimmed [this doc][document], I just found some typos that maybe could really confuse some people.
So this PR contains fixes to the found ones.
[document]: https://www.truenas.com/docs/scale/scaletutorials/communityrecommends/hardened-backup-repository-for-veeam/
[README]: https://github.com/truenas/documentation/blob/8c0ad9b25292c31402ace801087f639133ccde2c/README.md
[CONTRIBUTING]: https://github.com/truenas/documentation/blob/8c0ad9b25292c31402ace801087f639133ccde2c/CONTRIBUTING.md
> Docs scale fix some typos in "CommunityRecommends - Hardened Backup Repository for Veeam"

- content/CORE/CORETutorials/JailsPluginsVMs/VirtualMachines/CreatingBasicVM.md
> Change Virutal to Virtual

- content/CORE/GettingStarted/LoggingIn.md
- content/SCALE/GettingStarted/FirstTimeLogin.md
> DOCS-4197: Affects of browser used in the UI

- content/SCALE/SCALEReleaseNotes.md
> Add SCALE 22.02.4 Release Schedule

- content/Contributing/IssueReporting/_index.md
> DOCS-4210: fix Jira links in Issue Reporting article

- content/CORE/CORETutorials/Storage/Pools/Permissions.md
New video for Core Users, Permissions, and ACLs.
> DOCS-4057: Users Permissions ACLs

- content/_includes/ReplicatedEncryptedUnlock.md
> DOCS-4219: Replicate without Dataset Properties

- content/_includes/TaskManagerScale.md
This branch is to document the new minimize and abort functions in SCALE Angelfish.
> DOCS-3460: Access minimalize running tasks-SCALE

- content/TrueCommand/Clusters.md
Changed descriptions to incorporate active voice / directives now that value field is part of description. Bolded some field names.
> DOCS-3298 (part 2) updated Clusters.md

- content/SCALE/SCALETutorials/Apps/UsingApps.md
> Add missing Alias

- layouts/partials/search-form.html
- layouts/partials/search-index.html
> Adjust Search Permalink

- layouts/partials/search-index.html
> DOCS-4371: adjust search for Docs Hub baseurl

- content/SCALE/GettingStarted/Install/InstallingSCALE.md
- content/SCALE/SCALETutorials/SystemSettings/UpdateSCALE.md
- content/SCALE/SCALEUIReference/SystemSettings/UpdateScreensSCALE.md
> DOCS-4314: SCALE 22.12 System Updates Warning

- content/SCALE/SCALEUIReference/Storage/Pools/PoolsScreens.md
> DOCS-4388: Update Dedup in SCALE /pools/poolsscreens/

- content/SCALE/SCALEUIReference/Apps/AppsScreensSCALE.md
> Docs 3398 update apps UI reference article 

- content/SCALE/SCALE22.12.md
Place the article above the Getting Started Guide.
> Reweight 22.12 Release Notes in Nav panel

- static/includes/Reference/TasksReplicationAddAdvancedFields.md.part
> Small typo fix

- content/SCALE/SCALETutorials/Shares/SMB/AddSMBShares.md
> incidental typo fix

- content/SCALE/SCALETutorials/Shares/WebDAV/ConfigureWebDAV.md
This commit adds a warning about changing the HTTP Authentication to Basic or No Authorization, and adds instructions to mount the share in Windows.
> Docs-4319 Update WebDAV Tutorial Content

- content/SCALE/SCALETutorials/TopToolbar/ManagingAPIKeys.md
Add some detail to make finding the API Keys page easier.
> Improve the details of finding the API Keys screen

- content/CORE/COREReleaseNotes.md
> Add 13.0-U4 tentative release date

- content/CORE/COREReleaseNotes.md
> Add anticipated 13.0-U4 release dates.

- content/TrueCommand/TCReleaseNotes.md
- Remove completed internal release milestones
- Add 2.3.0 dates
- Add anticipated 2.3.1 dates
> Update TrueCommand Release Dates

- content/SCALE/SCALETutorials/TopToolbar/SettingUpSystemEmail.md
This is what I believe the original sentence was trying to say, please comment/correct if I'm in error.
> Clarification for SMTP Authentication description

- content/Hardware/LegacyHardware/MiniSeries/TrueNAS Minis (3rd Gen)/MiniBSG(Legacy).md
internal report that this link was 404 and a quick investigation spotted that it was pointed to the wrong document. Updated the link to point to the correct doc that is available on the web server and retitled article to better reflect the content.
> Link Fix: 2nd Gen Mini Family BSG

- content/References/_index.md
Add Children shortcode and update pointer for further info.
> Quick update to References index.

- content/SCALE/SCALETutorials/Storage/_index.md
Fixing an incorrect link's syntax.
> Fix link syntax

- content/SCALE/GettingStarted/Install/SetUpSharing.md
> PD-189: typo fix for install guide/data sharing article.

- content/CORE/COREReleaseNotes.md
> Resync LDAP bug ticket title with Jira

- content/CORE/COREReleaseNotes.md
> Remove additional callout for SMB aux param adjust.

- content/CORE/COREReleaseNotes.md
> 13.0-U4 - Add known issue for Mini XL+ hardware detection

- content/SCALE/SCALETutorials/Storage/Datasets/_index.md
- content/SCALE/SCALETutorials/Storage/Pools/_index.md
- content/SCALE/SCALETutorials/Storage/_index.md
Cleaning up this index page and some of the related article descriptions.
> SCALE Tutorials/Storage index cleanup

- content/SCALE/GettingStarted/Configure/ClusterPreparation.md
- content/SCALE/GettingStarted/Configure/FirstTimeLogin.md
- content/SCALE/GettingStarted/Configure/SetUpBackupScale.md
- content/SCALE/GettingStarted/Configure/SetUpSharing.md
- content/SCALE/GettingStarted/Configure/SetUpStorageScale.md
- content/SCALE/GettingStarted/Configure/UIConfigurationSCALE.md
- content/SCALE/GettingStarted/Configure/VMandAppConfigSCALE.md
- content/SCALE/GettingStarted/Configure/_index.md
- content/SCALE/GettingStarted/Install/_index.md
- content/SCALE/SCALETutorials/Credentials/RootlessLogin.md
This commit moves articles around in the Getting Started section. It creates a new expandable for Configuration Instructions.
> PD-240 Rework Getting Started Article Navigation

- static/includes/Reference/TasksReplicationAddWizardFields.md.part
> Fix a typo

- content/SCALE/SCALETutorials/Shares/SMB/AddSMBShares.md
> Replaced FreeNAS by TrueNAS in AddSMBShares.md

- content/SCALE/GettingStarted/Configure/FirstTimeLogin.md
- content/_includes/Jobs.md
This commit updates the /GettingStarted/Configure/FirstTimeLogin.md article to serve as the introduction to the UI and the first step in the UI configuration process. 
Added snippets, reworked sections to point at other article rather than duplicate content, and added enterprise shortcode for content that applies to just Enterprise customers.
This content applies to the current release so it merges into MASTER
> PD-241 Update First Time Login Article

- content/SCALE/SCALETutorials/SystemSettings/Services/SMARTServicesSCALE.md
> PD-159 updated SMARTServicesSCALE.md

- content/SCALE/SCALETutorials/SystemSettings/General/ManageSysConfigSCALE.md
> PD-318: HA warning for System Configuration reset

- content/_index.md
> Small fix to show TC 2.3 is currently documented

- config.toml
- data/menu/more.yml
> Fix up edit links and archive location

- static/api/core_rest_api.html
- static/api/scale_rest_api.html
> Fix up api docs js calls

- static/api/core_rest_api.html
- static/api/scale_rest_api.html
> Attempt 2 - fix javascript error by changing script source

- content/SCALE/SCALE22.12.md
> Update Cobia BETA.1 schedule

- content/SCALE/SCALETutorials/SystemSettings/Services/UPSServicesSCALE.md
> Fix `UPSServicesScreenSCALE.md` page link

- content/CORE/COREReleaseNotes.md
> PD-504: 13.0-U5.1 Release Note

- content/SCALE/SCALETutorials/Credentials/RootlessLogin.md
- content/Solutions/Optimizations/Security.md
Review wider content and update to show both CORE and SCALE tutorials.
Some additions for VMs and general polish to reduce content complexity.
> PD-501: Update Security.md

- content/CORE/CoreSecurityReports/SMB1Advisory.md
- content/CORE/CoreSecurityReports/_index.md
- content/SCALE/ScaleSecurityReports/_index.md
This is a couple small updates to make these articles consistent and add links to the Best Practices article.
> PD-362: Security Notices updates

- content/SCALE/SCALE22.12.md
> Add virtualization with PCI passthrough issue to 22.12.3 relnotes

- content/Hardware/ExpansionShelves/ES60BSG.md
- content/Hardware/XSeries/XSeriesBSG.md
Update ES60 BSG to version 1.94
Update X-Series BSG to version 1.91
> Publish ECN approved BSG Versions (6/26/23)

- content/SCALE/SCALE22.12.md
- content/_includes/TNHardwareGuide.md
Fix an additional spelling error I encountered.
> PD-392: Remove drive count limitation notice for Cobia

- content/SCALE/GettingStarted/_index.md
Add a reference from the SCALE Getting Started Guide home page to Marketing's blog post and video series showcasing SCALE.
This is not version-specific and can go live immediately.
> PD-510: Add reference to SCALE Evaluation Guide

- content/CORE/GettingStarted/Install.md
- content/SCALE/GettingStarted/Install/InstallingSCALE.md
These links are currently broken and changes in this PR can go live immediately after merge.
> PD-513: update to generic text about SHA checksum util

- content/CORE/API/_index.md
- content/SCALE/SCALETutorials/Storage/Pools/Disks/ReplacingDisks.md
- content/SCALE/SCALEUIReference/Apps/LaunchDockerImageScreens.md
Find the related articles and add new aliases to redirect 404 urls.
> Ahrefs report: fix three 404 url issues

- static/custom.css
Modifies style css to improve tables, expands, and the search bar, primarily improving docs hub display in dark mode
> PD-507: Update custom.css for light/dark mode improvements

- content/CORE/CORETutorials/Network/_index.md
- content/SCALE/SCALEPreviousVersion.md
> Couple small bugfixes

- content/SCALE/SCALETutorials/Storage/Pools/SLOGOverprovisionSCALE.md
Updating link to the Seagate SSD Over-Provisioning And Its Benefits article
> Update Link to Seagate SSD Over-Provisioning And Its Benefits Article

- content/GettingStarted/SCALEReleaseNotes.md
> Add note about zfs dataset legacy mountpoint property to release notes

- .github/workflows/build-external-contrib.yml
- .github/workflows/build-internal-contrib.yml
> Update workflows to use Hugo 0.117 for build tests

- content/TrueCommand/SystemManagement/TrueNASConfigManage.md
- content/TrueCommand/TCGettingStarted/InitialConfig.md
Found two files to update with the latest behavior in 2.3.4
> PD-653: Update TrueNAS Config Backup content

- content/TrueCommand/TCGettingStarted/Install/InstallTCCloud.md
Adjust the earlier link for Support to go directly to the Support site and use the include snippet for the customer support phone numbers.
> PD-570: Add iX portal 2FA copy

- content/TrueCommand/TCReleaseNotes.md
- words-to-ignore.txt
Added changelog, updated 2.3.5 release dates to TBD and added simple description of update.
> PD-596: TC 2.3.4 release notes

- content/_includes/TNHardwareGuide.md
Adds more details about Intel ECC support.
> Expand details about Intel ECC support

- content/SCALE/GettingStarted/Configure/SetUpSharing.md
- content/SCALE/GettingStarted/Configure/UIConfigurationSCALE.md
- content/SCALE/SCALECLIReference/Account/CLIgroup.md
- content/SCALE/SCALECLIReference/Account/CLIuser.md
- content/SCALE/SCALECLIReference/_index.md
- content/_includes/CLI/HintInteractiveArgsEditor.md
> master branch  `\_includes\` fix

- content/SCALE/SCALE22.12.md
This is a quick fix to an incorrect year in the release schedule. Note that this entire article will be getting purged as part of resetting master branch to track the latest nightly developments.
> PD-672: Typo fix for 22.12 release notes (master branch)

- jenkins/update-22.12
> Patch for scale 22.12 id 584

- content/CORE/_index.md
- content/SCALE/_index.md
- layouts/partials/docs-nav.html
- layouts/shortcodes/section-cards.html
- words-to-ignore.txt
Master branch content rework is pending.
Commits from this PR and a first build of the 22.12 branch are staged at the internal test website for review.
This PR includes the changes originally proposed from #2097 so that it's easier for me to internally test changes and polish up the master branch version switch behavior.
> PD-618: Update DOCSNAV for 13.0, 22.12, and 2.3 branches and start setting up master as nightly dev tracking branch

- content/CORE/_index.md
- content/SCALE/_index.md
- content/TrueCommand/_index.md
> PD-618: Remove aliases from product section master index files

- content/GettingStarted/Configure/FirstTimeLogin.md
- content/SCALEUIReference/Credentials/LocalUsersScreensSCALE.md
- content/_includes/StatusofTrueCommand.md
Ports update from 23.10 changes back to bluefin. Also fixes issue with a missing snippet file in the 22.12 branch.
> Pd 514 document disabling admin password is forbidden

- content/CORE/CORETutorials/Sharing/NFSShare.md
- content/CORE/CORETutorials/Sharing/SMB/SMBShare.md
- content/CORE/CORETutorials/Sharing/WebDAVShare.md
- content/_includes/ShareDatasetsNotPools.md
- content/_includes/SharingPrereqs.md
Annnd ports 13.0 changes to master branch.
> Pd 646 create snippet for shares do not use a pool for share master

- content/SCALECLIReference/System/CLIGeneral.md
Updates article to clarify rollback function behavior
> PD-454-cli-guide-document-system-general-namespace

- content/_index.md
> Fix 13.0 release notes link from home page

- content/SCALECLIReference/System/CLIReporting.md
> PD-460-cli-guide-document-system-reporting-namespace

- content/SCALETutorials/SystemSettings/Advanced/ManageSysLogsSCALE.md
- content/SCALEUIReference/SystemSettings/AdvancedSettingsScreen.md
> Pd 680 improve syslog docs

- jenkins/update-2310
update-2310 for push zone for cdn.  will improve page speed for international users.
> ID-629 Update update-2310

- content/API/_index.md
- content/GettingStarted/SCALEReleaseNotes.md
- content/SCALEUIReference/DataProtection/ReplicationScreensSCALE.md
- content/_includes/SCALEWebDAVDeprecation.md
- static/api/scale_rest_api.html
- words-to-ignore.txt
- Review resolved ticket list and update docs articles as needed.
- Update API docs.
- Write 22.12.4 release notes according to the simplified style. Release notes URL will be https://www.truenas.com/docs/scale/22.12/gettingstarted/scalereleasenotes/
- Local build test
NOTE: merging this requires asking iX IT for a CDN update so that the changes can go live immediately.
> PD-692: 22.12.4 docs

- content/API/_index.md
- content/GettingStarted/SCALEReleaseNotes.md
- content/SCALEUIReference/DataProtection/ReplicationScreensSCALE.md
- content/_includes/SCALEWebDAVDeprecation.md
- static/api/scale_rest_api.html
- words-to-ignore.txt
This should not be merged until 22.12.4 is actually released (target date 3 October)
> Revert "PD-692: 22.12.4 docs"

- content/GettingStarted/SCALEReleaseNotes.md
Add note about VM display button and link to Jira issue for more details.
> (23.10) Update 23.10-RC.1 SCALEReleaseNotes.md

- content/API/_index.md
- content/GettingStarted/SCALEReleaseNotes.md
- content/SCALEUIReference/DataProtection/ReplicationScreensSCALE.md
- content/_includes/SCALEWebDAVDeprecation.md
- static/api/scale_rest_api.html
- words-to-ignore.txt
Changes in this PR document changes that are not publicly available until after 22.12.4 is released.
DO NOT MERGE BEFORE RELEASE DAY (target 4 October)
> PD-692: 22.12.4 docs (Reopened)

- layouts/_default/baseof.html
- static/js/anchorpad.js
Ports changes from "Pd 698 investigate anchor points scrolling to below the anchor text"
> PD-698-port-to-23.10

- layouts/_default/baseof.html
- static/js/anchorpad.js
Ports changes from "Pd 698 investigate anchor points scrolling to below the anchor text"
> PD-698-port-to-22.12

- layouts/_default/baseof.html
- static/js/anchorpad.js
Ports changes from "Pd 698 investigate anchor points scrolling to below the anchor text"
> PD-698-port-to-13.0

- layouts/_default/baseof.html
- static/js/anchorpad.js
Ports changes from "Pd 698 investigate anchor points scrolling to below the anchor text"
> Pd 698 port to 2.3

- static/js/anchorpad.js
> Pd 698 port to 13.0

- jenkins/update-master
- layouts/partials/search-form.html
- static/js/search.js
> Fea/id 344/page find integration

- content/GettingStarted/SCALEReleaseNotes.md
Quick draft notes for this hotpatch.
> PD-806: 22.12.4.1 hotpatch release notes

- content/Solutions/Integrations/VMware/vCenterPlugin.md
Replaces raw html table (and font styling that was causing the problem) with a truetable.
> PD-779-all-text-on-this-page-is-smaller

- content/GettingStarted/SCALEReleaseNotes.md
- Add notice to 22.12.4.1 notes
- Add draft notes for 22.12.4.2 release.
> PD-809: 22.12.4.2 relnotes updates

- content/_includes/MinIOEnterpriseFirstSteps.md
Make a minor change to a nested snippet to watch the impact to the master branch.
> PD-812: quick check on snippet change

- content/SCALE/SCALETutorials/Apps/EnterpriseApps/MinIO/ConfigMinioEnterpriseMNMD.md
> PD-812: typo fix

- content/SCALETutorials/ConfigReportsScale.md
- content/SCALEUIReference/ReportingScreensSCALE.md
- content/_includes/AlertsCategories.md
- content/_includes/SystemReportingFields.md
- words-to-ignore.txt
Removes config form from UI ref and tutorial. Also scrubs some links to/mentions of collectd.
> Pd 755 remove reporting config form

- content/UIReference/Storage/Pools/PoolsScreens.md
> PD-811: typo fix backport for 13.0 branch

- content/SCALETutorials/Apps/EnterpriseApps/MinIO/ConfigMinioEnterpriseMNMD.md
master branch is already fixed - this is a cherry-pick of that fix to 23.10 branch.
> PD-812: typo fix (23.10 cherry-pick)

- content/SCALE/SCALETutorials/Credentials/ManageLocalUsersSCALE.md
> PD-801: typo fix for managelocalusersscale.md (master)

- content/GettingStarted/SCALEReleaseNotes.md
> PD-820: Known Issue for TrueNAS Enterprise system NIC name change on upgrade

- content/SCALE/SCALETutorials/Credentials/ManageLocalUsersSCALE.md
> PD-821: typo fix for managelocalusersSCALE (master)

- static/custom.css
Finding breakage to the Docs Hub home page - reverting this as part of determining if this broke the tab box behavior.
Reverts truenas/documentation#2262
> Revert "Pd 794 improve cli documentation styling in dark mode"

- layouts/shortcodes/expand.html
> PD-819-expand-shortcode-copy-link-button-not-working-as-expected

- content/CORE/CORETutorials/Storage/Pools/Datasets.md
- content/_includes/CreateDatasetSCALE.md
Add to both CORE and SCALE impacted tutorials.
> Add dataset Sync field recommendations

- content/CORE/CORETutorials/Services/ConfigureUPS.md
- content/SCALE/SCALETutorials/SystemSettings/Services/UPSServicesSCALE.md
- content/_includes/NUTsupport.md
> Pd 695 nut dont working with powercom bnt 1000 ap

- content/SCALE/SCALETutorials/Apps/EnterpriseApps/Syncthing.md
> Update Syncthing.md - image path typo

- static/custom.css
Reverts truenas/documentation#2264.
This needs additional review to avoid breaking home page styling when the browser defaults to different light or dark color schemes.
> Re-review "Pd 794 improve cli documentation styling in dark mode""

- content/_includes/CLI/HintInteractiveArgsEditor.md
> (master) Update HintInteractiveArgsEditor.md

- content/_includes/TCPermissionsHierarchy.md
- static/custom.css
Restyle this particular mermaid chart, but done generically so we can reuse the CSS values elsewhere if desired. Fix the display issues and clean up text a bit on the flowchart.
> Fix up mermaid flowchart for TC user/group permissions (master)

- content/SCALE/GettingStarted/Configure/UIConfigurationSCALE.md
- content/SCALE/SCALECLIReference/Account/CLIgroup.md
- content/SCALE/SCALECLIReference/Network/_index.md
- layouts/_default/baseof.html
- layouts/shortcodes/expand.html
- layouts/shortcodes/nest-expand.html
- static/custom.css
> Expand shortcode rework

- static/api/core_rest_api.html
- static/api/core_websocket_api.html
> Pd 688 api docs

- layouts/_default/baseof.html
- layouts/partials/menu.html
- layouts/partials/toc-panel.html
- static/custom.css
This is a WIP demo of a three-panel layout for the website.
TODO:
- sizing adjustments to handle the right panel on small screens and mobile devices.
- develop automation that populates the toc-panel with links to headers within the current article.
- lots of testing
> Adjust website layout

- content/TrueCommand/TCGettingStarted/Install/InstallTCCloud.md
- content/TrueCommand/TCGettingStarted/Install/InstallTCDocker.md
- content/TrueCommand/TCGettingStarted/Install/UpdateDocker.md
This commit makes minor style and text changes to the UpdateDocker.md, InstallTCDocker.md, and InstallTCCloud.md articles.
> PD-545 Review and Update Install Articles

- i18n/en.yaml
- layouts/_default/baseof.html
- layouts/partials/menu.html
- layouts/partials/site-footer.html
- layouts/partials/site-header.html
- layouts/partials/toc-panel.html
- static/custom.css
> Cli webdev: latest site experiments

- content/Hardware/MSeries.md
- content/Hardware/Mini.md
- content/Hardware/RSeries.md
- content/Hardware/XSeries.md
also incidental fix for wording issue
> Quick fix for alias issue

- layouts/partials/site-header.html
- static/custom.css
> Cli webdev

- layouts/partials/site-header.html
- layouts/partials/toc-panel.html
- static/custom.css
> Cli webdev finalize

- themes/hugo-geekdoc/layouts/robots.txt
> Add a few more sections to be ignored by indexing.

- content/CORE/CORETutorials/JailsPluginsVMs/Plugins/MinIOPlugin.md
- content/CORE/CORETutorials/JailsPluginsVMs/_index.md
> Pd 860 update core min io plugin content for 13 1

- content/GettingStarted/23.10Upgrades.md
> Update 23.10Upgrades.md - port release notes caution when upgrading from Bluefin

- content/CORE/CORETutorials/Storage/Disks/DiskReplace.md
This PR updates the CORE DiskReplace.md tutorial by adding the Refresh option, a summary step procedure, a new section on replacing the disk, and additional content in bringing an offline disk online.
> Pd 850 update core disk replace.md article

- content/TrueCommand/AdminGuide/_index.md
- content/TrueCommand/UserGuide/_index.md
> Fix incorrect links

- content/SCALEUIReference/SCALEDashboard.md
- content/SCALEUIReference/TopToolbar/Settings/_index.md
Found the 2fa button was missing and there was an obsolete reference to the Preferences button.
> 23.10 UI Reference check - Top Menu/Settings update

- content/GettingStarted/COREReleaseNotes.md
This was a late relation to the Jira release tracker; following up now to make sure the link is present in the relnotes.
> Add NAS issue link to U6.1

- content/SCALE/SCALETutorials/SystemSettings/Advanced/ManageGlobal2FASCALE.md
Note that additional changes of 2FA field names and behaviors might be forthcoming in Dragonfish, but this is current as of the 12/12 nightly build
> (master) Quick review of 2FA behaviors in DF nightly and expand text a little

- content/CORE/CORETutorials/JailsPluginsVMs/Plugins/MinIOPlugin.md
- content/Contributing/IssueReporting/_index.md
- content/Hardware/Notices/_index.md
- content/SCALE/SCALEUIReference/Shares/SMBSharesScreens.md
- content/TrueCommand/AdminGuide/Admin/LDAPServers.md
- content/TrueCommand/UserGuide/SystemManagement/_index.md
- layouts/_default/baseof.print.html
- layouts/partials/print/content.html
Reviewed the results of the automatic ref testing and identified some refinements to make with print view generation and an early catch of some syntax issues.
These changes will go in as part of getting the automatic testing online and results pared down as we keep looking for false positives or other refinements to make.
> ID-890: Printview review

- content/CORE/UIReference/ReportingGraphs.md
> Update ReportingGraphs.md - typo

- content/SCALE/SCALETutorials/Apps/EnterpriseApps/MinIO/_index.md
Added references to Veeam Backup and Replication.
> Add Veeam References to MinIO Enterprise app

- content/SCALETutorials/Virtualization/AddManageVMDevicesSCALE.md
- content/SCALETutorials/Virtualization/CreatingManagingVMsSCALE.md
- content/SCALEUIReference/VirtualizationScreens.md
Remove VNC mentions for agnostic text.
Add note about SPICE remote access clients for users who want to access their VM from outside the TrueNAS interface.
> (23.10) Add a little spice.

- content/TrueCommand/TCGettingStarted/TCReleaseNotes.md
- layouts/partials/docs-nav.html
- layouts/shortcodes/section-cards.html
Not to be merged until the 3.0 version branch is prepped and ready for pipeline integration.
- Remove alias from TC nightly release notes so the new 3.0 branch will properly catch that incoming traffic.
- Update Docs Hub version switcher for 3.0 branch option.
- Update Docs Hub home page TC section card so the 3.0 branch is stable and not part of nightly development
> PD-762: master branch changes for TC 3.0 version branch publish

- layouts/partials/docs-nav.html
> PD-762 (TC 2.3 branch): update version switcher to add 3.0 branch

- layouts/partials/docs-nav.html
> PD-762 (13.0): update version switcher to add 3.0 branch

- layouts/partials/docs-nav.html
> PD-762 (23.10 branch): update version switcher to add 3.0 branch

- layouts/partials/docs-nav.html
> PD-762 (22.12 branch): update version switcher to add 3.0 branch

- content/GettingStarted/SCALEReleaseNotes.md
- words-to-ignore.txt
> (23.10.1) Add known issue for non-physical network interfaces

- layouts/shortcodes/section-cards.html
Small change to update the next tab for CORE and SCALE to indicate the next major versions.
> Update home page section cards

- content/CORE/CORETutorials/JailsPluginsVMs/VirtualMachines/_index.md
- content/_includes/COREFeatureSupport.md
Update this snippet to indicate the status of the Virtualization, Plugin, and Jails features in CORE 13.1. Direct readers with a critical need to TrueNAS SCALE. Initial proposal shared internally for review; will update based on feedback.
> PD-961: rework COREFeatureSupport snippet for 13.1

- layouts/partials/page-header.html
- static/custom.css
Cherry pick and rework the nightly docs solution for indicating the active software documentation.
> Whereami note ported to 13.0

- layouts/partials/page-header.html
Port the master branch updated solution and adjust slightly for the SCALE 23.10 branch.
> Whereami notice for 23.10 branch

- layouts/partials/page-header.html
> whereami notice port to 22.12 branch
